Repository strapi/strapi, pull requests merged in 2018-04, with the labels that each got.

#869 Replace server host by localhost
  packages/strapi-generate-new/files/config/environments/development/server.json
  packages/strapi-generate-new/files/config/environments/production/server.json
  packages/strapi-generate-new/files/config/environments/staging/server.json
Labels: pr: 🐛 Bug fix, source: framework

#854 Upload feature: add Cloudinary
  packages/strapi-upload-cloudinary/.editorconfig
  packages/strapi-upload-cloudinary/.gitattributes
  packages/strapi-upload-cloudinary/.gitignore
  packages/strapi-upload-cloudinary/README.md
  packages/strapi-upload-cloudinary/lib/index.js
  packages/strapi-upload-cloudinary/package.json
Labels: pr: 🚀 New feature, source: plugin

#848 Allow default values in ctb
  packages/strapi-plugin-content-manager/admin/src/components/Edit/index.js
  packages/strapi-plugin-content-manager/admin/src/containers/EditPage/actions.js
  packages/strapi-plugin-content-manager/admin/src/containers/EditPage/index.js
  packages/strapi-plugin-content-manager/admin/src/containers/EditPage/reducer.js
  packages/strapi-plugin-content-type-builder/admin/src/components/PopUpForm/index.js
  packages/strapi-plugin-content-type-builder/admin/src/containers/Form/actions.js
  packages/strapi-plugin-content-type-builder/admin/src/containers/Form/forms.json
  packages/strapi-plugin-content-type-builder/admin/src/containers/Form/index.js
  packages/strapi-plugin-content-type-builder/admin/src/containers/ModelPage/actions.js
  packages/strapi-plugin-content-type-builder/admin/src/containers/ModelPage/index.js
  packages/strapi-plugin-content-type-builder/admin/src/translations/de.json
  packages/strapi-plugin-content-type-builder/admin/src/translations/en.json
  packages/strapi-plugin-content-type-builder/admin/src/translations/fr.json
  packages/strapi-plugin-content-type-builder/admin/src/translations/pl.json
  packages/strapi-plugin-content-type-builder/admin/src/translations/tr.json
  packages/strapi-plugin-content-type-builder/admin/src/translations/zh.json
Labels: pr: 💅 Enhancement, source: plugin

#890 Center logo
  packages/strapi-admin/admin/src/components/LeftMenuHeader/styles.scss
Labels: pr: 💅 Enhancement, source: admin

#895 Review bookshelf filters
  packages/strapi-bookshelf/lib/index.js
  packages/strapi-bookshelf/package.json
  packages/strapi-generate-api/templates/bookshelf/service.template
  packages/strapi-plugin-content-manager/config/queries/bookshelf.js
Labels: pr: 🐛 Bug fix, source: framework

#896 Improve german translation
  packages/strapi-admin/admin/src/translations/de.json
Labels: pr: 💅 Enhancement, source: admin

#910 Improve german translations
  packages/strapi-plugin-settings-manager/admin/src/translations/de.json
  packages/strapi-plugin-upload/admin/src/translations/de.json
  packages/strapi-plugin-users-permissions/admin/src/translations/de.json
Labels: pr: 💅 Enhancement, source: Plugin

#912 Handle default values with Bookshelf
  packages/strapi-bookshelf/lib/index.js
  packages/strapi-bookshelf/package.json
  packages/strapi-knex/package.json
Labels: pr: 💅 Enhancement, source: Plugin

#918 Add find one file endpoint
  packages/strapi-plugin-upload/config/routes.json
  packages/strapi-plugin-upload/controllers/Upload.js
Labels: pr: 💅 Enhancement, source: Plugin

#892 Losing OneToOne relation in the content manager
  packages/strapi-plugin-content-manager/config/queries/mongoose.js
Labels: pr: 🐛 Bug fix, source: Plugin

#928 Fixed issue for connection settings and ssl prop
  packages/strapi-mongoose/lib/index.js
Labels: pr: 🐛 Bug fix, source: Framework

#933 Handle polymorphic in content manager
  packages/strapi-plugin-content-manager/admin/src/components/EditRelations/index.js
  packages/strapi-plugin-content-manager/admin/src/containers/EditPage/index.js
  packages/strapi-plugin-content-manager/config/queries/mongoose.js
  packages/strapi-plugin-content-manager/services/ContentManager.js
  packages/strapi-plugin-users-permissions/models/User.settings.json
Labels: pr: 💅 Enhancement, source: Plugin

#934 Fix project npm run setup
  packages/strapi-admin/admin/src/config/manifest.json
  packages/strapi-admin/package.json
  packages/strapi-helper-plugin/lib/internals/webpack/webpack.base.babel.js
  packages/strapi-helper-plugin/package.json
Labels: pr: 🐛 Bug fix, source: Framework

#935 Update Getting Started docs to show correct sort parameter
  docs/3.x.x/en/getting-started/quick-start.md
Labels: pr: 💅 Enhancement, source: Admin

#937 Add strapi version on left menu
  packages/strapi-admin/admin/src/components/LeftMenuFooter/index.js
  packages/strapi-admin/admin/src/containers/AdminPage/actions.js
  packages/strapi-admin/admin/src/containers/AdminPage/constants.js
  packages/strapi-admin/admin/src/containers/AdminPage/index.js
  packages/strapi-admin/admin/src/containers/AdminPage/reducer.js
  packages/strapi-admin/admin/src/containers/AdminPage/saga.js
  packages/strapi-admin/admin/src/containers/LeftMenu/index.js
  packages/strapi-admin/config/routes.json
  packages/strapi-admin/controllers/Admin.js
Labels: pr: 💅 Enhancement, source: Admin

#938 Allow to pass custom input type and components to the lib
  docs/3.x.x/en/plugin-development/ui-components.md
  packages/strapi-helper-plugin/lib/src/components/InputsIndex/index.js
Labels: pr: 💅 Enhancement, source: Admin

#944 Add Russian language in admin
  packages/strapi-admin/admin/src/translations/ru.json
Labels: pr: 💅 Enhancement, source: Admin

#963 Fix docs typo
  docs/3.x.x/en/guides/graphql.md
Labels: pr: 💅 Enhancement, source: Documentation

#965 Staging config as production config
  packages/strapi-generate-new/files/config/environments/staging/request.json
Labels: pr: 💅 Enhancement, source: Framework

#982 Fix symlinks during project generation
  packages/strapi-generate-new/lib/after.js
Labels: pr: 🐛 Bug fix, source: Framework

#969 Fix invalid timestamp default values for MySQL 5.7
  packages/strapi-plugin-upload/config/functions/bootstrap.js
  packages/strapi-plugin-users-permissions/services/UsersPermissions.js
Labels: pr: 💅 Enhancement, source: Framework

#953 Reduce setup monorepo
  docs/3.x.x/en/plugin-development/quick-start.md
  package.json
  packages/strapi-admin/admin/src/containers/HomePage/index.js
  packages/strapi-admin/package.json
  packages/strapi-generate-new/json/package.json.js
  packages/strapi-generate-plugin/json/package.json.js
  packages/strapi-plugin-content-manager/package.json
  packages/strapi-plugin-content-type-builder/package.json
  packages/strapi-plugin-email/package.json
  packages/strapi-plugin-settings-manager/package.json
  packages/strapi-plugin-upload/package.json
  packages/strapi-plugin-users-permissions/package.json
  scripts/setup.js
Labels: pr: 💅 Enhancement, source: Admin

#974 Fix search select
  packages/strapi-mongoose/lib/index.js
  packages/strapi-plugin-content-manager/admin/src/components/SelectMany/index.js
  packages/strapi-plugin-content-manager/admin/src/components/SelectOne/index.js
  packages/strapi-plugin-users-permissions/models/User.settings.json
Labels: pr: 🐛 Bug fix, source: Plugin

#1003 Use latest release of Mongoose & add comment to explain post remove c…
  packages/strapi-mongoose/lib/index.js
  packages/strapi-mongoose/package.json
Labels: pr: 💅 Enhancement, source: Framework

#1001 Fix loose of file relation & select latest associated file
  packages/strapi-mongoose/lib/index.js
  packages/strapi-plugin-content-manager/config/queries/bookshelf.js
  packages/strapi-plugin-content-manager/config/queries/mongoose.js
Labels: pr: 🐛 Bug fix, source: Plugin

#1019 Improve Decimal128 and Float support with MongoDB
  packages/strapi-mongoose/lib/index.js
  packages/strapi-mongoose/lib/utils/index.js
  packages/strapi-plugin-content-manager/controllers/ContentManager.js
Labels: pr: 🐛 Bug fix, source: Framework

#1017 Ignore file model in the CTB
  packages/strapi-plugin-content-type-builder/services/ContentTypeBuilder.js
Labels: pr: 💅 Enhancement, source: Plugin

#996 Update LeftMenuFooter style
  packages/strapi-admin/admin/src/components/LeftMenuFooter/index.js
  packages/strapi-admin/admin/src/components/LeftMenuFooter/styles.scss
Labels: pr: 💅 Enhancement, source: Admin

#1020 Move authentication and ssl in database options
  packages/strapi-generate-new/files/config/environments/production/database.json
  packages/strapi-generate-new/files/config/environments/staging/database.json
  packages/strapi-generate-new/lib/before.js
  packages/strapi-mongoose/lib/index.js
  packages/strapi-mongoose/lib/utils/connectivity.js
Labels: pr: 💅 Enhancement, source: Framework

#1021 Reorder model root attributes and remove "multiple" key
  packages/strapi-plugin-content-type-builder/controllers/ContentTypeBuilder.js
  packages/strapi-plugin-content-type-builder/services/ContentTypeBuilder.js
Labels: pr: 💅 Enhancement, source: Plugin

#1028 Fix beforeCreate lifecycle
  packages/strapi-mongoose/package.json
  packages/strapi-plugin-content-manager/config/queries/bookshelf.js
  packages/strapi-plugin-content-manager/config/queries/mongoose.js
Labels: pr: 🐛 Bug fix, source: Framework

#1026 check if `strapi start` runs inside a strapi project
  packages/strapi/bin/strapi-start.js
Labels: pr: 💅 Enhancement, source: Framework

#1043 Block settings-manager & content-type-builder in production
  packages/strapi-admin/admin/src/components/LeftMenuFooter/styles.scss
  packages/strapi-admin/admin/src/containers/AdminPage/actions.js
  packages/strapi-admin/admin/src/containers/AdminPage/constants.js
  packages/strapi-admin/admin/src/containers/AdminPage/index.js
  packages/strapi-admin/admin/src/containers/AdminPage/reducer.js
  packages/strapi-admin/admin/src/containers/AdminPage/saga.js
  packages/strapi-mongoose/package.json
Labels: pr: 💅 Enhancement, source: Plugin

#1033 Improve webpack config
  packages/strapi-admin/admin/src/config/manifest.json
  packages/strapi-admin/package.json
  packages/strapi-admin/scripts/preSetup.js
  packages/strapi-admin/scripts/setup.js
  packages/strapi-helper-plugin/lib/internals/scripts/loadAdminConfigurations.js
  packages/strapi-helper-plugin/lib/internals/webpack/webpack.base.babel.js
  packages/strapi-helper-plugin/lib/internals/webpack/webpack.dev.babel.js
  packages/strapi-helper-plugin/lib/internals/webpack/webpack.prod.babel.js
  packages/strapi-plugin-content-manager/package.json
  packages/strapi-plugin-content-type-builder/package.json
  packages/strapi-plugin-settings-manager/package.json
  packages/strapi-plugin-upload/package.json
  packages/strapi-plugin-users-permissions/package.json
  packages/strapi/lib/Strapi.js
Labels: pr: 💅 Enhancement, source: Framework

#1044 Fixes multiple relationships on different models name
  packages/strapi-plugin-content-type-builder/admin/src/containers/Form/reducer.js
  packages/strapi-plugin-content-type-builder/admin/src/containers/Form/utils/attributeValidations.js
Labels: pr: 🐛 Bug fix, source: Plugin

#1045 Fixes DatePicker display
  packages/strapi-helper-plugin/lib/src/components/InputDate/index.js
Labels: pr: 💅 Enhancement, source: Plugin

#1046 Fixes settings-manager language deletion bug
  packages/strapi-plugin-settings-manager/controllers/SettingsManager.js
Labels: pr: 🐛 Bug fix, source: Plugin

#1049 Fix for host not in config.url
  packages/strapi/lib/core/configurations.js
Labels: pr: 🐛 Bug fix, source: Framework

#1047 Fixes WYSIWYG insert image position
  packages/strapi-helper-plugin/lib/src/components/Wysiwyg/index.js
Labels: pr: 🐛 Bug fix, source: Admin

#1025 Improve SQL experience
  packages/strapi-bookshelf/lib/index.js
  packages/strapi-bookshelf/lib/utils/connectivity.js
  packages/strapi-bookshelf/package.json
  packages/strapi-generate-new/lib/before.js
  packages/strapi-plugin-content-manager/config/layout.json
  packages/strapi-plugin-content-manager/config/queries/bookshelf.js
  packages/strapi-plugin-settings-manager/admin/src/translations/de.json
  packages/strapi-plugin-settings-manager/admin/src/translations/en.json
  packages/strapi-plugin-settings-manager/admin/src/translations/fr.json
  packages/strapi-plugin-settings-manager/admin/src/translations/pl.json
  packages/strapi-plugin-settings-manager/admin/src/translations/ru.json
  packages/strapi-plugin-settings-manager/admin/src/translations/tr.json
  packages/strapi-plugin-settings-manager/admin/src/translations/zh.json
  packages/strapi-plugin-settings-manager/services/SettingsManager.js
  packages/strapi-plugin-upload/config/functions/bootstrap.js
  packages/strapi-plugin-upload/models/File.settings.json
  packages/strapi-plugin-users-permissions/config/functions/bootstrap.js
  packages/strapi-plugin-users-permissions/config/queries/bookshelf.js
  packages/strapi-plugin-users-permissions/services/UsersPermissions.js
  packages/strapi/lib/Strapi.js
  packages/strapi/lib/core/store.js
Labels: pr: 💅 Enhancement, source: Framework

#1052 Remove plugin key for API model
  packages/strapi-plugin-content-type-builder/services/ContentTypeBuilder.js
Labels: pr: 🐛 Bug fix, source: Plugin

#1056 Update CONTRIBUTING GUIDE
  CONTRIBUTING.md
Labels: pr: 💅 Enhancement, source: Documentation

#1060 Add migration guide 11 to 12 in the menu
  docs/3.x.x/en/SUMMARY.md
Labels: pr: 💅 Enhancement, type: documentation 📖
