Repository strapi/strapi, pull requests merged in 2018-12, with the labels that each got.

#2430 Revert filter PR
  docs/3.x.x/guides/filters.md
  packages/strapi-admin/admin/src/config/manifest.json
  packages/strapi-generate-admin/package.json
  packages/strapi-generate-api/package.json
  packages/strapi-generate-api/templates/bookshelf/service.template
  packages/strapi-generate-api/templates/mongoose/service.template
  packages/strapi-generate-controller/package.json
  packages/strapi-generate-model/package.json
  packages/strapi-generate-new/json/package.json.js
  packages/strapi-generate-new/package.json
  packages/strapi-generate-plugin/package.json
  packages/strapi-generate-policy/package.json
  packages/strapi-generate-service/package.json
  packages/strapi-generate/package.json
  packages/strapi-hook-bookshelf/lib/index.js
  packages/strapi-hook-bookshelf/lib/relations.js
  packages/strapi-hook-bookshelf/package.json
  packages/strapi-hook-ejs/package.json
  packages/strapi-hook-knex/package.json
  packages/strapi-hook-mongoose/lib/index.js
  packages/strapi-hook-mongoose/lib/relations.js
  packages/strapi-hook-mongoose/lib/utils/index.js
  packages/strapi-hook-mongoose/package.json
  packages/strapi-hook-redis/package.json
  packages/strapi-lint/package.json
  packages/strapi-middleware-views/package.json
  packages/strapi-plugin-graphql/services/Query.js
  packages/strapi-plugin-settings-manager/package.json
  packages/strapi-plugin-users-permissions/config/queries/bookshelf.js
  packages/strapi-plugin-users-permissions/config/queries/mongoose.js
  packages/strapi-provider-email-amazon-ses/package.json
  packages/strapi-provider-email-mailgun/package.json
  packages/strapi-provider-email-sendgrid/package.json
  packages/strapi-provider-email-sendmail/package.json
  packages/strapi-provider-upload-aws-s3/package.json
  packages/strapi-provider-upload-local/package.json
  packages/strapi-utils/lib/models.js
  packages/strapi-utils/package.json
  packages/strapi/package.json
Labels: pr: 🐛 Bug fix, source: Framework

#2354 Fix path of contentTypesToShow
  packages/strapi-admin/admin/src/components/LeftMenuLinkContainer/index.js
Labels: pr: 🐛 Bug fix, source: Admin

#2331 Fix mongoose float and decimal problems
  packages/strapi-hook-mongoose/lib/utils/index.js
Labels: pr: 🐛 Bug fix, source: Framework

#2414 Remove .npmignore from generated files.
  packages/strapi-generate-new/lib/index.js
Labels: pr: 💅 Enhancement, source: Framework

#2440 Revert FA language
  packages/strapi-admin/admin/src/config/languages.json
  packages/strapi-admin/admin/src/containers/LocaleToggle/index.js
  packages/strapi-admin/admin/src/translations/fa.json
Labels: pr: 💅 Enhancement, source: Admin

#2454 Review plugin install logs
  packages/strapi/bin/strapi-install.js
  packages/strapi/package.json
Labels: pr: 💅 Enhancement, source: Framework

#2469 Fix to allow provider to be shown in the content manager
  packages/strapi-plugin-users-permissions/config/layout.js
Labels: pr: 💅 Enhancement, source: Plugin

#2435 Check dependencies vulnerability with Snyk
  .snyk
  .travis.yml
  package.json
  packages/strapi-admin/.snyk
  packages/strapi-generate-admin/.snyk
  packages/strapi-generate-api/.snyk
  packages/strapi-generate-controller/.snyk
  packages/strapi-generate-model/.snyk
  packages/strapi-generate-new/.snyk
  packages/strapi-generate-plugin/.snyk
  packages/strapi-generate-policy/.snyk
  packages/strapi-generate-service/.snyk
  packages/strapi-generate/.snyk
  packages/strapi-helper-plugin/.snyk
  packages/strapi-hook-bookshelf/.snyk
  packages/strapi-hook-ejs/.snyk
  packages/strapi-hook-knex/.snyk
  packages/strapi-hook-mongoose/.snyk
  packages/strapi-hook-redis/.snyk
  packages/strapi-lint/.snyk
  packages/strapi-lint/lib/internals/shared/listChangedFiles.js
  packages/strapi-middleware-views/.snyk
  packages/strapi-plugin-content-manager/.snyk
  packages/strapi-plugin-content-type-builder/.snyk
  packages/strapi-plugin-email/.snyk
  packages/strapi-plugin-graphql/.snyk
  packages/strapi-plugin-settings-manager/.snyk
  packages/strapi-plugin-upload/.snyk
  packages/strapi-plugin-users-permissions/.snyk
  packages/strapi-provider-email-amazon-ses/.snyk
  packages/strapi-provider-email-mailgun/.snyk
  packages/strapi-provider-email-sendgrid/.snyk
  packages/strapi-provider-email-sendmail/.snyk
  packages/strapi-provider-upload-aws-s3/.snyk
  packages/strapi-provider-upload-cloudinary/.snyk
  packages/strapi-provider-upload-local/.snyk
  packages/strapi-provider-upload-rackspace/.snyk
  packages/strapi-utils/.snyk
  packages/strapi/.snyk
  scripts/snyk.js
Labels: pr: 💅 Enhancement, source: Framework

#2370 Allow customization for mongoose connection (ej. load some mongoose plugins)
  docs/3.x.x/configurations/configurations.md
  packages/strapi-hook-bookshelf/lib/index.js
  packages/strapi-hook-mongoose/lib/index.js
Labels: flag: 💥 Breaking change, pr: 💅 Enhancement, source: Framework

#2487 Add migration guide in documentation
  docs/.vuepress/config.js
  docs/3.x.x/migration-guide/README.md
  docs/3.x.x/migration-guide/migration-guide-1-to-3.md
  docs/3.x.x/migration-guide/migration-guide-alpha.10-to-alpha.11.md
  docs/3.x.x/migration-guide/migration-guide-alpha.11-to-alpha.12.md
  docs/3.x.x/migration-guide/migration-guide-alpha.12.1-to-alpha.12.2.md
  docs/3.x.x/migration-guide/migration-guide-alpha.12.2-to-alpha.12.3.md
  docs/3.x.x/migration-guide/migration-guide-alpha.12.3-to-alpha.12.4.md
  docs/3.x.x/migration-guide/migration-guide-alpha.12.4-to-alpha.12.5.md
  docs/3.x.x/migration-guide/migration-guide-alpha.12.5-to-alpha.12.6.md
  docs/3.x.x/migration-guide/migration-guide-alpha.12.6-to-alpha.12.7.md
  docs/3.x.x/migration-guide/migration-guide-alpha.12.7-to-alpha.13.md
  docs/3.x.x/migration-guide/migration-guide-alpha.13-to-alpha.13.1.md
  docs/3.x.x/migration-guide/migration-guide-alpha.13.1-to-alpha.14.md
  docs/3.x.x/migration-guide/migration-guide-alpha.14-to-alpha.14.1.md
  docs/3.x.x/migration-guide/migration-guide-alpha.14.1-to-alpha.14.2.md
  docs/3.x.x/migration-guide/migration-guide-alpha.14.2-to-alpha.14.3.md
  docs/3.x.x/migration-guide/migration-guide-alpha.14.3-to-alpha.14.4.md
  docs/3.x.x/migration-guide/migration-guide-alpha.14.4-to-alpha.14.5.md
  docs/3.x.x/migration-guide/migration-guide-alpha.14.5-to-alpha.15.md
  docs/3.x.x/migration-guide/migration-guide-alpha.15-to-alpha.16.md
  docs/3.x.x/migration-guide/migration-guide-alpha.7.4-to-alpha.8.md
  docs/3.x.x/migration-guide/migration-guide-alpha.8-to-alpha.9.md
  docs/3.x.x/migration-guide/migration-guide-alpha.9-to-alpha.10.md
Labels: pr: 💅 Enhancement, source: Documentation

#2486 Force snyk auth
  .travis.yml
Labels: pr: 🐛 Bug fix, source: Framework

#2493 Remove snyk from Travis
  .travis.yml
Labels: pr: 🐛 Bug fix, source: Framework

#2508 Add a place for users to link their project in Issue Template
  .github/ISSUE_TEMPLATE/BUG_REPORT.md
Labels: pr: 💅 Enhancement, source: Documentation

#2501 Update readme middleware views
  packages/strapi-middleware-views/README.md
Labels: pr: 💅 Enhancement, source: Documentation

#2489 Plugin Quick Start does not work as expected
  docs/3.x.x/plugin-development/quick-start.md
Labels: pr: 💅 Enhancement, source: Documentation

#2485 Add support for Apollo server tracing in GraphQL
  docs/3.x.x/guides/graphql.md
  packages/strapi-plugin-graphql/config/settings.json
  packages/strapi-plugin-graphql/hooks/graphql/index.js
Labels: pr: 🚀 New feature, source: Plugin

#2528 Fix spelling mistake
  docs/3.x.x/guides/filters.md
Labels: pr: 💅 Enhancement, source: Documentation

#2529 Fix anchor in link from i18n guide to concepts
  docs/3.x.x/guides/i18n.md
Labels: pr: 💅 Enhancement, source: Documentation

#2465 Fix so you can choose multiple domains for the cors
  packages/strapi/lib/middlewares/cors/index.js
Labels: pr: 🐛 Bug fix, source: Framework

#2542 Update middleware documentation enable
  docs/3.x.x/advanced/middlewares.md
Labels: pr: 💅 Enhancement, source: Documentation

#2544 Fix a typo in concepts documentation
  docs/3.x.x/concepts/concepts.md
Labels: pr: 💅 Enhancement, source: Documentation
