Repository strapi/strapi, pull requests merged in 2019-12, with the labels that each got.

#4636 Validate plugin name
  packages/strapi-admin/controllers/Admin.js
Labels: pr: 🐛 Bug fix, source: Admin

#4405 Remove old admin panel warning
  CONTRIBUTING.md
Labels: pr: 💅 Enhancement, source: Documentation

#4652 Update Swagger-UI for Documentation plugin
  packages/strapi-plugin-documentation/package.json
Labels: pr: 🐛 Bug fix, source: Plugin

#4638 Fix no response when get user permission role with internal network
  packages/strapi-plugin-users-permissions/services/UsersPermissions.js
Labels: pr: 🐛 Bug fix, source: Plugin

#4651 Update KO translation
  packages/strapi-admin/admin/src/translations/ko.json
  packages/strapi-plugin-content-manager/admin/src/translations/ko.json
  packages/strapi-plugin-content-type-builder/admin/src/translations/ko.json
  packages/strapi-plugin-upload/admin/src/translations/ko.json
  packages/strapi-plugin-users-permissions/admin/src/translations/ko.json
Labels: pr: 💅 Enhancement, source: Admin

#4660 Updated ApolloServer configuration for introspection queries (GraphQL Plugin)
  packages/strapi-plugin-graphql/hooks/graphql/index.js
Labels: pr: 🐛 Bug fix, source: Plugin

#4667 Add strapi console command
  docs/3.0.0-beta.x/cli/CLI.md
Labels: pr: 💅 Enhancement, source: Documentation

#4657 Added missed comma in ecosystem.config.js example
  docs/3.0.0-beta.x/guides/deployment.md
Labels: pr: 💅 Enhancement, source: Documentation

#4674 Wrap tsvector attributes with coalesce before join
  packages/strapi-hook-bookshelf/lib/queries.js
Labels: pr: 💅 Enhancement, source: Framework

#4540 Populate only role relation to authorize user
  packages/strapi-plugin-users-permissions/config/policies/permissions.js
Labels: flag: 💥 Breaking change, pr: 💅 Enhancement, source: Plugin

#4671 Add guide to create a draft system
  docs/.vuepress/config.js
  docs/3.0.0-beta.x/guides/draft.md
Labels: pr: 💅 Enhancement, source: Documentation

#4659 Update upload.md
  docs/3.0.0-beta.x/plugins/upload.md
Labels: pr: 💅 Enhancement, source: Documentation

#4656 Update model.template
  packages/strapi-generate-model/templates/mongoose/model.template
Labels: pr: 💅 Enhancement, source: Framework

#4654 Change "Mac O/S" to "macOS"
  README.md
Labels: pr: 💅 Enhancement, source: Documentation

#4645 Use the id of entry to update relations
  packages/strapi-hook-bookshelf/lib/queries.js
Labels: pr: 🐛 Bug fix, source: Framework

#4440 Fix empty date wrong display
  packages/strapi-plugin-content-manager/admin/src/components/CustomTable/Row.js
Labels: pr: 🐛 Bug fix, source: Admin

#4351 Fix uploaded file order by size
  packages/strapi-plugin-upload/documentation/1.0.0/overrides/upload-File.json
  packages/strapi-plugin-upload/models/File.settings.json
  packages/strapi-plugin-upload/test/upload.test.e2e.js
Labels: flag: 💥 Breaking change, pr: 🐛 Bug fix, source: Plugin

#4623 Remove search engine for index.html page
  packages/strapi-generate-new/lib/resources/files/public/index.html
  packages/strapi-generate-new/lib/resources/files/public/production.html
Labels: pr: 💅 Enhancement, source: Framework

#4668 Add sqreen guide
  docs/.vuepress/config.js
  docs/3.0.0-beta.x/guides/secure-your-app.md
Labels: pr: 💅 Enhancement, source: Documentation

#4682 Alphabetize concepts/file-structure.md docs
  docs/3.0.0-beta.x/concepts/file-structure.md
Labels: pr: 💅 Enhancement, source: Documentation

#4687 Fix typo draft guide
  docs/3.0.0-beta.x/guides/draft.md
Labels: pr: 💅 Enhancement, source: Documentation

#4688 Update documentation with dynamic zone feature
  docs/3.0.0-beta.x/concepts/queries.md
  docs/3.0.0-beta.x/content-api/api-endpoints.md
  docs/3.0.0-beta.x/plugins/upload.md
Labels: pr: 💅 Enhancement, source: Documentation

#4696 Fix environment typo
  packages/strapi/lib/commands/build.js
Labels: pr: 🐛 Bug fix, source: Framework

#4694 Change admin UI's default language to English if browser's preferred language is not found
  packages/strapi-admin/admin/src/containers/LanguageProvider/reducer.js
Labels: pr: 💅 Enhancement, source: Admin

#4733 Update configurations.md
  docs/3.0.0-beta.x/concepts/configurations.md
Labels: pr: 💅 Enhancement, source: Documentation

#4703 Guide API token
  docs/.vuepress/config.js
  docs/3.0.0-beta.x/guides/api-token.md
Labels: pr: 💅 Enhancement, source: Documentation

#4741 Update migration-guide-beta.17-to-beta.18.md
  docs/3.0.0-beta.x/migration-guide/migration-guide-beta.17-to-beta.18.md
Labels: pr: 🐛 Bug fix, source: Documentation

#4742 Add database migration guides for components
  docs/3.0.0-beta.x/migration-guide/migration-guide-beta.17-to-beta.18.md
Labels: pr: 💅 Enhancement, source: Documentation

#4744 Fix db test on strapi new
  packages/strapi-generate-new/lib/create-customized-project.js
Labels: pr: 🐛 Bug fix, source: Framework

#4753 Fixes #4752
  packages/strapi-admin/admin/src/translations/en.json
  packages/strapi-helper-plugin/lib/src/utils/translatedErrors.js
  packages/strapi-plugin-content-manager/admin/src/components/Inputs/index.js
  packages/strapi-plugin-content-manager/admin/src/containers/EditViewDataManagerProvider/index.js
  packages/strapi-plugin-content-manager/admin/src/containers/EditViewDataManagerProvider/utils/schema.js
  packages/strapi-plugin-content-type-builder/admin/src/components/CustomCheckbox/index.js
  packages/strapi-plugin-content-type-builder/admin/src/containers/FormModal/index.js
  packages/strapi-plugin-content-type-builder/admin/src/containers/FormModal/utils/forms.js
Labels: pr: 🐛 Bug fix, source: Admin

#4764 Allow - in component category name regex
  packages/strapi-plugin-content-type-builder/admin/src/containers/FormModal/utils/attributesRegexes.js
  packages/strapi-plugin-content-type-builder/admin/src/containers/FormModal/utils/forms.js
  packages/strapi-plugin-content-type-builder/controllers/validation/common.js
  packages/strapi-plugin-content-type-builder/controllers/validation/component-category.js
  packages/strapi-plugin-content-type-builder/controllers/validation/component.js
Labels: pr: 🐛 Bug fix, source: Plugin

#4750 Add search behavior in content type builder component picker
  examples/getstarted/api/address/models/Address.settings.json
  packages/strapi-admin/admin/src/components/Logout/index.js
  packages/strapi-admin/admin/src/containers/App/index.js
  packages/strapi-plugin-content-manager/admin/src/components/DraggedFieldWithPreview/DynamicComponent.js
  packages/strapi-plugin-content-manager/admin/src/components/DraggedFieldWithPreview/index.js
  packages/strapi-plugin-content-type-builder/admin/src/components/ComponentSelect/MultipleMenuList.js
  packages/strapi-plugin-content-type-builder/admin/src/containers/DataManagerProvider/reducer.js
  packages/strapi-plugin-content-type-builder/admin/src/containers/FormModal/index.js
  packages/strapi-plugin-content-type-builder/admin/src/translations/en.json
Labels: pr: 💅 Enhancement, source: Plugin

#4757 Fix content type builder logo
  packages/strapi-plugin-content-type-builder/admin/src/assets/images/logo.svg
Labels: pr: 🐛 Bug fix, source: Admin

#4768 Fix multiple issues in beta.18
  packages/strapi-connector-mongoose/lib/mount-models.js
  packages/strapi-plugin-documentation/services/utils/parametersOptions.json
Labels: pr: 🐛 Bug fix, source: Plugin

#4771 Fix edit component with min value when not required
  packages/strapi-plugin-content-manager/admin/src/components/RepeatableComponent/index.js
  packages/strapi-plugin-content-manager/admin/src/containers/EditViewDataManagerProvider/index.js
  packages/strapi-plugin-content-manager/admin/src/containers/EditViewDataManagerProvider/utils/schema.js
Labels: pr: 🐛 Bug fix, source: Admin

#4778 [DOC] Updated 'Migration guide from beta.17.4 through beta.17.8 to be…
  docs/3.0.0-beta.x/migration-guide/migration-guide-beta.17-to-beta.18.md
Labels: pr: 💅 Enhancement, source: Documentation

#4754 Add guide to init a third party client
  docs/.vuepress/config.js
  docs/3.0.0-beta.x/guides/client.md
Labels: pr: 💅 Enhancement, source: Documentation

#4759 Add guide to send email programmatically
  docs/.vuepress/config.js
  docs/3.0.0-beta.x/guides/send-email.md
Labels: pr: 💅 Enhancement, source: Documentation

#4782 Fix documentation generation when route has no config
  packages/strapi-plugin-documentation/services/Documentation.js
Labels: pr: 🐛 Bug fix, source: Plugin

#4770 [CTB] Small improvements
  packages/strapi-plugin-content-type-builder/admin/src/components/ComponentSelect/MultipleMenuList.js
  packages/strapi-plugin-content-type-builder/admin/src/components/ComponentSelect/utils/HasSomeSubArray.js
  packages/strapi-plugin-content-type-builder/admin/src/containers/FormModal/reducer.js
Labels: pr: 💅 Enhancement, source: Admin

#4800 Fix typo in install command
  packages/strapi-generate-new/lib/create-customized-project.js
Labels: pr: 🐛 Bug fix, source: Framework

#4796 Fix typo in documentation of Many-to-Many relationship in model.md
  docs/3.0.0-beta.x/concepts/models.md
Labels: pr: 💅 Enhancement, source: Documentation

#4793 Update databases.md
  docs/3.0.0-beta.x/guides/databases.md
Labels: pr: 💅 Enhancement, source: Documentation

#4784 [CTB] Add search for component's icon
  packages/strapi-plugin-content-type-builder/admin/src/components/ComponentIconPicker/Search.js
  packages/strapi-plugin-content-type-builder/admin/src/components/ComponentIconPicker/SearchWrapper.js
  packages/strapi-plugin-content-type-builder/admin/src/components/ComponentIconPicker/Wrapper.js
  packages/strapi-plugin-content-type-builder/admin/src/components/ComponentIconPicker/index.js
Labels: pr: 💅 Enhancement, source: Plugin

#4774 Add populate option to the fetch user service
  packages/strapi-plugin-users-permissions/services/User.js
Labels: pr: 💅 Enhancement, source: Plugin

#4663 Adding VK auth provider
  packages/strapi-plugin-users-permissions/admin/src/components/PopUpForm/index.js
  packages/strapi-plugin-users-permissions/admin/src/translations/en.json
  packages/strapi-plugin-users-permissions/admin/src/translations/ru.json
  packages/strapi-plugin-users-permissions/config/functions/bootstrap.js
  packages/strapi-plugin-users-permissions/services/Providers.js
Labels: pr: 🚀 New feature, source: Plugin

#4804 Fix/relation from plugin
  packages/strapi-plugin-content-type-builder/services/schema-builder/content-type-builder.js
Labels: pr: 🐛 Bug fix, source: Plugin

#4802 Add morph rel on populate compo relation
  packages/strapi-connector-bookshelf/lib/populate.js
Labels: pr: 💅 Enhancement, source: Framework

#4811 logs(strapi-utills/parse-multipart.js): typo fix
  packages/strapi-utils/lib/parse-multipart.js
Labels: pr: 💅 Enhancement, source: Framework

#4788 Add private option in CTB field options
  packages/strapi-plugin-content-type-builder/admin/src/containers/FormModal/utils/forms.js
  packages/strapi-plugin-content-type-builder/admin/src/containers/FormModal/utils/staticFields.js
  packages/strapi-plugin-content-type-builder/admin/src/translations/en.json
Labels: pr: 💅 Enhancement, source: Plugin

#4817 Add guide to request as authenticated user
  docs/.vuepress/config.js
  docs/3.0.0-beta.x/guides/auth-request.md
Labels: pr: 💅 Enhancement, source: Documentation

#4816 Add email trouble shooting
  docs/3.0.0-beta.x/plugins/email.md
Labels: pr: 💅 Enhancement, source: Documentation

#4824 Beta.18.x migration guide add mongoose tabs
  docs/3.0.0-beta.x/migration-guide/migration-guide-beta.17-to-beta.18.md
Labels: pr: 💅 Enhancement, source: Documentation

#4862 Fix scroll content type fields
  packages/strapi-plugin-content-manager/admin/src/containers/ListSettingsView/DragWrapper.js
Labels: pr: 🐛 Bug fix, source: Plugin
