Repository strapi/strapi, pull requests merged in 2019-07, with the labels that each got.

#3519 Fix lodash depedency for email providers
  packages/strapi-generate-new/json/package.json.js
  packages/strapi-provider-email-amazon-ses/package.json
  packages/strapi-provider-email-mailgun/package.json
  packages/strapi-provider-email-sendgrid/package.json
  packages/strapi-provider-email-sendmail/package.json
  packages/strapi-provider-upload-aws-s3/package.json
Labels: pr: 🐛 Bug fix, source: Plugin

#3181 Use algolia docsearch in documentation search
  docs/.vuepress/config.js
  docs/.vuepress/theme/AlgoliaSearchBox.vue
  docs/.vuepress/theme/Navbar.vue
Labels: pr: 💅 Enhancement, source: Documentation

#3061 Enable sendgrid's transactional template
  packages/strapi-provider-email-sendgrid/lib/index.js
Labels: pr: 💅 Enhancement, source: Plugin

#3356 Fix removal of double quotes in string/text fields
  packages/strapi-plugin-content-manager/services/ContentManager.js
Labels: pr: 🐛 Bug fix, source: Plugin

#3475 Update AWS and Digital Ocean depoyment documentation
  docs/3.0.0-alpha.x/assets/quick-start-detailed/AdminUserInUsers.png
  docs/3.0.0-alpha.x/getting-started/quick-start-tutorial.md
  docs/3.0.0-alpha.x/guides/deployment.md
  docs/3.0.0-beta.x/assets/quick-start-detailed/AddContentTypeMenuItem.png
  docs/3.0.0-beta.x/assets/quick-start-detailed/AddStrapiRestaurant.png
  docs/3.0.0-beta.x/assets/quick-start-detailed/AddTextFieldRestaurant.png
  docs/3.0.0-beta.x/assets/quick-start-detailed/AdminUserInUsers.png
  docs/3.0.0-beta.x/assets/quick-start-detailed/AfterRegistrationScreenAdminPanel.png
  docs/3.0.0-beta.x/assets/quick-start-detailed/CreateContentTypeScreen.png
  docs/3.0.0-beta.x/assets/quick-start-detailed/RestaurantNameAndDescription.png
  docs/3.0.0-beta.x/assets/quick-start-detailed/Screenshot 2019-06-14 at 17.50.09.png
  docs/3.0.0-beta.x/assets/quick-start-detailed/addContemporaryCategoryToRestaurant.png
  docs/3.0.0-beta.x/assets/quick-start-detailed/addItalianCategoryToRestaurant.png
  docs/3.0.0-beta.x/assets/quick-start-detailed/addNewRelationScreen.png
  docs/3.0.0-beta.x/assets/quick-start-detailed/addTheRestaurantData.png
  docs/3.0.0-beta.x/assets/quick-start-detailed/categoriesListed.png
  docs/3.0.0-beta.x/assets/quick-start-detailed/categoryAddStringField.png
  docs/3.0.0-beta.x/assets/quick-start-detailed/categoryChangePermissionToRestaurant.png
  docs/3.0.0-beta.x/assets/quick-start-detailed/categoryContentTypeScreen.png
  docs/3.0.0-beta.x/assets/quick-start-detailed/categoryHasManyToMany.png
  docs/3.0.0-beta.x/assets/quick-start-detailed/categoryNameAndDescription.png
  docs/3.0.0-beta.x/assets/quick-start-detailed/categoryStringAdvancedSettings.png
  docs/3.0.0-beta.x/assets/quick-start-detailed/categoryStringNameField.png
  docs/3.0.0-beta.x/assets/quick-start-detailed/clickRelationFieldCategory.png
  docs/3.0.0-beta.x/assets/quick-start-detailed/forbiddenAccessToRestaurant.png
  docs/3.0.0-beta.x/assets/quick-start-detailed/listedItalianCategory.png
  docs/3.0.0-beta.x/assets/quick-start-detailed/listedRestaurant.png
  docs/3.0.0-beta.x/assets/quick-start-detailed/nowSaveCategory.png
  docs/3.0.0-beta.x/assets/quick-start-detailed/restaurantAddFields.png
  docs/3.0.0-beta.x/assets/quick-start-detailed/restaurantAddNewField.png
  docs/3.0.0-beta.x/assets/quick-start-detailed/restaurantAdvancedSettingsStringField.png
  docs/3.0.0-beta.x/assets/quick-start-detailed/restaurantTextFieldAdvancedSettings.png
  docs/3.0.0-beta.x/assets/quick-start-detailed/restaurantTextFieldBaseSettings.png
  docs/3.0.0-beta.x/assets/quick-start-detailed/rolesAndPermissions.png
  docs/3.0.0-beta.x/assets/quick-start-detailed/rolesFindAndRoute.png
  docs/3.0.0-beta.x/assets/quick-start-detailed/saveRestaurantContentType.png
  docs/3.0.0-beta.x/assets/quick-start-detailed/saveRestaurantNameField.png
  docs/3.0.0-beta.x/assets/quick-start-detailed/selectCategoryFromRestaurant.png
  docs/3.0.0-beta.x/assets/quick-start-detailed/strapi-welcome-screen.png
  docs/3.0.0-beta.x/assets/quick-start-detailed/strapiWelcomePage.png
  docs/3.0.0-beta.x/assets/quick-start-detailed/successApiCall.png
  docs/3.0.0-beta.x/assets/quick-start-detailed/waitForRestart.png
  docs/3.0.0-beta.x/assets/quick-start-detailed/welcome-screen-entered-information.png
  docs/3.0.0-beta.x/getting-started/install-requirements.md
  docs/3.0.0-beta.x/getting-started/quick-start-tutorial.md
  docs/3.0.0-beta.x/getting-started/quick-start.md
  docs/3.0.0-beta.x/guides/deployment.md
Labels: pr: 💅 Enhancement, type: documentation 📖

#3454 Update getting started documentation with beta specific content
  docs/3.0.0-alpha.x/getting-started/install-requirements.md
  docs/3.0.0-alpha.x/getting-started/quick-start.md
  docs/3.0.0-beta.x/getting-started/install-requirements.md
  docs/3.0.0-beta.x/getting-started/quick-start.md
Labels: pr: 💅 Enhancement, source: Documentation

#3555 Fix front-end files lint
  .eslintrc.js
  packages/strapi-admin/admin/src/components/LeftMenuFooter/index.js
  packages/strapi-admin/admin/src/components/LeftMenuLink/index.js
  packages/strapi-admin/admin/src/components/Logout/index.js
  packages/strapi-admin/admin/src/components/PluginCard/index.js
  packages/strapi-admin/admin/src/components/Row/index.js
  packages/strapi-admin/admin/src/components/Sub/index.js
  packages/strapi-admin/admin/src/components/SupportUsCta/index.js
  packages/strapi-admin/admin/src/containers/Admin/saga.js
  packages/strapi-admin/admin/src/containers/Admin/tests/saga.test.js
  packages/strapi-admin/admin/src/containers/HomePage/BlockLink.js
  packages/strapi-admin/admin/src/containers/HomePage/CreateContent.js
  packages/strapi-admin/admin/src/containers/HomePage/SocialLink.js
  packages/strapi-admin/admin/src/containers/HomePage/WelcomeContent.js
  packages/strapi-admin/admin/src/containers/HomePage/index.js
  packages/strapi-admin/admin/src/containers/HomePage/saga.js
  packages/strapi-admin/admin/src/containers/Marketplace/saga.js
  packages/strapi-admin/admin/src/containers/Onboarding/saga.js
  packages/strapi-admin/admin/src/public-path.js
  packages/strapi-generate-plugin/files/admin/src/containers/ExamplePage/saga.js
  packages/strapi-helper-plugin/lib/src/components/BlockerComponent/index.js
  packages/strapi-helper-plugin/lib/src/components/InputFileDetails/index.js
  packages/strapi-helper-plugin/lib/src/components/OverlayBlocker/index.js
  packages/strapi-plugin-content-manager/admin/src/components/SelectMany/index.js
  packages/strapi-plugin-content-manager/admin/src/components/TableDelete/index.js
  packages/strapi-plugin-content-manager/admin/src/containers/EditPage/saga.js
  packages/strapi-plugin-content-manager/admin/src/containers/SettingsPage/index.js
  packages/strapi-plugin-content-manager/admin/src/lifecycles/didGetSecuredData.js
  packages/strapi-plugin-content-type-builder/admin/src/components/Block/tests/index.test.js
  packages/strapi-plugin-content-type-builder/admin/src/components/Flex/tests/index.test.js
  packages/strapi-plugin-content-type-builder/admin/src/components/LeftMenu/tests/index.test.js
  packages/strapi-plugin-content-type-builder/admin/src/components/LeftMenuSection/tests/index.test.js
  packages/strapi-plugin-content-type-builder/admin/src/components/ListTitle/tests/index.test.js
  packages/strapi-plugin-content-type-builder/admin/src/components/Ul/tests/index.test.js
  packages/strapi-plugin-content-type-builder/admin/src/containers/App/saga.js
  packages/strapi-plugin-content-type-builder/admin/src/containers/App/tests/saga.test.js
  packages/strapi-plugin-content-type-builder/admin/src/containers/ModelForm/index.js
  packages/strapi-plugin-content-type-builder/admin/src/containers/ModelPage/DocumentationSection.js
  packages/strapi-plugin-content-type-builder/admin/src/containers/RelationForm/NaturePicker.js
  packages/strapi-plugin-content-type-builder/admin/src/containers/RelationForm/tests/InlineBlock.test.js
  packages/strapi-plugin-documentation/admin/src/containers/HomePage/saga.js
  packages/strapi-plugin-settings-manager/admin/src/components/WithFormSection/index.js
  packages/strapi-plugin-settings-manager/admin/src/components/WithInput/index.js
  packages/strapi-plugin-settings-manager/admin/src/containers/App/index.js
  packages/strapi-plugin-settings-manager/admin/src/containers/App/sagas.js
  packages/strapi-plugin-settings-manager/admin/src/containers/HomePage/index.js
  packages/strapi-plugin-upload/admin/src/components/Li/index.js
  packages/strapi-plugin-users-permissions/admin/src/components/Controller/index.js
  packages/strapi-plugin-users-permissions/admin/src/components/InputSearchLi/index.js
  packages/strapi-plugin-users-permissions/admin/src/components/PopUpForm/index.js
  packages/strapi-plugin-users-permissions/admin/src/containers/Initializer/tests/saga.test.js
Labels: pr: 💅 Enhancement, source: Admin

#3425 Add Github discussion template
  .github/ISSUE_TEMPLATE/DISCUSSION.md
Labels: pr: 💅 Enhancement, source: Documentation

#3561 Fix doc header's link blog & slack
  docs/.vuepress/config.js
Labels: pr: 💅 Enhancement, source: Documentation

#3564 Fix deployment typo fix
  docs/3.0.0-beta.x/guides/deployment.md
Labels: pr: 💅 Enhancement, source: Documentation

#3532 Trimmed whitespace for AWS S3 credentials
  packages/strapi-provider-upload-aws-s3/lib/index.js
Labels: pr: 💅 Enhancement, source: Plugin

#3562 Add null and not null filters
  docs/3.0.0-beta.x/guides/filters.md
  docs/3.0.0-beta.x/guides/graphql.md
  docs/3.0.0-beta.x/guides/restapi.md
  packages/strapi-hook-bookshelf/lib/buildQuery.js
  packages/strapi-hook-mongoose/lib/buildQuery.js
  packages/strapi-plugin-graphql/test/graphqlCrud.test.e2e.js
  packages/strapi-utils/lib/__tests__/convertRestQueryParams.test.js
  packages/strapi-utils/lib/buildQuery.js
  packages/strapi-utils/lib/convertRestQueryParams.js
  packages/strapi/__tests__/filtering.test.e2e.js
Labels: pr: 💅 Enhancement, source: Framework

#3575 Fix hook.json file name
  docs/3.0.0-alpha.x/advanced/hooks.md
  docs/3.0.0-beta.x/advanced/hooks.md
  packages/strapi-hook-ejs/README.md
Labels: pr: 💅 Enhancement, source: Documentation

#3574 Update all packages Slack badge
  docs/1.x.x/README.md
  docs/3.0.0-alpha.x/README.md
  docs/3.0.0-beta.x/README.md
  packages/strapi-generate-api/README.md
  packages/strapi-generate-controller/README.md
  packages/strapi-generate-model/README.md
  packages/strapi-generate-new/README.md
  packages/strapi-generate-plugin/README.md
  packages/strapi-generate-policy/README.md
  packages/strapi-generate-service/README.md
  packages/strapi-generate/README.md
  packages/strapi-hook-bookshelf/README.md
  packages/strapi-hook-ejs/README.md
  packages/strapi-hook-knex/README.md
  packages/strapi-hook-mongoose/README.md
  packages/strapi-hook-redis/README.md
  packages/strapi-middleware-views/README.md
  packages/strapi-utils/README.md
  packages/strapi/README.md
Labels: pr: 💅 Enhancement, source: Documentation

#3567 Fix styling on content type builder left menu list
  packages/strapi-plugin-content-type-builder/admin/src/components/LeftMenuSection/styles.scss
Labels: pr: 🐛 Bug fix, source: Admin

#3585 Support many way relation
  examples/getstarted/api/articles/models/Articles.settings.json
  examples/getstarted/api/post/models/Post.settings.json
  examples/getstarted/api/tag/models/Tag.settings.json
  packages/strapi-hook-bookshelf/lib/buildDatabaseSchema.js
  packages/strapi-hook-bookshelf/lib/mount-models.js
  packages/strapi-hook-bookshelf/lib/relations.js
  packages/strapi-hook-bookshelf/lib/utils/graphql.js
  packages/strapi-hook-bookshelf/lib/utils/index.js
  packages/strapi-hook-mongoose/lib/mount-models.js
  packages/strapi-hook-mongoose/lib/relations.js
  packages/strapi-plugin-content-manager/test/index.test.e2e.js
  packages/strapi-plugin-content-type-builder/controllers/ContentTypeBuilder.js
  packages/strapi-plugin-content-type-builder/services/ContentTypeBuilder.js
  packages/strapi-plugin-content-type-builder/test/groups.test.e2e.js
  packages/strapi-plugin-graphql/services/Loaders.js
  packages/strapi-plugin-graphql/services/Resolvers.js
  packages/strapi-utils/lib/models.js
  test/helpers/generators.js
Labels: pr: 💅 Enhancement, source: Plugin

#3589 Fix content manager json parsing strategy
  examples/getstarted/api/articles/models/Articles.settings.json
  examples/getstarted/config/environments/development/database.js
  examples/getstarted/exports/graphql/schema.graphql
  examples/getstarted/package.json
  packages/strapi-plugin-content-manager/services/ContentManager.js
  yarn.lock
Labels: pr: 🐛 Bug fix, source: Plugin

#3587 Update ESLint dependencies in created applications
  package.json
  packages/strapi-generate-new/lib/resources/files/.eslintignore
  packages/strapi-generate-new/lib/resources/files/.eslintrc
  packages/strapi-generate-new/lib/resources/json/package.json.js
  yarn.lock
Labels: pr: 💅 Enhancement, source: Framework

#3544 Admin sidebar scrolling support for firefox
  packages/strapi-admin/admin/src/components/LeftMenuLinkContainer/styles.scss
Labels: pr: 🐛 Bug fix, source: Admin

#3594 Allow node 12 now that it is supported
  README.md
  examples/getstarted/package.json
  package.json
  packages/create-strapi-app/index.js
  packages/strapi-admin/package.json
  packages/strapi-generate-api/package.json
  packages/strapi-generate-controller/package.json
  packages/strapi-generate-model/package.json
  packages/strapi-generate-new/lib/resources/json/package.json.js
  packages/strapi-generate-new/package.json
  packages/strapi-generate-plugin/json/package.json.js
  packages/strapi-generate-plugin/package.json
  packages/strapi-generate-policy/package.json
  packages/strapi-generate-service/package.json
  packages/strapi-generate/package.json
  packages/strapi-helper-plugin/package.json
  packages/strapi-hook-bookshelf/package.json
  packages/strapi-hook-ejs/package.json
  packages/strapi-hook-knex/package.json
  packages/strapi-hook-mongoose/package.json
  packages/strapi-hook-redis/package.json
  packages/strapi-middleware-views/package.json
  packages/strapi-plugin-content-manager/package.json
  packages/strapi-plugin-content-type-builder/package.json
  packages/strapi-plugin-email/package.json
  packages/strapi-plugin-graphql/package.json
  packages/strapi-plugin-settings-manager/package.json
  packages/strapi-plugin-upload/package.json
  packages/strapi-plugin-users-permissions/package.json
  packages/strapi-provider-email-amazon-ses/package.json
  packages/strapi-provider-email-mailgun/package.json
  packages/strapi-provider-email-sendgrid/package.json
  packages/strapi-provider-email-sendmail/package.json
  packages/strapi-provider-upload-aws-s3/package.json
  packages/strapi-provider-upload-cloudinary/package.json
  packages/strapi-provider-upload-local/package.json
  packages/strapi-utils/package.json
  packages/strapi/package.json
Labels: pr: 💅 Enhancement, source: Framework

#3597 Update koa2-ratelimit to latest version
  packages/strapi-plugin-users-permissions/package.json
Labels: pr: 💅 Enhancement, source: Plugin

#3568 CTB - GroupPage - List group attributes and delete attribute
  packages/strapi-helper-plugin/lib/src/assets/styles/colors.js
  packages/strapi-helper-plugin/lib/src/components/HeaderNav/styles.scss
  packages/strapi-helper-plugin/lib/src/components/List/index.js
  packages/strapi-helper-plugin/lib/src/components/ListHeader/Wrapper.js
  packages/strapi-helper-plugin/lib/src/components/ListHeader/index.js
  packages/strapi-helper-plugin/lib/src/components/ListWrapper/index.js
  packages/strapi-plugin-content-type-builder/admin/src/assets/icons/attributes/icon_boolean.png
  packages/strapi-plugin-content-type-builder/admin/src/assets/icons/attributes/icon_date.png
  packages/strapi-plugin-content-type-builder/admin/src/assets/icons/attributes/icon_email.png
  packages/strapi-plugin-content-type-builder/admin/src/assets/icons/attributes/icon_enumeration.png
  packages/strapi-plugin-content-type-builder/admin/src/assets/icons/attributes/icon_json.png
  packages/strapi-plugin-content-type-builder/admin/src/assets/icons/attributes/icon_media.png
  packages/strapi-plugin-content-type-builder/admin/src/assets/icons/attributes/icon_number.png
  packages/strapi-plugin-content-type-builder/admin/src/assets/icons/attributes/icon_password.png
  packages/strapi-plugin-content-type-builder/admin/src/assets/icons/attributes/icon_relation.png
  packages/strapi-plugin-content-type-builder/admin/src/assets/icons/attributes/icon_string.png
  packages/strapi-plugin-content-type-builder/admin/src/assets/icons/attributes/icon_text.png
  packages/strapi-plugin-content-type-builder/admin/src/components/AttributeLi/assets.js
  packages/strapi-plugin-content-type-builder/admin/src/components/AttributeLi/index.js
  packages/strapi-plugin-content-type-builder/admin/src/components/AttributeLi/styles.scss
  packages/strapi-plugin-content-type-builder/admin/src/components/AttributeLi/tests/index.test.js
  packages/strapi-plugin-content-type-builder/admin/src/components/AttributeOption/index.js
  packages/strapi-plugin-content-type-builder/admin/src/components/ListRow/StyledListRow.js
  packages/strapi-plugin-content-type-builder/admin/src/components/ListRow/index.js
  packages/strapi-plugin-content-type-builder/admin/src/components/ListRow/tests/index.test.js
  packages/strapi-plugin-content-type-builder/admin/src/containers/App/actions.js
  packages/strapi-plugin-content-type-builder/admin/src/containers/App/constants.js
  packages/strapi-plugin-content-type-builder/admin/src/containers/App/reducer.js
  packages/strapi-plugin-content-type-builder/admin/src/containers/GroupPage/index.js
  packages/strapi-plugin-content-type-builder/admin/src/containers/GroupPage/tests/index.test.js
  packages/strapi-plugin-content-type-builder/admin/src/containers/HomePage/Tr.js
  packages/strapi-plugin-content-type-builder/admin/src/containers/HomePage/index.js
  packages/strapi-plugin-content-type-builder/admin/src/containers/HomePage/tests/index.test.js
  packages/strapi-plugin-content-type-builder/admin/src/containers/LeftMenu/StyledLeftMenu.js
  packages/strapi-plugin-content-type-builder/admin/src/containers/ModelPage/index.js
  packages/strapi-plugin-content-type-builder/admin/src/containers/ModelPage/tests/index.test.js
  packages/strapi-plugin-content-type-builder/admin/src/translations/en.json
  packages/strapi-plugin-content-type-builder/admin/src/translations/fr.json
  packages/strapi-plugin-content-type-builder/admin/src/utils/attributeIcons.js
  packages/strapi-plugin-content-type-builder/controllers/Fixtures.js
Labels: pr: 🚀 New feature, source: Plugin

#3572 Improve documentation
  docs/1.x.x/models.md
  docs/1.x.x/request.md
  docs/1.x.x/upload.md
  docs/3.0.0-alpha.x/advanced/customize-admin.md
  docs/3.0.0-alpha.x/advanced/hooks.md
  docs/3.0.0-alpha.x/advanced/usage-information.md
  docs/3.0.0-alpha.x/api-reference/reference.md
  docs/3.0.0-alpha.x/cli/CLI.md
  docs/3.0.0-alpha.x/concepts/concepts.md
  docs/3.0.0-alpha.x/configurations/configurations.md
  docs/3.0.0-alpha.x/guides/api-documentation.md
  docs/3.0.0-alpha.x/guides/authentication.md
  docs/3.0.0-alpha.x/guides/deployment.md
  docs/3.0.0-alpha.x/guides/filters.md
  docs/3.0.0-alpha.x/guides/graphql.md
  docs/3.0.0-alpha.x/guides/models.md
  docs/3.0.0-alpha.x/guides/policies.md
  docs/3.0.0-alpha.x/guides/public-assets.md
  docs/3.0.0-alpha.x/guides/requests.md
  docs/3.0.0-alpha.x/guides/responses.md
  docs/3.0.0-alpha.x/plugin-development/backend-development.md
  docs/3.0.0-alpha.x/plugin-development/frontend-development.md
  docs/3.0.0-alpha.x/plugin-development/utils.md
  docs/3.0.0-beta.x/advanced/customize-admin.md
  docs/3.0.0-beta.x/advanced/hooks.md
  docs/3.0.0-beta.x/advanced/usage-information.md
  docs/3.0.0-beta.x/api-reference/reference.md
  docs/3.0.0-beta.x/cli/CLI.md
  docs/3.0.0-beta.x/concepts/concepts.md
  docs/3.0.0-beta.x/configurations/configurations.md
  docs/3.0.0-beta.x/getting-started/install-requirements.md
  docs/3.0.0-beta.x/getting-started/quick-start-tutorial.md
  docs/3.0.0-beta.x/guides/api-documentation.md
  docs/3.0.0-beta.x/guides/authentication.md
  docs/3.0.0-beta.x/guides/deployment.md
  docs/3.0.0-beta.x/guides/email.md
  docs/3.0.0-beta.x/guides/filters.md
  docs/3.0.0-beta.x/guides/graphql.md
  docs/3.0.0-beta.x/guides/models.md
  docs/3.0.0-beta.x/guides/policies.md
  docs/3.0.0-beta.x/guides/public-assets.md
  docs/3.0.0-beta.x/guides/requests.md
  docs/3.0.0-beta.x/guides/responses.md
  docs/3.0.0-beta.x/migration-guide/migration-guide-alpha.26-to-beta.md
  docs/3.0.0-beta.x/plugin-development/backend-development.md
  packages/strapi-admin/admin/src/containers/Admin/index.js
  packages/strapi-admin/admin/src/containers/ListPluginsPage/saga.js
  packages/strapi-helper-plugin/lib/src/utils/inputsValidations.js
  packages/strapi-hook-bookshelf/lib/index.js
  packages/strapi-hook-mongoose/lib/buildQuery.js
  packages/strapi-hook-mongoose/lib/index.js
  packages/strapi-plugin-content-manager/admin/src/components/Wysiwyg/previewWysiwyg.js
  packages/strapi-plugin-content-type-builder/admin/src/containers/RelationForm/tests/index.test.js
  packages/strapi-plugin-documentation/README.md
  packages/strapi-plugin-documentation/public/index.html
  packages/strapi-plugin-documentation/services/Documentation.js
  packages/strapi-plugin-settings-manager/admin/src/components/InputNumber/index.js
  packages/strapi-plugin-settings-manager/admin/src/components/InputText/index.js
  packages/strapi-plugin-users-permissions/admin/src/translations/fr.json
  packages/strapi-plugin-users-permissions/config/routes.json
Labels: pr: 💅 Enhancement, source: Documentation

#3584 Improve upload documentation wording
  docs/3.0.0-beta.x/guides/upload.md
Labels: pr: 💅 Enhancement, source: Documentation

#3590 Fix strapi-generate-api removing underscores in field name
  packages/strapi-generate-api/lib/before.js
Labels: pr: 🐛 Bug fix, source: Framework

#3605 CRUD Groups in core-api's bookshelf queries
  examples/getstarted/api/articles/models/Articles.settings.json
  examples/getstarted/config/environments/development/database.js
  examples/getstarted/exports/graphql/schema.graphql
  examples/getstarted/groups/cta_facebook.json
  packages/strapi-hook-bookshelf/lib/generate-group-relations.js
  packages/strapi-hook-bookshelf/lib/relations.js
  packages/strapi-hook-mongoose/lib/relations.js
  packages/strapi-plugin-content-type-builder/package.json
  packages/strapi/lib/core-api/queries/bookshelf.js
  yarn.lock
Labels: flag: 💥 Breaking change, pr: 💅 Enhancement, source: Framework

#3607 Force relationnal updates to be done before main model update
  packages/strapi-hook-bookshelf/lib/relations.js
Labels: pr: 🐛 Bug fix, source: Framework

#3610 Fix plugin route object
  docs/3.0.0-beta.x/plugin-development/backend-development.md
Labels: pr: 💅 Enhancement, source: Documentation

#3609 Update customize-admin in beta documentation
  docs/3.0.0-beta.x/advanced/customize-admin.md
Labels: pr: 💅 Enhancement, source: Documentation

#3612 CRUD Group mongoose
  packages/strapi-hook-mongoose/lib/mount-models.js
  packages/strapi/lib/core-api/queries/bookshelf.js
  packages/strapi/lib/core-api/queries/mongoose.js
Labels: pr: 🚀 New feature, source: Framework

#3617 Update engines configuration
  examples/getstarted/package.json
  package.json
  packages/create-strapi-app/package.json
  packages/strapi-admin/package.json
  packages/strapi-generate-api/package.json
  packages/strapi-generate-controller/package.json
  packages/strapi-generate-model/package.json
  packages/strapi-generate-new/lib/resources/json/package.json.js
  packages/strapi-generate-new/package.json
  packages/strapi-generate-plugin/json/package.json.js
  packages/strapi-generate-plugin/package.json
  packages/strapi-generate-policy/package.json
  packages/strapi-generate-service/package.json
  packages/strapi-generate/package.json
  packages/strapi-helper-plugin/package.json
  packages/strapi-hook-bookshelf/package.json
  packages/strapi-hook-ejs/package.json
  packages/strapi-hook-knex/package.json
  packages/strapi-hook-mongoose/package.json
  packages/strapi-hook-redis/package.json
  packages/strapi-middleware-views/package.json
  packages/strapi-plugin-content-manager/package.json
  packages/strapi-plugin-content-type-builder/package.json
  packages/strapi-plugin-documentation/package.json
  packages/strapi-plugin-email/package.json
  packages/strapi-plugin-graphql/package.json
  packages/strapi-plugin-settings-manager/package.json
  packages/strapi-plugin-upload/package.json
  packages/strapi-plugin-users-permissions/package.json
  packages/strapi-provider-email-amazon-ses/package.json
  packages/strapi-provider-email-mailgun/package.json
  packages/strapi-provider-email-sendgrid/package.json
  packages/strapi-provider-email-sendmail/package.json
  packages/strapi-provider-upload-aws-s3/package.json
  packages/strapi-provider-upload-cloudinary/package.json
  packages/strapi-provider-upload-local/package.json
  packages/strapi-utils/package.json
  packages/strapi/package.json
Labels: pr: 💅 Enhancement, source: Framework

#3613 Fix Google auth
  packages/strapi-plugin-users-permissions/services/Providers.js
Labels: pr: 🐛 Bug fix, source: Plugin

#3625 Fix missing connector in generated database.json files
  packages/strapi-generate-new/lib/resources/json/database.json.js
Labels: pr: 🐛 Bug fix, source: Framework

#3659 Fix graphql amountLimit must be used when no limit is provided
  packages/strapi-plugin-graphql/services/Query.js
Labels: pr: 🐛 Bug fix, source: Plugin

#3599 Update koa-ip version
  packages/strapi/package.json
  yarn.lock
Labels: pr: 💅 Enhancement, source: Framework

#3646 Fix graphql me query on sql databases
  packages/strapi-plugin-users-permissions/config/schema.graphql
Labels: pr: 🐛 Bug fix, source: Plugin

#3624 MongoDB Atlas documentation update in database and deployment
  docs/3.0.0-beta.x/guides/databases.md
  docs/3.0.0-beta.x/guides/deployment.md
Labels: pr: 💅 Enhancement, source: Documentation

#3668 New content manager schemas + wysiwyg type
  cypress/fixtures/api/product.json
  packages/strapi-admin/config/layout.js
  packages/strapi-hook-bookshelf/lib/buildDatabaseSchema.js
  packages/strapi-hook-mongoose/lib/utils/index.js
  packages/strapi-plugin-content-manager/config/functions/bootstrap.js
  packages/strapi-plugin-content-manager/config/functions/utils/getters.js
  packages/strapi-plugin-content-manager/config/routes.json
  packages/strapi-plugin-content-manager/controllers/ContentManager.js
  packages/strapi-plugin-content-manager/controllers/ContentManagerFixtures.js
  packages/strapi-plugin-content-manager/controllers/ContentTypes.js
  packages/strapi-plugin-content-manager/controllers/GeneralSettings.js
  packages/strapi-plugin-content-manager/controllers/Groups.js
  packages/strapi-plugin-content-manager/controllers/validation/general-setting.js
  packages/strapi-plugin-content-manager/controllers/validation/index.js
  packages/strapi-plugin-content-manager/controllers/validation/model-configuration.js
  packages/strapi-plugin-content-manager/package.json
  packages/strapi-plugin-content-manager/services/ContentTypes.js
  packages/strapi-plugin-content-manager/services/GeneralSettings.js
  packages/strapi-plugin-content-manager/services/Groups.js
  packages/strapi-plugin-content-manager/services/utils/configuration/__tests__/attributes.test.js
  packages/strapi-plugin-content-manager/services/utils/configuration/attributes.js
  packages/strapi-plugin-content-manager/services/utils/configuration/index.js
  packages/strapi-plugin-content-manager/services/utils/configuration/layouts.js
  packages/strapi-plugin-content-manager/services/utils/configuration/metadatas.js
  packages/strapi-plugin-content-manager/services/utils/configuration/settings.js
  packages/strapi-plugin-content-manager/services/utils/schema.js
  packages/strapi-plugin-content-manager/services/utils/store.js
  packages/strapi-plugin-content-type-builder/controllers/ContentTypeBuilder.js
  packages/strapi-plugin-content-type-builder/services/ContentTypeBuilder.js
  packages/strapi-plugin-content-type-builder/utils/Manager.js
  packages/strapi-plugin-content-type-builder/utils/helpers.js
  packages/strapi-plugin-graphql/test/graphqlCrud.test.e2e.js
  packages/strapi-plugin-graphql/test/graphqlRelations.test.e2e.js
  packages/strapi-plugin-users-permissions/config/layout.js
  packages/strapi/lib/Strapi.js
  packages/strapi/lib/middlewares/logger/index.js
  packages/strapi/lib/services/groups/index.js
  test/helpers/generators.js
Labels: flag: 💥 Breaking change

#3674 Remove i18n example
  docs/3.0.0-alpha.x/assets/internationalization.gif
  docs/3.0.0-alpha.x/guides/i18n.md
  docs/3.0.0-beta.x/assets/internationalization.gif
  docs/3.0.0-beta.x/guides/i18n.md
Labels: pr: 💅 Enhancement, source: Documentation

#3669 Update JA translation
  packages/strapi-admin/admin/src/translations/ja.json
Labels: pr: 💅 Enhancement, source: Admin
