Repository strapi/strapi, pull requests merged in 2019-11, with the labels that each got.

#4421 Use limit=0 to require full data set
  docs/3.0.0-alpha.x/guides/filters.md
Labels: pr: 💅 Enhancement, type: documentation 📖

#4433 Add Email validation on user register
  packages/strapi-plugin-users-permissions/controllers/Auth.js
Labels: pr: 🐛 Bug fix, source: Plugin

#4443 Fix security issue with reset password
  packages/strapi-admin/controllers/Auth.js
  packages/strapi-plugin-users-permissions/controllers/Auth.js
Labels: pr: 🐛 Bug fix, source: Plugin

#4446 Add security and vulnerability reporting page
  .github/ISSUE_TEMPLATE/SECURITY.md
  docs/SECURITY.md
Labels: pr: 💅 Enhancement, source: Documentation

#4447 Move security information to proper location
  SECURITY.md
Labels: pr: 💅 Enhancement, source: Documentation

#4451 Fix typo on security.md
  .github/ISSUE_TEMPLATE/SECURITY.md
  SECURITY.md
Labels: pr: 💅 Enhancement, source: Documentation

#4422 Fix typos in deployment docs
  docs/3.0.0-beta.x/guides/deployment.md
Labels: pr: 💅 Enhancement, source: Documentation

#4454 Serve index.html in a simpler way
  packages/strapi/lib/middlewares/public/index.js
Labels: pr: 💅 Enhancement, source: Framework

#4452 Add Strapi environment to Sentry error
  docs/3.0.0-beta.x/guides/error-catching.md
Labels: pr: 💅 Enhancement, source: Documentation

#4438 Update discussion template to clarify it's use.
  .github/ISSUE_TEMPLATE/DISCUSSION.md
Labels: pr: 💅 Enhancement, source: Documentation

#4242 Fix error handling in OAuth providers + Enhance Github provider
  packages/strapi-plugin-users-permissions/services/Providers.js
Labels: pr: 🐛 Bug fix, source: Plugin

#4458 Do not create manyRelation tables if autoMigration is false.
  packages/strapi-hook-bookshelf/lib/buildDatabaseSchema.js
Labels: pr: 🐛 Bug fix, source: Plugin

#4406 Add uuid attribute translations and uuid icon for content builder
  packages/strapi-plugin-content-type-builder/admin/src/assets/icons/attributes/icon_uuid.png
  packages/strapi-plugin-content-type-builder/admin/src/translations/en.json
  packages/strapi-plugin-content-type-builder/admin/src/utils/attributeIcons.js
Labels: pr: 💅 Enhancement, source: Plugin

#4462 Auto confirmation user with provider other than local
  packages/strapi-plugin-users-permissions/services/Providers.js
Labels: pr: 🐛 Bug fix, source: Plugin

#4441 Support private associations in GraphQL resolvers
  packages/strapi-plugin-graphql/services/Resolvers.js
Labels: pr: 🐛 Bug fix, source: Plugin

#4464 Remove unneeded Webpack plugin
  packages/strapi-admin/package.json
  packages/strapi-admin/webpack.config.dev.js
  yarn.lock
Labels: pr: 💅 Enhancement, source: Admin

#4444 Clean up template and remove keys that would break bookshelf/knex
  packages/strapi-generate-new/lib/resources/json/database.json.js
Labels: pr: 🐛 Bug fix, source: Framework

#4418 New design for the server homepage
  examples/getstarted/public/index.html
  examples/getstarted/public/production.html
  packages/strapi-generate-new/lib/resources/files/public/index.html
  packages/strapi-generate-new/lib/resources/files/public/production.html
  packages/strapi/lib/middlewares/public/index.js
Labels: pr: 💅 Enhancement, source: Admin

#4508 Use plugin in the GraphQL aggregation queries
  packages/strapi-plugin-graphql/services/Aggregator.js
Labels: pr: 🐛 Bug fix, source: Plugin

#4270 Add POST route /auth/send-email-confirmation
  docs/3.0.0-beta.x/plugins/users-permissions.md
  packages/strapi-plugin-users-permissions/config/routes.json
  packages/strapi-plugin-users-permissions/controllers/Auth.js
  packages/strapi-plugin-users-permissions/documentation/1.0.0/overrides/users-permissions-User.json
Labels: pr: 🚀 New feature, source: Plugin

#4412 Add guide to fetch and insert external data
  docs/.vuepress/config.js
  docs/3.0.0-beta.x/guides/external-data.md
Labels: pr: 💅 Enhancement, source: Documentation

#4529 Write the correct database configuration
  packages/strapi-generate-new/lib/create-customized-project.js
Labels: pr: 🐛 Bug fix, source: Framework

#4519 Retrieve roles without populating users and permissions relations
  packages/strapi-plugin-users-permissions/services/UsersPermissions.js
Labels: pr: 💅 Enhancement, source: Plugin

#4530 Add the model value in the core controller docs
  docs/3.0.0-beta.x/concepts/controllers.md
Labels: pr: 💅 Enhancement, source: Documentation

#4545 Clarify usage of model in create and update examples
  docs/3.0.0-beta.x/concepts/services.md
Labels: pr: 💅 Enhancement, source: Documentation

#4544 Correct typo in content-api documentation
  docs/3.0.0-beta.x/content-api/parameters.md
Labels: pr: 💅 Enhancement, source: Documentation

#4465 Fix non required JSON
  packages/strapi-admin/admin/src/containers/App/tests/index.test.js
  packages/strapi-helper-plugin/lib/src/components/InputsIndex/index.js
  packages/strapi-plugin-content-manager/admin/src/components/InputJSON/index.js
  packages/strapi-plugin-content-manager/admin/src/components/InputJSONWithErrors/index.js
  packages/strapi-plugin-content-manager/admin/src/containers/EditView/utils/formatData.js
  packages/strapi-plugin-content-manager/admin/src/containers/EditView/utils/schema.js
Labels: pr: 🐛 Bug fix, source: Admin

#4515 Update migration-guide-alpha.26-to-beta.md - to remove strapi-plugin-settings-manager package
  docs/3.0.0-beta.x/migration-guide/migration-guide-alpha.26-to-beta.md
Labels: pr: 💅 Enhancement, source: Documentation

#4516 Update migration-guide-alpha.26-to-beta.md - to add changes for Bootstrap function
  docs/3.0.0-beta.x/migration-guide/migration-guide-alpha.26-to-beta.md
Labels: pr: 💅 Enhancement, source: Documentation

#4533 Fix hot reload bug on Win 10
  packages/strapi-admin/index.js
Labels: pr: 🐛 Bug fix, source: Admin

#4552 valid JSON makes a working example
  docs/3.0.0-beta.x/plugins/documentation.md
Labels: pr: 💅 Enhancement, source: Documentation

#4551 Send details about administrator in events
  packages/strapi-plugin-content-manager/admin/src/containers/EditView/index.js
Labels: pr: 💅 Enhancement, source: Admin

#4414 Add Vietnamese translation
  examples/getstarted/config/locales/vi_vn.json
  packages/strapi-admin/admin/src/containers/LocaleToggle/index.js
  packages/strapi-admin/admin/src/containers/LocaleToggle/tests/index.test.js
  packages/strapi-admin/admin/src/i18n.js
  packages/strapi-admin/admin/src/translations/index.js
  packages/strapi-admin/admin/src/translations/vi.json
  packages/strapi-generate-plugin/files/admin/src/translations/index.js
  packages/strapi-generate-plugin/files/admin/src/translations/vi.json
  packages/strapi-plugin-content-manager/admin/src/translations/index.js
  packages/strapi-plugin-content-manager/admin/src/translations/vi.json
  packages/strapi-plugin-documentation/admin/src/translations/index.js
  packages/strapi-plugin-documentation/admin/src/translations/vi.json
  packages/strapi-plugin-email/admin/src/translations/index.js
  packages/strapi-plugin-email/admin/src/translations/vi.json
  packages/strapi-plugin-upload/admin/src/translations/index.js
  packages/strapi-plugin-upload/admin/src/translations/vi.json
  packages/strapi-plugin-users-permissions/admin/src/translations/index.js
  packages/strapi-plugin-users-permissions/admin/src/translations/vi.json
Labels: pr: 💅 Enhancement, source: Admin

#4563 Fix documentation redirection and css
  docs/.vuepress/theme/components/AlgoliaSearchBox.vue
  docs/.vuepress/theme/components/Navbar.vue
  docs/.vuepress/theme/index.js
Labels: pr: 🐛 Bug fix, source: Documentation

#4566 Add process manager guide
  docs/.vuepress/config.js
  docs/3.0.0-beta.x/guides/process-manager.md
Labels: pr: 💅 Enhancement, source: Documentation

#4588 docs: update doc
  docs/3.0.0-beta.x/guides/databases.md
Labels: pr: 💅 Enhancement, source: Documentation

#4568 Fix misleading database configuration documentation
  docs/3.0.0-beta.x/concepts/configurations.md
Labels: pr: 💅 Enhancement, source: Documentation

#4579 Add guide to customize admin and plugin
  docs/.vuepress/config.js
  docs/3.0.0-beta.x/guides/custom-admin.md
Labels: pr: 💅 Enhancement, source: Documentation

#4575 Some documentation update
  docs/3.0.0-beta.x/concepts/configurations.md
  docs/3.0.0-beta.x/content-api/api-endpoints.md
  docs/3.0.0-beta.x/content-api/parameters.md
  docs/3.0.0-beta.x/getting-started/install-requirements.md
  docs/3.0.0-beta.x/getting-started/quick-start-tutorial.md
  docs/3.0.0-beta.x/getting-started/quick-start.md
Labels: pr: 💅 Enhancement, source: Documentation

#4571 Add data response customization
  docs/.vuepress/config.js
  docs/3.0.0-beta.x/guides/custom-data-response.md
  docs/3.0.0-beta.x/guides/databases.md
Labels: pr: 💅 Enhancement, source: Documentation

#4585 Update link to pm2 guide
  docs/3.0.0-beta.x/guides/deployment.md
Labels: pr: 💅 Enhancement, source: Documentation

#4599 Fix lowercase the email in the forgot password function
  packages/strapi-plugin-users-permissions/controllers/Auth.js
Labels: pr: 🐛 Bug fix, source: Plugin

#4611 Add a docker ref in the docs
  docs/3.0.0-beta.x/guides/deployment.md
Labels: pr: 💅 Enhancement, source: Documentation

#4612 Display a deprecated message docs alpha
  docs/.vuepress/theme/components/Navbar.vue
Labels: pr: 💅 Enhancement, source: Documentation

#4600 Fix docs website link in the top menu
  docs/.vuepress/config.js
Labels: pr: 💅 Enhancement, source: Documentation

#4620 Add GA in the docs
  docs/.vuepress/config.js
  docs/package.json
  docs/yarn.lock
Labels: pr: 💅 Enhancement, source: Documentation

#4584 Update Russian translation for admin panel
  packages/strapi-admin/admin/src/translations/ru.json
Labels: pr: 💅 Enhancement, source: Admin

#4624 Hotfix mongo aggregate policy verifications
  packages/strapi-plugin-graphql/services/Aggregator.js
  packages/strapi-plugin-graphql/services/Resolvers.js
Labels: pr: 🐛 Bug fix, source: Plugin
