Repository strapi/strapi, pull requests merged in 2019-06, with the labels that each got.

#3353 Remove version key from root package.json of the monorepo
  package.json
Labels: pr: 💅 Enhancement, source: Framework

#3364 Fix install plugin when env is different than development
  packages/strapi-admin/admin/src/components/PluginCard/index.js
Labels: pr: 🐛 Bug fix, source: Admin

#3355 Add missing migration step mkdir extensions
  docs/3.0.0-beta.x/migration-guide/migration-guide-alpha.26-to-beta.md
Labels: pr: 🐛 Bug fix, source: Documentation

#3358 Typo fix in documentation
  docs/1.x.x/configuration.md
Labels: pr: 💅 Enhancement, source: Documentation

#3367 Update migration guide steps
  docs/3.0.0-beta.x/migration-guide/migration-guide-alpha.26-to-beta.md
Labels: pr: 💅 Enhancement, source: Documentation

#3368 Add migration guide link on beta doc homepage
  docs/3.0.0-beta.x/README.md
Labels: pr: 💅 Enhancement, source: Documentation

#3369 Update PR template to allow new PRs
  .github/PULL_REQUEST_TEMPLATE.md
Labels: pr: 💅 Enhancement, source: Documentation

#3372 Remove graphql special condition for delete request
  packages/strapi-plugin-graphql/services/Mutation.js
Labels: pr: 🐛 Bug fix, source: Plugin

#3381 Clarified and fixed instructions
  docs/3.0.0-beta.x/migration-guide/migration-guide-alpha.26-to-beta.md
Labels: pr: 💅 Enhancement, source: Documentation

#3373 Amazon AWS Strapi Deployment Docs
  docs/3.0.0-alpha.x/guides/deployment.md
  docs/3.0.0-beta.x/guides/deployment.md
Labels: pr: 💅 Enhancement, source: Documentation

#3395 Digital ocean deployment UPDATES
  docs/3.0.0-alpha.x/guides/deployment.md
  docs/3.0.0-beta.x/guides/deployment.md
Labels: pr: 💅 Enhancement, source: Documentation

#3400 Fix permission policy mixing users jwt and admin jwt
  packages/strapi-admin/services/auth.js
  packages/strapi-plugin-users-permissions/config/policies/permissions.js
Labels: pr: 🐛 Bug fix, source: Plugin

#3402 Improved clarity in plugin-architecture.md
  docs/3.0.0-beta.x/plugin-development/plugin-architecture.md
Labels: pr: 🐛 Bug fix, source: Documentation

#3404 Fix typo
  docs/3.0.0-beta.x/concepts/concepts.md
Labels: pr: 💅 Enhancement, source: Documentation

#3379 fix: ru welcome.again text
  packages/strapi-admin/admin/src/translations/ru.json
Labels: pr: 🐛 Bug fix, source: Admin

#3414 Init link helper to work on a project outside of the workspace
  packages/README.md
  scripts/link.js
Labels: pr: 💅 Enhancement, source: Framework

#3407 Fix error not ignored getPlugins
  packages/strapi-plugin-users-permissions/services/UsersPermissions.js
Labels: pr: 🐛 Bug fix, source: Plugin

#3401 Fix wrong param name in getType bookshelf hook
  packages/strapi-hook-bookshelf/lib/buildDatabaseSchema.js
Labels: pr: 🐛 Bug fix, source: Framework

#3422 Fix amountLimit in graphql queries
  examples/getstarted/extensions/graphql/config/settings.json
  packages/strapi-plugin-graphql/services/Query.js
Labels: pr: 🐛 Bug fix, source: Plugin

#3416 Fix primaryKey not found for custom resolvers
  packages/strapi-plugin-graphql/services/Query.js
Labels: pr: 🐛 Bug fix, source: Plugin

#3426 Add status code handler to health checks
  packages/strapi-helper-plugin/lib/src/utils/request.js
Labels: pr: 💅 Enhancement, source: Admin

#3432 Fixes #3224
  packages/strapi-plugin-content-type-builder/admin/src/containers/App/saga.js
Labels: pr: 🐛 Bug fix, source: Plugin

#3419 Front/repeatable fields leftmenu
  examples/getstarted/extensions/documentation/documentation/1.0.0/full_documentation.json
  packages/strapi-helper-plugin/lib/src/testUtils/mountWithIntl.js
  packages/strapi-plugin-content-type-builder/admin/src/components/CustomLink/StyledCustomLink.js
  packages/strapi-plugin-content-type-builder/admin/src/components/CustomLink/index.js
  packages/strapi-plugin-content-type-builder/admin/src/components/CustomLink/tests/index.test.js
  packages/strapi-plugin-content-type-builder/admin/src/components/DocumentationSection/index.js
  packages/strapi-plugin-content-type-builder/admin/src/components/DocumentationSection/tests/index.test.js
  packages/strapi-plugin-content-type-builder/admin/src/components/LeftMenu/index.js
  packages/strapi-plugin-content-type-builder/admin/src/components/LeftMenu/styles.scss
  packages/strapi-plugin-content-type-builder/admin/src/components/LeftMenu/tests/index.test.js
  packages/strapi-plugin-content-type-builder/admin/src/components/LeftMenuLink/Span.js
  packages/strapi-plugin-content-type-builder/admin/src/components/LeftMenuLink/index.js
  packages/strapi-plugin-content-type-builder/admin/src/components/LeftMenuLink/styles.scss
  packages/strapi-plugin-content-type-builder/admin/src/components/LeftMenuLink/tests/index.test.js
  packages/strapi-plugin-content-type-builder/admin/src/components/LeftMenuSection/index.js
  packages/strapi-plugin-content-type-builder/admin/src/components/LeftMenuSection/styles.scss
  packages/strapi-plugin-content-type-builder/admin/src/components/LeftMenuSection/tests/index.test.js
  packages/strapi-plugin-content-type-builder/admin/src/components/LeftMenuSectionTitle/index.js
  packages/strapi-plugin-content-type-builder/admin/src/components/LeftMenuSectionTitle/styles.scss
  packages/strapi-plugin-content-type-builder/admin/src/components/LeftMenuSectionTitle/tests/index.test.js
  packages/strapi-plugin-content-type-builder/admin/src/containers/App/actions.js
  packages/strapi-plugin-content-type-builder/admin/src/containers/App/index.js
  packages/strapi-plugin-content-type-builder/admin/src/containers/App/reducer.js
  packages/strapi-plugin-content-type-builder/admin/src/containers/App/saga.js
  packages/strapi-plugin-content-type-builder/admin/src/containers/App/tests/__snapshots__/saga.test.js.snap
  packages/strapi-plugin-content-type-builder/admin/src/containers/App/tests/actions.test.js
  packages/strapi-plugin-content-type-builder/admin/src/containers/App/tests/index.test.js
  packages/strapi-plugin-content-type-builder/admin/src/containers/App/tests/reducer.test.js
  packages/strapi-plugin-content-type-builder/admin/src/containers/App/tests/saga.test.js
  packages/strapi-plugin-content-type-builder/admin/src/containers/GroupPage/index.js
  packages/strapi-plugin-content-type-builder/admin/src/containers/GroupPage/tests/index.test.js
  packages/strapi-plugin-content-type-builder/admin/src/containers/HomePage/index.js
  packages/strapi-plugin-content-type-builder/admin/src/containers/LeftMenu/StyledLeftMenu.js
  packages/strapi-plugin-content-type-builder/admin/src/containers/LeftMenu/index.js
  packages/strapi-plugin-content-type-builder/admin/src/containers/LeftMenu/tests/index.test.js
  packages/strapi-plugin-content-type-builder/admin/src/containers/MenuContext/index.js
  packages/strapi-plugin-content-type-builder/admin/src/containers/ModelPage/DocumentationSection.js
  packages/strapi-plugin-content-type-builder/admin/src/containers/ModelPage/index.js
  packages/strapi-plugin-content-type-builder/admin/src/containers/ModelPage/tests/index.test.js
  packages/strapi-plugin-content-type-builder/admin/src/translations/ar.json
  packages/strapi-plugin-content-type-builder/admin/src/translations/de.json
  packages/strapi-plugin-content-type-builder/admin/src/translations/en.json
  packages/strapi-plugin-content-type-builder/admin/src/translations/es.json
  packages/strapi-plugin-content-type-builder/admin/src/translations/fr.json
  packages/strapi-plugin-content-type-builder/admin/src/translations/it.json
  packages/strapi-plugin-content-type-builder/admin/src/translations/ja.json
  packages/strapi-plugin-content-type-builder/admin/src/translations/ko.json
  packages/strapi-plugin-content-type-builder/admin/src/translations/nl.json
  packages/strapi-plugin-content-type-builder/admin/src/translations/pl.json
  packages/strapi-plugin-content-type-builder/admin/src/translations/pt-BR.json
  packages/strapi-plugin-content-type-builder/admin/src/translations/pt.json
  packages/strapi-plugin-content-type-builder/admin/src/translations/ru.json
  packages/strapi-plugin-content-type-builder/admin/src/translations/tr.json
  packages/strapi-plugin-content-type-builder/admin/src/translations/zh-Hans.json
  packages/strapi-plugin-content-type-builder/admin/src/translations/zh.json
  packages/strapi-plugin-content-type-builder/config/routes.json
  packages/strapi-plugin-content-type-builder/controllers/Fixtures.js
Labels: pr: 🚀 New feature

#3417 Load extensions in graphql schemas
  examples/getstarted/exports/graphql/schema.graphql
  examples/getstarted/extensions/users-permissions/config/schema.graphql.js
  packages/strapi-plugin-graphql/hooks/graphql/index.js
  packages/strapi-plugin-graphql/hooks/graphql/load-config.js
Labels: pr: 🐛 Bug fix, source: Plugin

#3410 Remove strapi.koaMiddlewares and simplify middleware ordering algorithm
  docs/3.0.0-beta.x/advanced/middlewares.md
  docs/3.0.0-beta.x/api-reference/reference.md
  examples/getstarted/config/middleware.json
  examples/getstarted/middlewares/testM/index.js
  examples/getstarted/plugins/myplugin/middlewares/mazdaz/index.js
  packages/strapi-middleware-views/lib/index.js
  packages/strapi-plugin-documentation/controllers/Documentation.js
  packages/strapi-plugin-documentation/middlewares/documentation/index.js
  packages/strapi-plugin-documentation/package.json
  packages/strapi-plugin-graphql/package.json
  packages/strapi-plugin-graphql/services/Mutation.js
  packages/strapi-plugin-graphql/services/Query.js
  packages/strapi-plugin-users-permissions/controllers/Auth.js
  packages/strapi-plugin-users-permissions/middlewares/users-permissions/index.js
  packages/strapi-plugin-users-permissions/package.json
  packages/strapi/lib/Strapi.js
  packages/strapi/lib/core/bootstrap.js
  packages/strapi/lib/core/load-middlewares.js
  packages/strapi/lib/middlewares/boom/index.js
  packages/strapi/lib/middlewares/cors/index.js
  packages/strapi/lib/middlewares/cron/index.js
  packages/strapi/lib/middlewares/csp/index.js
  packages/strapi/lib/middlewares/csrf/index.js
  packages/strapi/lib/middlewares/favicon/index.js
  packages/strapi/lib/middlewares/gzip/index.js
  packages/strapi/lib/middlewares/hsts/index.js
  packages/strapi/lib/middlewares/index.js
  packages/strapi/lib/middlewares/ip/index.js
  packages/strapi/lib/middlewares/language/index.js
  packages/strapi/lib/middlewares/logger/index.js
  packages/strapi/lib/middlewares/mask/index.js
  packages/strapi/lib/middlewares/p3p/index.js
  packages/strapi/lib/middlewares/parser/index.js
  packages/strapi/lib/middlewares/public/index.js
  packages/strapi/lib/middlewares/responseTime/index.js
  packages/strapi/lib/middlewares/responses/index.js
  packages/strapi/lib/middlewares/router/index.js
  packages/strapi/lib/middlewares/router/utils/composeEndpoint.js
  packages/strapi/lib/middlewares/router/utils/routerChecker.js
  packages/strapi/lib/middlewares/session/index.js
  packages/strapi/lib/middlewares/xframe/index.js
  packages/strapi/lib/middlewares/xss/index.js
Labels: pr: 💅 Enhancement, source: Framework

#3442 Remove strapi build on new
  examples/getstarted/package.json
  packages/strapi-generate-new/lib/after.js
  packages/strapi/lib/commands/develop.js
  packages/strapi/lib/utils/index.js
  packages/strapi/package.json
Labels: pr: 💅 Enhancement, source: Framework

#3443 Fix documentation load settings
  packages/strapi-plugin-documentation/services/Documentation.js
Labels: pr: 🐛 Bug fix, source: Plugin

#3458 Fix typo in documentation
  docs/3.0.0-beta.x/guides/services.md
Labels: pr: 💅 Enhancement, source: Documentation

#3450 Improve CLI documentation
  docs/3.0.0-beta.x/cli/CLI.md
Labels: pr: 💅 Enhancement, source: Documentation

#3453 Requiring bootstrap.js before config loading
  packages/strapi/lib/Strapi.js
Labels: pr: 🐛 Bug fix, source: Framework

#3444 Improve example in the documentation
  docs/3.0.0-beta.x/guides/models.md
Labels: pr: 💅 Enhancement, source: Documentation

#3439 Fix curl request example in documentation
  docs/3.0.0-beta.x/guides/upload.md
Labels: pr: 💅 Enhancement, source: Documentation

#3371 Update description and keyword of the package strapi
  packages/strapi/package.json
Labels: pr: 💅 Enhancement, source: Documentation

#3438 Fix strapi.query.delete passing invalid property to bookshelf
  packages/strapi/lib/core-api/queries/bookshelf.js
Labels: pr: 🐛 Bug fix, source: Framework

#3469 Fix crash caused by strapi-plugin-users-permissions
  packages/strapi-plugin-users-permissions/services/UsersPermissions.js
Labels: pr: 🐛 Bug fix, source: Plugin

#3464 Update NPM Badge on Readme to Beta
  README.md
Labels: pr: 💅 Enhancement, source: Documentation

#3435 Init gitlab ci trigger
  .gitlab-ci.yml
Labels: pr: 💅 Enhancement, source: Framework

#3459 Allow different envrionment names on config load
  packages/strapi/lib/load/__tests__/check-reserved-filename.test.js
  packages/strapi/lib/load/check-reserved-filename.js
  packages/strapi/lib/load/load-config-files.js
  packages/strapi/lib/load/load-files.js
  packages/strapi/package.json
Labels: pr: 🐛 Bug fix, source: Framework

#3452 Fix wording of welcome text
  packages/strapi-admin/admin/src/translations/en.json
  packages/strapi-helper-plugin/lib/src/testUtils/commonTrads.json
  test/config/front/testUtils/commonTrads.json
Labels: pr: 💅 Enhancement, source: Admin

#3460 Only use keys from settings.json to create documentation files
  packages/strapi-plugin-documentation/services/Documentation.js
  packages/strapi/lib/Strapi.js
Labels: pr: 🐛 Bug fix, source: Plugin

#3485 Call requireBootstrap on init
  packages/strapi/lib/Strapi.js
Labels: pr: 💅 Enhancement, source: Framework

#3480 Fix user routes using _id instead of id
  examples/getstarted/config/environments/development/database.js
  examples/getstarted/config/environments/development/database.json
  examples/getstarted/extensions/documentation/documentation/1.0.0/full_documentation.json
  examples/getstarted/extensions/users-permissions/documentation/1.0.0/users-permissions-User.json
  examples/getstarted/package.json
  packages/strapi-plugin-users-permissions/config/routes.json
Labels: pr: 🐛 Bug fix, source: Plugin

#3488 Fix admin UI bugs
  .gitignore
  packages/strapi-plugin-settings-manager/services/SettingsManager.js
  packages/strapi-plugin-users-permissions/admin/src/components/Controller/index.js
  packages/strapi-plugin-users-permissions/admin/src/components/Controller/styles.scss
  packages/strapi-plugin-users-permissions/admin/src/components/Plugins/index.js
  packages/strapi-plugin-users-permissions/admin/src/translations/en.json
  packages/strapi-plugin-users-permissions/admin/src/translations/fr.json
Labels: pr: 🐛 Bug fix, source: Admin

#3466 Replace koa-router-joi (strapi fork) by original and maintained
  packages/strapi-admin/package.json
  packages/strapi-plugin-graphql/package.json
  packages/strapi-plugin-users-permissions/package.json
  packages/strapi/lib/core/bootstrap.js
  packages/strapi/lib/middlewares/router/index.js
  packages/strapi/lib/middlewares/router/utils/routerChecker.js
  packages/strapi/package.json
  yarn.lock
Labels: pr: 💅 Enhancement, source: Framework

#3501 Update NL translations
  packages/strapi-admin/admin/src/translations/nl.json
Labels: pr: 💅 Enhancement, source: Admin

#3468 Update JA translation
  packages/strapi-admin/admin/src/translations/ja.json
Labels: pr: 💅 Enhancement, source: Admin

#3461 Update ES translations
  packages/strapi-admin/admin/src/translations/es.json
  packages/strapi-plugin-content-manager/admin/src/translations/es.json
  packages/strapi-plugin-content-type-builder/admin/src/translations/es.json
  packages/strapi-plugin-upload/admin/src/translations/en.json
  packages/strapi-plugin-upload/admin/src/translations/es.json
Labels: pr: 💅 Enhancement, source: Admin

#3503 Clear exemple strapi-plugin-documentation and add it to gitignore
  examples/getstarted/.gitignore
  examples/getstarted/api/articles/documentation/1.0.0/articles.json
  examples/getstarted/api/post/documentation/1.0.0/post.json
  examples/getstarted/extensions/documentation/documentation/1.0.0/full_documentation.json
  examples/getstarted/extensions/email/documentation/1.0.0/email-Email.json
  examples/getstarted/extensions/upload/documentation/1.0.0/upload-File.json
  examples/getstarted/extensions/users-permissions/documentation/1.0.0/users-permissions-Role.json
  examples/getstarted/extensions/users-permissions/documentation/1.0.0/users-permissions-User.json
Labels: pr: 💅 Enhancement, source: Framework

#3140 Add the option for a different Amazon SES domain
  packages/strapi-provider-email-amazon-ses/lib/index.js
Labels: pr: 💅 Enhancement, source: Plugin

#3478 Change CTA label to delete selected entries
  packages/strapi-plugin-content-manager/admin/src/components/Table/index.js
  packages/strapi-plugin-content-manager/admin/src/components/TableDelete/index.js
  packages/strapi-plugin-content-manager/admin/src/translations/ar.json
  packages/strapi-plugin-content-manager/admin/src/translations/de.json
  packages/strapi-plugin-content-manager/admin/src/translations/en.json
  packages/strapi-plugin-content-manager/admin/src/translations/es.json
  packages/strapi-plugin-content-manager/admin/src/translations/fr.json
  packages/strapi-plugin-content-manager/admin/src/translations/it.json
  packages/strapi-plugin-content-manager/admin/src/translations/ja.json
  packages/strapi-plugin-content-manager/admin/src/translations/ko.json
  packages/strapi-plugin-content-manager/admin/src/translations/nl.json
  packages/strapi-plugin-content-manager/admin/src/translations/pl.json
  packages/strapi-plugin-content-manager/admin/src/translations/pt-BR.json
  packages/strapi-plugin-content-manager/admin/src/translations/pt.json
  packages/strapi-plugin-content-manager/admin/src/translations/ru.json
  packages/strapi-plugin-content-manager/admin/src/translations/tr.json
  packages/strapi-plugin-content-manager/admin/src/translations/zh.json
Labels: pr: 💅 Enhancement, source: Plugin

#3511 Update Slack badge URL
  README.md
Labels: pr: 💅 Enhancement, source: Documentation

#3540 Fix admin pwd persisted in plaintext on edit
  packages/strapi-admin/controllers/Admin.js
Labels: pr: 🐛 Bug fix, source: Admin

#3541 Fix grant-koa breaking with strapi on grant-koa v4.6.0
  packages/strapi-plugin-users-permissions/controllers/Auth.js
  packages/strapi-plugin-users-permissions/package.json
  yarn.lock
Labels: pr: 🐛 Bug fix, source: Plugin
