Repository strapi/strapi, pull requests merged in 2019-01, with the labels that each got.

#2569 Update to 2019
  LICENSE.md
  README.md
  packages/strapi-admin/LICENSE.md
  packages/strapi-generate-admin/LICENSE.md
  packages/strapi-generate-api/LICENSE.md
  packages/strapi-generate-controller/LICENSE.md
  packages/strapi-generate-model/LICENSE.md
  packages/strapi-generate-new/LICENSE.md
  packages/strapi-generate-plugin/LICENSE.md
  packages/strapi-generate-policy/LICENSE.md
  packages/strapi-generate-service/LICENSE.md
  packages/strapi-hook-bookshelf/LICENSE.md
  packages/strapi-hook-ejs/LICENSE.md
  packages/strapi-hook-knex/LICENSE.md
  packages/strapi-hook-mongoose/LICENSE.md
  packages/strapi-hook-redis/LICENSE.md
  packages/strapi-middleware-views/LICENSE.md
  packages/strapi-provider-email-amazon-ses/LICENSE.md
  packages/strapi-provider-email-mailgun/LICENSE.md
  packages/strapi-provider-email-sendgrid/LICENSE.md
  packages/strapi-provider-email-sendmail/LICENSE.md
  packages/strapi-provider-upload-aws-s3/LICENSE.md
  packages/strapi-provider-upload-local/LICENSE.md
  packages/strapi-provider-upload-rackspace/LICENSE.md
  packages/strapi-utils/LICENSE.md
  packages/strapi/LICENSE.md
Labels: pr: 💅 Enhancement, source: Documentation

#2523 Update quick start documentation
  docs/3.x.x/getting-started/quick-start.md
Labels: pr: 💅 Enhancement, source: Documentation

#2540 Add JS query example in relation documentation
  docs/3.x.x/guides/models.md
Labels: pr: 💅 Enhancement, source: Documentation

#2557 Improve strapi new
  docs/3.x.x/cli/CLI.md
  packages/strapi-generate-new/lib/before.js
  packages/strapi-hook-bookshelf/lib/utils/connectivity.js
  packages/strapi-hook-mongoose/lib/utils/connectivity.js
  packages/strapi/bin/strapi-new.js
  packages/strapi/bin/strapi.js
Labels: pr: 💅 Enhancement, source: Framework

#2504 Add note for fish shell users
  CONTRIBUTING.md
Labels: pr: 💅 Enhancement, source: Documentation

#2534 Add force option when database not empty with bookshelf
  docs/3.x.x/cli/CLI.md
  packages/strapi-hook-bookshelf/lib/utils/connectivity.js
  packages/strapi/bin/strapi-new.js
  packages/strapi/bin/strapi.js
Labels: pr: 💅 Enhancement, source: Framework

#2583 Add logo to documentation plugin
  packages/strapi-plugin-documentation/admin/src/assets/images/logo.svg
Labels: pr: 🐛 Bug fix, source: Plugin

#2584 Add migration of jwt.json file
  docs/3.x.x/migration-guide/migration-guide-alpha.10-to-alpha.11.md
  docs/3.x.x/migration-guide/migration-guide-alpha.11-to-alpha.12.md
  docs/3.x.x/migration-guide/migration-guide-alpha.12.1-to-alpha.12.2.md
  docs/3.x.x/migration-guide/migration-guide-alpha.12.2-to-alpha.12.3.md
  docs/3.x.x/migration-guide/migration-guide-alpha.12.3-to-alpha.12.4.md
  docs/3.x.x/migration-guide/migration-guide-alpha.12.4-to-alpha.12.5.md
  docs/3.x.x/migration-guide/migration-guide-alpha.12.5-to-alpha.12.6.md
  docs/3.x.x/migration-guide/migration-guide-alpha.12.6-to-alpha.12.7.md
  docs/3.x.x/migration-guide/migration-guide-alpha.12.7-to-alpha.13.md
  docs/3.x.x/migration-guide/migration-guide-alpha.13-to-alpha.13.1.md
  docs/3.x.x/migration-guide/migration-guide-alpha.13.1-to-alpha.14.md
  docs/3.x.x/migration-guide/migration-guide-alpha.14-to-alpha.14.1.md
  docs/3.x.x/migration-guide/migration-guide-alpha.14.1-to-alpha.14.2.md
  docs/3.x.x/migration-guide/migration-guide-alpha.14.2-to-alpha.14.3.md
  docs/3.x.x/migration-guide/migration-guide-alpha.14.3-to-alpha.14.4.md
  docs/3.x.x/migration-guide/migration-guide-alpha.14.4-to-alpha.14.5.md
  docs/3.x.x/migration-guide/migration-guide-alpha.14.5-to-alpha.15.md
  docs/3.x.x/migration-guide/migration-guide-alpha.15-to-alpha.16.md
  docs/3.x.x/migration-guide/migration-guide-alpha.16-to-alpha.17.md
  docs/3.x.x/migration-guide/migration-guide-alpha.17-to-alpha.18.md
  docs/3.x.x/migration-guide/migration-guide-alpha.8-to-alpha.9.md
  docs/3.x.x/migration-guide/migration-guide-alpha.9-to-alpha.10.md
  packages/strapi-plugin-users-permissions/admin/src/containers/AuthPage/saga.js
Labels: pr: 💅 Enhancement, source: Documentation

#2585 Remove relations route from bookshelf template
  packages/strapi-generate-api/json/routes.json.js
  packages/strapi-generate-api/templates/bookshelf/controller.template
Labels: pr: 🐛 Bug fix, source: Framework

#2556 Custom timestamp column names in database
  docs/3.x.x/guides/models.md
  packages/strapi-hook-bookshelf/lib/index.js
  packages/strapi-hook-mongoose/lib/index.js
  packages/strapi-plugin-content-manager/admin/src/containers/EditPage/saga.js
  packages/strapi-plugin-content-manager/config/functions/bootstrap.js
Labels: pr: 🚀 New feature, source: Framework

#2594 Small grammatical fix
  docs/3.x.x/guides/filters.md
Labels: pr: 💅 Enhancement, source: Documentation

#2571 Fix Create new role bug related to permissions missing
  packages/strapi-plugin-users-permissions/config/routes.json
Labels: pr: 🐛 Bug fix, source: Plugin

#2572 Update deployment guide with helpful hint
  docs/3.x.x/guides/deployment.md
Labels: pr: 💅 Enhancement, source: Documentation

#2518 Avoid write files if not development environment
  packages/strapi-generate-new/files/config/environments/production/server.json
  packages/strapi-generate-new/files/config/environments/staging/server.json
  packages/strapi-plugin-graphql/services/Schema.js
  packages/strapi-plugin-users-permissions/services/UsersPermissions.js
  packages/strapi/lib/core/plugins.js
Labels: pr: 🐛 Bug fix, source: Framework

#2565 Update inquirer version to resolve Windows cli hang
  packages/strapi-generate-new/package.json
  packages/strapi-hook-bookshelf/package.json
Labels: pr: 🐛 Bug fix, source: Framework

#2500 Updated documentation for model indexing
  docs/3.x.x/guides/models.md
Labels: pr: 💅 Enhancement, source: Documentation

#2445 Avoid duplicating the message when wrapping errors with Bom
  packages/strapi/lib/middlewares/boom/index.js
Labels: pr: 🐛 Bug fix, source: Framework

#2537 Fix query building in user-permissions/services/Provider.js
  packages/strapi-plugin-users-permissions/services/Providers.js
Labels: pr: 🐛 Bug fix, source: Plugin

#2597 Update PR Template with database testing checks
  .github/PULL_REQUEST_TEMPLATE.md
Labels: pr: 💅 Enhancement, source: Documentation

#2618 Update graphql.md
  docs/3.x.x/guides/graphql.md
Labels: pr: 💅 Enhancement, source: Documentation

#2612 Add Documentation and Help links
  packages/strapi-admin/admin/src/components/LeftMenuFooter/index.js
  packages/strapi-admin/admin/src/components/LeftMenuFooter/messages.json
  packages/strapi-admin/admin/src/components/LeftMenuFooter/styles.scss
  packages/strapi-admin/admin/src/components/LeftMenuLink/index.js
  packages/strapi-admin/admin/src/components/LeftMenuLinkContainer/styles.scss
  packages/strapi-admin/admin/src/containers/AdminPage/index.js
  packages/strapi-admin/admin/src/translations/en.json
  packages/strapi-admin/admin/src/translations/fr.json
Labels: pr: 💅 Enhancement, source: Admin

#2590 Add intl support in logout component
  packages/strapi-admin/admin/src/components/Logout/index.js
  packages/strapi-admin/admin/src/translations/ar.json
  packages/strapi-admin/admin/src/translations/de.json
  packages/strapi-admin/admin/src/translations/en.json
  packages/strapi-admin/admin/src/translations/es.json
  packages/strapi-admin/admin/src/translations/fr.json
  packages/strapi-admin/admin/src/translations/it.json
  packages/strapi-admin/admin/src/translations/ja.json
  packages/strapi-admin/admin/src/translations/ko.json
  packages/strapi-admin/admin/src/translations/nl.json
  packages/strapi-admin/admin/src/translations/pl.json
  packages/strapi-admin/admin/src/translations/pt-BR.json
  packages/strapi-admin/admin/src/translations/pt.json
  packages/strapi-admin/admin/src/translations/ru.json
  packages/strapi-admin/admin/src/translations/tr.json
  packages/strapi-admin/admin/src/translations/zh-Hans.json
  packages/strapi-admin/admin/src/translations/zh.json
Labels: pr: 💅 Enhancement, source: Admin

#2575 Grammar improvements to the installation docs
  docs/3.x.x/getting-started/installation.md
Labels: pr: 💅 Enhancement, source: Documentation

#2578 More friendly / grammar updates
  README.md
Labels: pr: 💅 Enhancement, source: Documentation

#2615 Fix connection issue with Heroku Postgres
  packages/strapi-generate-new/lib/before.js
Labels: pr: 🐛 Bug fix, source: Framework

#2632 Incorrect params variable name in user update
  packages/strapi-plugin-users-permissions/controllers/User.js
Labels: pr: 🐛 Bug fix, source: Plugin

#2655 Add listeners to events
  packages/strapi-generate-new/json/package.json.js
  packages/strapi-generate-new/lib/after.js
  packages/strapi-generate-new/lib/before.js
  packages/strapi-generate-new/package.json
  packages/strapi-plugin-users-permissions/controllers/Auth.js
Labels: pr: 💅 Enhancement, source: Framework

#2636 Avoid write files if production mode
  packages/strapi/lib/core/admin.js
Labels: pr: 🐛 Bug fix, source: Framework

#2638 Fix confusion between request and axios
  docs/3.x.x/guides/webhooks.md
Labels: pr: 💅 Enhancement, source: Documentation

#2661 Add uploads folder to generated gitignore
  packages/strapi-generate-new/lib/index.js
  packages/strapi-generate-new/templates/gitignore
  packages/strapi-generate-new/templates/gitkeep
Labels: pr: 🐛 Bug fix, source: Framework

#2380 Fix users CRUD mutations
  packages/strapi-admin/admin/src/config/manifest.json
  packages/strapi-generate-api/templates/bookshelf/service.template
  packages/strapi-generate-api/templates/mongoose/service.template
  packages/strapi-hook-bookshelf/lib/index.js
  packages/strapi-hook-mongoose/lib/index.js
  packages/strapi-hook-mongoose/lib/utils/index.js
  packages/strapi-plugin-content-manager/config/queries/mongoose.js
  packages/strapi-plugin-content-manager/services/ContentManager.js
  packages/strapi-plugin-documentation/admin/src/containers/HomePage/index.js
  packages/strapi-plugin-graphql/package.json
  packages/strapi-plugin-graphql/services/Loaders.js
  packages/strapi-plugin-graphql/services/Query.js
  packages/strapi-plugin-graphql/services/Resolvers.js
  packages/strapi-plugin-graphql/services/Types.js
  packages/strapi-plugin-users-permissions/config/schema.graphql
  packages/strapi-plugin-users-permissions/controllers/User.js
  packages/strapi-plugin-users-permissions/models/User.settings.json
  packages/strapi-plugin-users-permissions/services/User.js
  packages/strapi-utils/lib/models.js
Labels: pr: 🐛 Bug fix, source: Plugin

#2649 Fix Infinite loading when clearing the name of an existing role
  packages/strapi-plugin-users-permissions/admin/src/containers/EditPage/index.js
Labels: pr: 🐛 Bug fix, source: Plugin

#2651 Update controllers.md (Grammatical Mistake)
  docs/3.x.x/guides/controllers.md
Labels: pr: 💅 Enhancement, source: Documentation

#2629 Add note about docker to deployment documentation
  docs/3.x.x/guides/deployment.md
Labels: pr: 💅 Enhancement, source: Documentation

#2595 In `production` GraphQL Playground doesn't load the schema
  packages/strapi-plugin-graphql/hooks/graphql/index.js
Labels: pr: 💅 Enhancement, source: Plugin

#2609 Updated knex
  CONTRIBUTING.md
  docs/3.x.x/configurations/configurations.md
  packages/strapi-hook-knex/lib/index.js
  packages/strapi-hook-knex/package.json
  packages/strapi-utils/package.json
Labels: pr: 💅 Enhancement, source: Framework

#2680 Complete funnel
  packages/strapi-plugin-content-manager/controllers/ContentManager.js
  packages/strapi-plugin-content-type-builder/controllers/ContentTypeBuilder.js
  packages/strapi-plugin-users-permissions/controllers/UsersPermissions.js
  packages/strapi-plugin-users-permissions/services/UsersPermissions.js
Labels: pr: 💅 Enhancement, source: Framework

#2678 Fix get timestamp in the admin
  packages/strapi-hook-bookshelf/lib/index.js
  packages/strapi-hook-mongoose/lib/index.js
  packages/strapi-plugin-content-manager/config/functions/bootstrap.js
Labels: pr: 🐛 Bug fix, source: Framework

#2687 Fix SQL query where oneWay relationship is null
  packages/strapi-plugin-content-manager/services/ContentManager.js
  packages/strapi-plugin-graphql/services/Loaders.js
  packages/strapi-utils/lib/models.js
Labels: pr: 🐛 Bug fix, source: Plugin

#2682 Remove Mongoose warning logs
  .github/PULL_REQUEST_TEMPLATE.md
  packages/strapi-generate-api/templates/mongoose/service.template
  packages/strapi-hook-mongoose/lib/index.js
  packages/strapi-hook-mongoose/lib/relations.js
  packages/strapi-plugin-content-manager/config/queries/mongoose.js
  packages/strapi-plugin-email/config/queries/mongoose.js
  packages/strapi-plugin-upload/config/queries/mongoose.js
  packages/strapi-plugin-users-permissions/config/queries/mongoose.js
  packages/strapi/lib/core/store.js
Labels: pr: 💅 Enhancement, source: Framework

#2689 Add _in array query example
  docs/3.x.x/guides/filters.md
Labels: pr: 💅 Enhancement, source: Documentation

#2598 Add cli option for srv
  packages/strapi-generate-new/files/config/environments/production/database.json
  packages/strapi-generate-new/files/config/environments/staging/database.json
  packages/strapi/bin/strapi-new.js
  packages/strapi/bin/strapi.js
Labels: pr: 🐛 Bug fix, source: Framework

#2693 Fix image populate
  packages/strapi-hook-mongoose/lib/index.js
Labels: pr: 🐛 Bug fix, source: Framework

#2698 Fix database prod and staging template
  packages/strapi-generate-new/files/config/environments/production/database.json
  packages/strapi-generate-new/files/config/environments/staging/database.json
  packages/strapi-generate-new/json/database.json.js
  packages/strapi-generate-new/lib/before.js
  packages/strapi-generate-new/lib/index.js
Labels: pr: 🐛 Bug fix, source: Framework

#2711 Added missing region eu-north-1 (Stockholm) to AWS S3 upload
  packages/strapi-provider-upload-aws-s3/lib/index.js
Labels: pr: 💅 Enhancement, source: Plugin

#2717 Add new installation event
  packages/strapi-generate-new/lib/after.js
  packages/strapi-generate-new/lib/before.js
  packages/strapi-generate-new/lib/success.js
  packages/strapi/lib/utils/success.js
  packages/strapi/package.json
Labels: pr: 💅 Enhancement, source: Framework

#2718 Fix Bookshelf big integer - backend only
  packages/strapi-hook-bookshelf/lib/index.js
Labels: pr: 🐛 Bug fix, source: Plugin

#2690 Redesign marketplace and add new blocker component
  packages/strapi-admin/admin/src/app.js
  packages/strapi-admin/admin/src/components/LeftMenuLinkContainer/index.js
  packages/strapi-admin/admin/src/components/PluginCard/index.js
  packages/strapi-admin/admin/src/components/PluginCard/screenshot.png
  packages/strapi-admin/admin/src/components/PluginCard/styles.scss
  packages/strapi-admin/admin/src/components/SupportUsBanner/Loadable.js
  packages/strapi-admin/admin/src/components/SupportUsBanner/index.js
  packages/strapi-admin/admin/src/components/SupportUsBanner/styles.scss
  packages/strapi-admin/admin/src/config/manifest.json
  packages/strapi-admin/admin/src/containers/AdminPage/index.js
  packages/strapi-admin/admin/src/containers/AdminPage/styles.scss
  packages/strapi-admin/admin/src/containers/App/actions.js
  packages/strapi-admin/admin/src/containers/App/reducer.js
  packages/strapi-admin/admin/src/containers/App/selectors.js
  packages/strapi-admin/admin/src/containers/InstallPluginPage/actions.js
  packages/strapi-admin/admin/src/containers/InstallPluginPage/constants.js
  packages/strapi-admin/admin/src/containers/InstallPluginPage/index.js
  packages/strapi-admin/admin/src/containers/InstallPluginPage/reducer.js
  packages/strapi-admin/admin/src/containers/InstallPluginPage/saga.js
  packages/strapi-admin/admin/src/containers/InstallPluginPage/selectors.js
  packages/strapi-admin/admin/src/containers/Marketplace/Loadable.js
  packages/strapi-admin/admin/src/containers/Marketplace/actions.js
  packages/strapi-admin/admin/src/containers/Marketplace/constants.js
  packages/strapi-admin/admin/src/containers/Marketplace/index.js
  packages/strapi-admin/admin/src/containers/Marketplace/reducer.js
  packages/strapi-admin/admin/src/containers/Marketplace/saga.js
  packages/strapi-admin/admin/src/containers/Marketplace/selectors.js
  packages/strapi-admin/admin/src/containers/Marketplace/styles.scss
  packages/strapi-admin/admin/src/strapi.js
  packages/strapi-admin/admin/src/translations/en.json
  packages/strapi-admin/admin/src/translations/fr.json
  packages/strapi-admin/package.json
  packages/strapi-helper-plugin/lib/src/components/LoadingIndicatorPage/index.js
  packages/strapi-helper-plugin/lib/src/components/OverlayBlocker/index.js
  packages/strapi-helper-plugin/lib/src/utils/request.js
Labels: pr: 💅 Enhancement, source: Admin

#2659 Fix InputDate not working
  packages/strapi-helper-plugin/lib/src/components/InputDateWithErrors/index.js
  packages/strapi-plugin-content-manager/admin/src/containers/EditPage/index.js
  packages/strapi-plugin-content-manager/admin/src/containers/EditPage/saga.js
Labels: pr: 🐛 Bug fix, source: Plugin

#2692 Fixing GraphQL timestamps
  packages/strapi-plugin-graphql/services/Resolvers.js
Labels: pr: 🐛 Bug fix, source: Plugin

#2725 Hotfix database name variable
  packages/strapi-generate-new/json/database.json.js
Labels: pr: 🐛 Bug fix, source: Framework

#2562 Add SQLite support
  packages/strapi-generate-api/templates/bookshelf/service.template
  packages/strapi-generate-new/lib/before.js
  packages/strapi-hook-bookshelf/lib/index.js
  packages/strapi-hook-bookshelf/lib/utils/connectivity.js
  packages/strapi-hook-knex/lib/index.js
  packages/strapi-plugin-content-manager/config/queries/bookshelf.js
  packages/strapi/bin/strapi-new.js
  packages/strapi/bin/strapi-start.js
  packages/strapi/bin/strapi.js
  test/start.js
Labels: pr: 🚀 New feature, source: Framework

#2719 Fix links HomePage
  packages/strapi-admin/admin/src/containers/AdminPage/index.js
  packages/strapi-admin/admin/src/containers/HomePage/WelcomeContent.js
  packages/strapi-admin/admin/src/containers/HomePage/index.js
  packages/strapi-plugin-content-manager/admin/src/components/TableHeader/styles.scss
Labels: pr: 💅 Enhancement, source: Admin

#2716 Update quick-start.md
  docs/3.x.x/plugin-development/quick-start.md
Labels: pr: 💅 Enhancement, source: Documentation
