Repository strapi/strapi, pull requests merged in 2019-04, with the labels that each got.

#3029 Fix Blue button
  packages/strapi-admin/admin/src/containers/Onboarding/index.js
  packages/strapi-admin/admin/src/containers/Onboarding/styles.scss
Labels: pr: 🐛 Bug fix, source: Admin

#3079 Add PR merge pause
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  README.md
Labels: pr: 💅 Enhancement, source: Documentation

#3010 Run snyk only on non fork repo
  .travis.yml
Labels: pr: 🐛 Bug fix, source: Framework

#2999 Added comment to improve linting of generated service files
  packages/strapi-generate-api/templates/mongoose/service.template
Labels: pr: 💅 Enhancement, source: Framework

#3032 Community link is broken
  docs/3.x.x/getting-started/introduction.md
Labels: pr: 💅 Enhancement, source: Documentation

#3003 Remove duplicated server
  docs/3.x.x/guides/api-documentation.md
  packages/strapi-plugin-documentation/config/settings.json
Labels: pr: 💅 Enhancement, source: Plugin

#3037 Run the database event if the connection is established
  packages/strapi-generate-new/lib/before.js
Labels: pr: 💅 Enhancement, source: Framework

#3051 Update CONTRIBUTING.md with fixes of minor typos
  CONTRIBUTING.md
Labels: pr: 💅 Enhancement, source: Documentation

#2961 Deep filtering
  .travis.yml
  README.md
  docs/3.x.x/guides/filters.md
  package.json
  packages/strapi-generate-api/templates/bookshelf/controller.template
  packages/strapi-generate-api/templates/bookshelf/service.template
  packages/strapi-generate-api/templates/mongoose/controller.template
  packages/strapi-generate-api/templates/mongoose/service.template
  packages/strapi-generate-new/json/package.json.js
  packages/strapi-hook-bookshelf/lib/buildQuery.js
  packages/strapi-hook-bookshelf/lib/index.js
  packages/strapi-hook-bookshelf/lib/relations.js
  packages/strapi-hook-knex/lib/index.js
  packages/strapi-hook-mongoose/lib/buildQuery.js
  packages/strapi-hook-mongoose/lib/index.js
  packages/strapi-hook-mongoose/lib/relations.js
  packages/strapi-hook-mongoose/lib/utils/index.js
  packages/strapi-plugin-content-manager/config/queries/bookshelf.js
  packages/strapi-plugin-content-manager/config/queries/mongoose.js
  packages/strapi-plugin-content-manager/package.json
  packages/strapi-plugin-content-manager/services/ContentManager.js
  packages/strapi-plugin-email/config/queries/bookshelf.js
  packages/strapi-plugin-email/config/queries/mongoose.js
  packages/strapi-plugin-email/package.json
  packages/strapi-plugin-graphql/hooks/graphql/index.js
  packages/strapi-plugin-graphql/services/Aggregator.js
  packages/strapi-plugin-graphql/services/Loaders.js
  packages/strapi-plugin-graphql/services/Mutation.js
  packages/strapi-plugin-graphql/services/Query.js
  packages/strapi-plugin-graphql/services/Resolvers.js
  packages/strapi-plugin-graphql/services/Schema.js
  packages/strapi-plugin-graphql/test/graphqlCrud.test.e2e.js
  packages/strapi-plugin-graphql/test/graphqlRelations.test.e2e.js
  packages/strapi-plugin-upload/config/queries/bookshelf.js
  packages/strapi-plugin-upload/config/queries/mongoose.js
  packages/strapi-plugin-upload/package.json
  packages/strapi-plugin-upload/services/Upload.js
  packages/strapi-plugin-users-permissions/config/queries/bookshelf.js
  packages/strapi-plugin-users-permissions/config/queries/mongoose.js
  packages/strapi-plugin-users-permissions/config/schema.graphql
  packages/strapi-plugin-users-permissions/controllers/User.js
  packages/strapi-plugin-users-permissions/controllers/UsersPermissions.js
  packages/strapi-plugin-users-permissions/services/Providers.js
  packages/strapi-plugin-users-permissions/services/User.js
  packages/strapi-plugin-users-permissions/services/UsersPermissions.js
  packages/strapi-utils/lib/__tests__/convertRestQueryParams.test.js
  packages/strapi-utils/lib/buildQuery.js
  packages/strapi-utils/lib/convertRestQueryParams.js
  packages/strapi-utils/lib/index.js
  packages/strapi-utils/lib/models.js
  packages/strapi-utils/package.json
  packages/strapi/bin/strapi-start.js
  packages/strapi/lib/hooks/index.js
  packages/strapi/package.json
  test/e2e.js
  test/helpers/generators.js
  test/helpers/generators.json
  test/helpers/testAppGenerator.js
Labels: flag: 💥 Breaking change, pr: 🚀 New feature, source: Plugin

#2994 Trim content builder model attributes
  packages/strapi-plugin-content-type-builder/services/ContentTypeBuilder.js
  packages/strapi-plugin-content-type-builder/utils/helpers.js
Labels: pr: 🐛 Bug fix, source: Plugin

#3090 Fix big integer support on GraphQL
  packages/strapi-plugin-graphql/package.json
  packages/strapi-plugin-graphql/services/Types.js
  packages/strapi-plugin-graphql/test/graphqlCrud.test.e2e.js
Labels: pr: 🐛 Bug fix, source: Plugin

#3088 Good old issues fixing before the beta
  packages/strapi-plugin-content-manager/admin/src/components/SelectMany/index.js
  packages/strapi-plugin-content-manager/admin/src/components/SelectMany/styles.scss
  packages/strapi-plugin-content-manager/admin/src/components/SelectManyDraggedItem/Content.js
  packages/strapi-plugin-content-manager/admin/src/components/SelectOne/index.js
  packages/strapi-plugin-content-manager/test/front/integration/createPage_specs.js
Labels: pr: 🐛 Bug fix, source: Plugin

#3110 Add gitignore step in Heroku tutorial
  docs/3.x.x/guides/deployment.md
Labels: pr: 💅 Enhancement, source: Documentation

#3111 Remove hiring banner from readme
  README.md
Labels: pr: 💅 Enhancement, source: Documentation

#3050 Use SQL aliases to allow for the same table name multiple times in a query
  docs/3.x.x/guides/filters.md
  packages/strapi-hook-bookshelf/lib/buildQuery.js
  test/e2e.js
Labels: pr: 💅 Enhancement, source: Framework

#3108 Split admin and users.
  cypress/support/commands.js
  packages/strapi-admin/admin/src/components/Logout/index.js
  packages/strapi-admin/admin/src/components/Logout/styles.scss
  packages/strapi-admin/admin/src/translations/en.json
  packages/strapi-admin/config/layout.js
  packages/strapi-admin/config/queries/bookshelf.js
  packages/strapi-admin/config/queries/mongoose.js
  packages/strapi-admin/config/routes.json
  packages/strapi-admin/controllers/Admin.js
  packages/strapi-admin/controllers/Auth.js
  packages/strapi-admin/models/Administrator.js
  packages/strapi-admin/models/Administrator.settings.json
  packages/strapi-admin/package.json
  packages/strapi-generate-api/test/endpoint.test.e2e.js
  packages/strapi-helper-plugin/lib/src/components/LiLink/index.js
  packages/strapi-helper-plugin/lib/src/components/LiLink/styles.scss
  packages/strapi-hook-bookshelf/lib/index.js
  packages/strapi-hook-mongoose/lib/index.js
  packages/strapi-plugin-content-manager/admin/src/containers/EditPage/index.js
  packages/strapi-plugin-content-manager/admin/src/utils/formValidations.js
  packages/strapi-plugin-content-manager/config/functions/bootstrap.js
  packages/strapi-plugin-content-manager/config/policies/routing.js
  packages/strapi-plugin-content-manager/services/ContentManager.js
  packages/strapi-plugin-content-manager/test/index.test.e2e.js
  packages/strapi-plugin-content-type-builder/admin/src/InjectedComponents/ContentManager/EditViewLink.js
  packages/strapi-plugin-content-type-builder/admin/src/InjectedComponents/ContentManager/tests/EditViewLink.test.js
  packages/strapi-plugin-graphql/test/graphqlCrud.test.e2e.js
  packages/strapi-plugin-graphql/test/graphqlRelations.test.e2e.js
  packages/strapi-plugin-users-permissions/admin/src/components/ListRow/index.js
  packages/strapi-plugin-users-permissions/admin/src/containers/AuthPage/saga.js
  packages/strapi-plugin-users-permissions/admin/src/containers/Initializer/actions.js
  packages/strapi-plugin-users-permissions/admin/src/containers/Initializer/constants.js
  packages/strapi-plugin-users-permissions/admin/src/containers/Initializer/reducer.js
  packages/strapi-plugin-users-permissions/config/policies/permissions.js
  packages/strapi-plugin-users-permissions/controllers/Auth.js
  packages/strapi-plugin-users-permissions/controllers/UsersPermissions.js
  packages/strapi-plugin-users-permissions/services/UsersPermissions.js
  packages/strapi-utils/lib/models.js
  packages/strapi/lib/Strapi.js
  test/helpers/auth.js
Labels: flag: 💥 Breaking change, pr: 🚀 New feature, source: Admin

#3116 Removed empty "TBD" sections from deployment.md
  docs/3.x.x/guides/deployment.md
Labels: pr: 💅 Enhancement, source: Documentation

#2945 Add necessary spaces before the list items
  docs/3.x.x/configurations/configurations.md
Labels: pr: 💅 Enhancement, source: Documentation

#3118 Fix redirect when editing a model
  packages/strapi-plugin-content-type-builder/admin/src/containers/App/saga.js
  packages/strapi-plugin-content-type-builder/admin/src/containers/ModelForm/index.js
  packages/strapi-plugin-content-type-builder/admin/src/containers/ModelPage/index.js
Labels: pr: 💅 Enhancement, source: Plugin

#3152 Fix column name for many to many relations
  packages/strapi-hook-bookshelf/lib/buildQuery.js
Labels: pr: 🐛 Bug fix, source: Framework

#3151 Fix issue with graphql loaders
  packages/strapi-plugin-graphql/services/Loaders.js
Labels: pr: 🐛 Bug fix, source: Plugin

#3141 Set the fetch limit to 100 by default and add a default param
  packages/strapi-utils/lib/convertRestQueryParams.js
Labels: pr: 🐛 Bug fix, source: Framework

#3158 Fix one to many update
  packages/strapi-hook-bookshelf/lib/relations.js
  packages/strapi-hook-mongoose/lib/relations.js
Labels: pr: 🐛 Bug fix, source: Framework

#3157 Fix missing populate in graphql queries
  packages/strapi-plugin-graphql/services/Query.js
Labels: pr: 🐛 Bug fix, source: Framework

#3148 Fix join multi database
  package.json
  packages/strapi-hook-bookshelf/lib/buildQuery.js
  packages/strapi-hook-bookshelf/lib/index.js
  packages/strapi-plugin-users-permissions/models/User.settings.json
  test/e2e.js
Labels: pr: 🐛 Bug fix, source: Framework

#3121 Added a paragraph about developing with Strapi and Heroku
  docs/3.x.x/guides/deployment.md
Labels: pr: 💅 Enhancement, source: Documentation

#3172 Cast non nil values and not only truthy ones
  packages/strapi-utils/lib/buildQuery.js
Labels: pr: 🐛 Bug fix, source: Framework

#3190 Cast arrays and build mongo where match with a $and
  packages/strapi-hook-mongoose/lib/buildQuery.js
  packages/strapi-utils/lib/buildQuery.js
Labels: pr: 🐛 Bug fix, source: Framework
