Repository strapi/strapi, pull requests merged in 2020-03, with the labels that each got.

#5367 Fix #5337 - suppress rewrite config in db without changes
  packages/strapi-plugin-content-manager/services/utils/store.js
Labels: type: bug, type: enhancement

#5362 fix: don't show unique attribute for rich text fields #5305
  packages/strapi-plugin-content-type-builder/admin/src/containers/FormModal/utils/forms.js
Labels: source: plugin:content-type-builder, type: bug

#5281 Init new Getting Started documentation
  docs/.vuepress/config.js
  docs/.vuepress/theme/global-components/InstallLink.vue
  docs/3.0.0-beta.x/getting-started/contributing.md
  docs/3.0.0-beta.x/getting-started/install-requirements.md
  docs/3.0.0-beta.x/getting-started/installation.md
  docs/3.0.0-beta.x/getting-started/introduction.md
  docs/3.0.0-beta.x/getting-started/troubleshooting.md
  docs/3.0.0-beta.x/installation/cli.md
  docs/3.0.0-beta.x/installation/docker.md
  docs/3.0.0-beta.x/installation/platformsh.md
  docs/package.json
Labels: source: documentation, type: enhancement

#5376 Add FAQ and clean up users-permissions docs
  docs/3.0.0-beta.x/getting-started/troubleshooting.md
  docs/3.0.0-beta.x/plugins/users-permissions.md
Labels: source: documentation, type: enhancement

#5392 Fix platform.sh steps titles
  docs/3.0.0-beta.x/installation/platformsh.md
Labels: source: documentation, type: enhancement

#5383 Fix enumeration on SQL databases
  packages/strapi-connector-bookshelf/lib/buildDatabaseSchema.js
Labels: source core:database, type: bug

#5370 Updated links in docs to referenced document pages
  docs/3.0.0-beta.x/guides/custom-data-response.md
Labels: source: documentation, type: enhancement

#5396 fix(EditViewDataManagerProvider): allow to reset number input
  packages/strapi-plugin-content-manager/admin/src/containers/EditViewDataManagerProvider/index.js
Labels: source: plugin:content-manager, type: enhancement

#5400 Fix SelectWrapper stack order
  packages/strapi-plugin-content-manager/admin/src/components/SelectWrapper/components.js
Labels: source: plugin:content-manager, type: bug

#5411 Fix component globalId
  packages/strapi/lib/core/load-components.js
Labels: source: core:database, type: bug

#5412 Fix entity validator for media
  packages/strapi/lib/services/entity-validator/index.js
Labels: source: core:framework, type: bug

#5413 Update migration guide
  docs/3.0.0-beta.x/admin-panel/customization.md
  docs/3.0.0-beta.x/migration-guide/migration-guide-beta.18-to-beta.19.md
  packages/strapi-admin/admin/src/app.js
  packages/strapi-admin/admin/src/components/LeftMenuLinkContainer/index.js
  packages/strapi-admin/admin/src/containers/Admin/index.js
Labels: source: admin, type: bug

#5419 Fit Left menu + scrollbars
  packages/strapi-admin/admin/src/components/GlobalStyle/index.js
  packages/strapi-admin/admin/src/components/LeftMenuLinkContainer/MenuSection.js
  packages/strapi-admin/admin/src/components/LeftMenuLinkContainer/Wrapper.js
  packages/strapi-admin/admin/src/components/LeftMenuLinkContainer/index.js
  packages/strapi-admin/admin/src/components/LeftMenuLinkSection/LeftMenuListLink.js
  packages/strapi-admin/admin/src/components/LeftMenuLinkSection/index.js
  packages/strapi-admin/admin/src/containers/LeftMenu/Wrapper.js
  packages/strapi-plugin-content-manager/admin/src/components/SelectMany/components.js
Labels: source: admin, type: enhancement

#5222 Add documentation reference for AWS SES URLs
  docs/3.0.0-beta.x/plugins/upload.md
Labels: source: documentation, type: enhancement

#5336 Update frontend-development.md
  docs/3.0.0-beta.x/plugin-development/frontend-development.md
Labels: source: documentation, type: enhancement

#5432 Fix plugin generator
  packages/strapi-generate-plugin/files/admin/src/index.js
Labels: source: core:framework, type: bug

#5436 Fix boom middleware logging < 500
  packages/strapi/lib/middlewares/boom/index.js
Labels: source: core:framework, type: bug

#5440 Fix/5439
  packages/strapi-utils/package.json
Labels: source: core:framework, type: bug

#5446 Update lodash to fix security issues
  packages/strapi-utils/package.json
Labels: source: core:framework, type: enhancement

#5398 Fixes typo on mongo image
  docs/3.0.0-beta.x/installation/docker.md
Labels: source: documentation, type: enhancement

#5447 Add count GraphQL guide
  docs/.vuepress/config.js
  docs/3.0.0-beta.x/guides/count-graphql.md
Labels: source: documentation, type: enhancement

#5476 Add front-end settings API to documentation
  docs/.vuepress/config.js
Labels: source: documentation, type: documentation

#5298 Add DigitalOcean one-click docs
  docs/3.0.0-beta.x/getting-started/installation.md
  docs/3.0.0-beta.x/installation/digitalocean-one-click.md
Labels: source: documentation, type: enhancement

#5486 fix #5399 Strapi is not using the configured host when launching the server
  packages/strapi/lib/Strapi.js
Labels: source: core:framework, type: enhancement

#5407 Minor typo fixes
  docs/3.0.0-beta.x/migration-guide/migration-guide-beta.18-to-beta.19.md
Labels: source: documentation, type: enhancement

#5426 fix typo
  docs/3.0.0-beta.x/installation/platformsh.md
Labels: source: documentation, type: enhancement

#5420 Add --no-run and --use-npm to CLI docs
  docs/3.0.0-beta.x/cli/CLI.md
Labels: source: documentation, type: enhancement

#5287 Fix/admin path serve
  docs/3.0.0-beta.x/admin-panel/deploy.md
  packages/strapi/lib/core/bootstrap.js
Labels: source: core:framework, type: enhancement

#5452 Fix find one cant have multiple parameters when there is a primary key
  packages/strapi-admin/controllers/Admin.js
  packages/strapi-connector-bookshelf/lib/queries.js
  packages/strapi-connector-mongoose/lib/queries.js
  packages/strapi-database/lib/queries/create-query.js
  packages/strapi-database/lib/utils/__tests__/primary-keys.test.js
  packages/strapi-database/lib/utils/primary-key.js
  packages/strapi-plugin-content-manager/controllers/ContentManager.js
  packages/strapi-plugin-content-manager/test/components/repeatable-required.test.e2e.js
  packages/strapi-plugin-upload/controllers/Upload.js
  packages/strapi-plugin-users-permissions/controllers/Auth.js
  packages/strapi-plugin-users-permissions/controllers/User.js
  packages/strapi/lib/core-api/controller.js
Labels: source: core:database, type: bug

#5499 Change error message when bookshelf db connection fails at start
  packages/strapi-connector-bookshelf/lib/mount-models.js
  packages/strapi/lib/Strapi.js
Labels: source: core:database, type: bug

#5494 add possibility to set a relation "private"
  packages/strapi-plugin-content-manager/test/dynamiczones/with-media.test.e2e.js
  packages/strapi-plugin-content-type-builder/controllers/ContentTypes.js
  packages/strapi-plugin-content-type-builder/controllers/validation/relations.js
  packages/strapi-plugin-content-type-builder/services/schema-builder/index.js
  packages/strapi-plugin-graphql/services/type-builder.js
  packages/strapi-plugin-graphql/services/type-definitions.js
  packages/strapi-plugin-graphql/test/graphqlRelations.test.e2e.js
Labels: source: plugin:graphql, type: bug

#5296 removed text-transform from variable name
  packages/strapi-plugin-content-type-builder/admin/src/components/ListRow/Wrapper.js
Labels: source: plugin:content-type-builder, type: enhancement

#5485 Add single type examples
  docs/3.0.0-beta.x/content-api/api-endpoints.md
  docs/3.0.0-beta.x/getting-started/introduction.md
Labels: source: documentation, type: enhancement

#5510 Update graphql.md
  docs/3.0.0-beta.x/plugins/graphql.md
Labels: source: documentation, type: enhancement

#5519 Fix/#4556/null when requiring a component in relation graph ql
  docs/3.0.0-beta.x/plugins/graphql.md
  packages/strapi-connector-bookshelf/lib/populate.js
  packages/strapi-plugin-content-type-builder/admin/src/components/ListRow/Wrapper.js
  packages/strapi-plugin-graphql/test/graphqlRelations.test.e2e.js
Labels: source: plugin:graphql, type: bug

#5541 Minor fixes to DO one-click docs
  docs/3.0.0-beta.x/installation/digitalocean-one-click.md
Labels: source: documentation, type: enhancement

#5533 Fix: don't diff custom resolvers
  packages/strapi-plugin-graphql/services/utils.js
Labels: source: plugin:graphql, type: enhancement

#5371 Removed redundant callback argument
  packages/strapi-plugin-email/services/Email.js
  packages/strapi-provider-email-amazon-ses/lib/index.js
  packages/strapi-provider-email-mailgun/lib/index.js
  packages/strapi-provider-email-sendgrid/lib/index.js
  packages/strapi-provider-email-sendmail/lib/index.js
Labels: source: plugin:email, type: enhancement

#5465 Make plugins documentation generation optional
  docs/3.0.0-beta.x/plugins/documentation.md
  packages/strapi-plugin-documentation/config/functions/bootstrap.js
  packages/strapi-plugin-documentation/config/settings.json
  packages/strapi-plugin-documentation/services/Documentation.js
Labels: source: plugin:documentation, type: enhancement

#5532 Fix context issue in custom GraphQL query and mutation
  packages/strapi-plugin-graphql/services/resolvers-builder.js
  packages/strapi-plugin-users-permissions/test/graphql.test.e2e.js
Labels: source: plugin:graphql, type: bug

#5516 Fix little syntax error
  docs/3.0.0-beta.x/concepts/services.md
Labels: source: documentation, type: enhancement

#5523 Update Dutch Translation and Typos [NL]
  packages/strapi-admin/admin/src/translations/nl.json
  packages/strapi-plugin-content-type-builder/admin/src/translations/nl.json
Labels: source: admin, type: enhancement

#5455 Document proofreads
  docs/3.0.0-beta.x/admin-panel/customization.md
  docs/3.0.0-beta.x/admin-panel/deploy.md
  docs/3.0.0-beta.x/cli/CLI.md
  docs/3.0.0-beta.x/concepts/configurations.md
  docs/3.0.0-beta.x/concepts/controllers.md
  docs/3.0.0-beta.x/concepts/customization.md
  docs/3.0.0-beta.x/concepts/file-structure.md
  docs/3.0.0-beta.x/concepts/logging.md
  docs/3.0.0-beta.x/concepts/middlewares.md
  docs/3.0.0-beta.x/concepts/models.md
  docs/3.0.0-beta.x/concepts/parameters.md
  docs/3.0.0-beta.x/concepts/policies.md
  docs/3.0.0-beta.x/concepts/public-assets.md
  docs/3.0.0-beta.x/concepts/routing.md
  docs/3.0.0-beta.x/content-api/api-endpoints.md
  docs/3.0.0-beta.x/getting-started/quick-start-tutorial.md
  docs/3.0.0-beta.x/guides/api-token.md
  docs/3.0.0-beta.x/guides/custom-admin.md
  docs/3.0.0-beta.x/guides/custom-data-response.md
  docs/3.0.0-beta.x/guides/deployment.md
  docs/3.0.0-beta.x/guides/draft.md
  docs/3.0.0-beta.x/guides/jwt-validation.md
  docs/3.0.0-beta.x/guides/secure-your-app.md
  docs/3.0.0-beta.x/guides/send-email.md
  docs/3.0.0-beta.x/guides/slug.md
  docs/3.0.0-beta.x/guides/update-version.md
  docs/3.0.0-beta.x/plugins/email.md
  docs/3.0.0-beta.x/plugins/upload.md
  docs/3.0.0-beta.x/plugins/users-permissions.md
Labels: source: documentation, type: enhancement

#5507 Fixed sentence structure and grammatical errors.
  docs/3.0.0-beta.x/getting-started/introduction.md
Labels: source: documentation, type: enhancement

#5553 Keep media order set on creation
  examples/getstarted/api/restaurant/models/Restaurant.settings.json
  packages/strapi-connector-bookshelf/lib/buildDatabaseSchema.js
  packages/strapi-connector-bookshelf/lib/mount-models.js
  packages/strapi-connector-bookshelf/lib/queries.js
  packages/strapi-connector-bookshelf/lib/relations.js
  packages/strapi-connector-mongoose/lib/mount-models.js
  packages/strapi-connector-mongoose/lib/queries.js
  packages/strapi-connector-mongoose/lib/relations.js
  packages/strapi-database/lib/database-manager.js
  packages/strapi-plugin-upload/services/Upload.js
  packages/strapi-utils/lib/__tests__/models.test.js
  packages/strapi-utils/lib/models.js
  packages/strapi/lib/Strapi.js
Labels: flag: 💥 Breaking change

#5536 Fix deep filtering for manyWay
  packages/strapi-connector-bookshelf/lib/buildQuery.js
  packages/strapi-connector-bookshelf/lib/mount-models.js
  packages/strapi/__tests__/deepFiltering.test.e2e.js
Labels: source: core:database, type: bug

#5576 Remove extra logs in users-permissions
  packages/strapi-plugin-users-permissions/config/policies/permissions.js
Labels: source: plugin:users-permissions, type: enhancement

#5578 Make UID searchable in Mongoose and avoid errors if content type can't be searched
  packages/strapi-connector-mongoose/lib/queries.js
Labels: source: core:database, type: bug

#5547 fix generate:model --plugin path + little refacto of code
  packages/strapi-generate-api/lib/before.js
  packages/strapi-generate-api/package.json
  packages/strapi-generate-controller/lib/before.js
  packages/strapi-generate-controller/package.json
  packages/strapi-generate-controller/templates/controller.template
  packages/strapi-generate-model/lib/before.js
  packages/strapi-generate-model/lib/index.js
  packages/strapi-generate-model/package.json
  packages/strapi-generate-model/templates/bookshelf/model.settings.template
  packages/strapi-generate-model/templates/bookshelf/model.template
  packages/strapi-generate-model/templates/mongoose/model.settings.template
  packages/strapi-generate-model/templates/mongoose/model.template
  packages/strapi-generate-plugin/json/routes.json.js
  packages/strapi-generate-plugin/lib/before.js
  packages/strapi-generate-plugin/lib/index.js
  packages/strapi-generate-plugin/package.json
  packages/strapi-generate-plugin/templates/controller.template
  packages/strapi-generate-policy/lib/before.js
  packages/strapi-generate-policy/package.json
  packages/strapi-generate-service/lib/before.js
  packages/strapi-generate-service/lib/index.js
  packages/strapi-generate-service/package.json
  packages/strapi-generate-service/templates/bookshelf/service.template
  packages/strapi-generate-service/templates/mongoose/service.template
  packages/strapi-generate/lib/generate.js
  packages/strapi-plugin-content-type-builder/services/ComponentCategories.js
  packages/strapi-plugin-content-type-builder/services/ContentTypes.js
  packages/strapi-plugin-content-type-builder/services/schema-builder/component-builder.js
  packages/strapi-plugin-content-type-builder/services/schema-builder/content-type-builder.js
  packages/strapi-plugin-content-type-builder/utils/helpers.js
  packages/strapi-utils/lib/index.js
  packages/strapi-utils/lib/stringFormatting.js
  packages/strapi-utils/package.json
  packages/strapi/lib/commands/generate.js
  yarn.lock
Labels: source: core:framework, type: bug

#5584 Fix the order of settings in ses provider
  packages/strapi-provider-email-amazon-ses/lib/index.js
Labels: source: plugin:email, type: bug

#5580 Added missing forgotPassword, changePassword and emailConfirmation mutations/resolvers
  packages/strapi-plugin-users-permissions/config/schema.graphql.js
  packages/strapi-plugin-users-permissions/controllers/Auth.js
Labels: source: plugin:graphql, type: enhancement

#5586 don't generate default routes when generating plugin api
  packages/strapi-generate-api/json/routes.json.js
Labels: source: core:framework, type: bug

#5607 Fix bad singular form of column name
  packages/strapi-connector-bookshelf/lib/generate-component-relations.js
Labels: source: core:database, type: bug

#5557 Remove condition that reset query start param
  packages/strapi-plugin-content-manager/admin/src/components/SelectWrapper/index.js
Labels: source: plugin:content-manager, type: enhancement

#5581 Fix rerouting of destroy route in user-perm
  packages/strapi-plugin-users-permissions/config/layout.js
Labels: source: plugin:users-permissions, type: bug

#5438 fix: short relation fields list have unnecessary scrollbar
  packages/strapi-plugin-content-manager/admin/src/components/SelectMany/components.js
Labels: source: plugin:content-manager, type: enhancement

#5605 Implement Graphql Aggregation Feature for Bookshelf
  packages/strapi-plugin-graphql/services/build-aggregation.js
  packages/strapi-plugin-graphql/services/type-definitions.js
Labels: source: plugin:graphql, type: enhancement

#5589 Translations: Updated the 'terms' translations for 'de'
  packages/strapi-admin/admin/src/translations/de.json
Labels: source: admin, type: enhancement

#5612 Fix ability to update unique constraints in mongoose
  packages/strapi-connector-mongoose/lib/mount-models.js
Labels: source: core:database, type: bug

#5625 Fix checkBadrequest useless logic in user-permissions' graphql config
  packages/strapi-plugin-users-permissions/config/schema.graphql.js
Labels: source: plugin:users-permissions, type: bug

#5622 Fix French trad for float and decimal
  packages/strapi-plugin-content-type-builder/admin/src/translations/fr.json
Labels: source: plugin:content-type-builder, type: enhancement

#5390 Fix the button name for configuring layout in docs
  docs/3.0.0-beta.x/guides/slug.md
Labels: source: admin, type: enhancement

#5596 Fix typo
  docs/3.0.0-beta.x/getting-started/quick-start-tutorial.md
Labels: source: documentation, type: enhancement

#5620 Fixes #5570
  packages/strapi-plugin-content-manager/admin/src/components/FilterPicker/index.js
  packages/strapi-plugin-content-manager/admin/src/components/FilterPicker/init.js
  packages/strapi-plugin-content-manager/admin/src/components/FilterPicker/reducer.js
  packages/strapi-plugin-content-manager/admin/src/components/FilterPickerOption/Input.js
  packages/strapi-plugin-content-manager/admin/src/components/FilterPickerOption/index.js
Labels: source: plugin:content-manager, type: enhancement

#5623 Fixes #5573
  packages/strapi-plugin-content-manager/admin/src/components/SelectWrapper/index.js
Labels: source: plugin:content-manager, type: bug

#5633 Changed add new entity button to just use getName for consistency (#5…
  packages/strapi-plugin-content-manager/admin/src/containers/ListView/index.js
Labels: source: plugin:content-manager, type: enhancement

#5629 Make strapi analytics simpler
  packages/strapi-admin/controllers/Auth.js
  packages/strapi-plugin-content-manager/controllers/ContentManager.js
  packages/strapi-plugin-content-type-builder/controllers/ContentTypes.js
  packages/strapi-plugin-content-type-builder/services/schema-builder/component-builder.js
  packages/strapi-plugin-content-type-builder/services/schema-builder/schema-handler.js
  packages/strapi/lib/Strapi.js
  packages/strapi/lib/services/metrics/__mocks__/node-fetch.js
  packages/strapi/lib/services/metrics/__tests__/index.test.js
  packages/strapi/lib/services/metrics/__tests__/is-truthy.js
  packages/strapi/lib/services/metrics/__tests__/middleware.test.js
  packages/strapi/lib/services/metrics/index.js
  packages/strapi/lib/services/metrics/is-truthy.js
  packages/strapi/lib/services/metrics/middleware.js
  packages/strapi/lib/utils/exposer.js
  packages/strapi/lib/utils/index.js
  packages/strapi/lib/utils/resources/key.pub
  packages/strapi/package.json
  yarn.lock
Labels: source: core:framework, type: enhancement

#5444 Add possibility to delete index.html + remove use of production.html
  docs/3.0.0-beta.x/concepts/configurations.md
  examples/getstarted/public/index.html
  examples/getstarted/public/production.html
  packages/strapi-generate-new/lib/resources/files/public/production.html
  packages/strapi/lib/core/bootstrap.js
  packages/strapi/lib/middlewares/favicon/defaults.json
  packages/strapi/lib/middlewares/public/defaults.json
  packages/strapi/lib/middlewares/public/index.html
  packages/strapi/lib/middlewares/public/index.js
Labels: flag: 💥 Breaking change, source: core:framework, type: bug

#5627 improve joinTable customization + test collectionName duplicates
  docs/3.0.0-beta.x/concepts/models.md
  packages/strapi-connector-bookshelf/lib/mount-models.js
  packages/strapi-database/lib/database-manager.js
  packages/strapi-database/lib/validation/before-mounting-models/check-duplicated-table-names.js
  packages/strapi-database/lib/validation/before-mounting-models/index.js
  packages/strapi-utils/lib/models.js
  packages/strapi/lib/load/load-config-files.js
Labels: source: core:database, type: enhancement

#5644 Add simple docker conf to run the getstarted with different databases
  CONTRIBUTING.md
  Makefile
  docker-compose.dev.yml
  examples/getstarted/README.md
  mkdocs.yml
Labels: source: core:framework, type: enhancement

#5657 fix: GraphQL Aggregation Bookshelf `where` condition aren't applied to groupBy
  packages/strapi-plugin-graphql/services/build-aggregation.js
Labels: source: plugin:graphql, type: bug
