Repository strapi/strapi, pull requests merged in 2020-12, with the labels that each got.

#8777 Add manyWay relation example
  docs/v3.x/concepts/models.md
Labels: source: documentation, type: enhancement

#8764 Docs fix type singleType findOne
  docs/v3.x/concepts/services.md
Labels: source: documentation, type: enhancement

#8740 Fix `strapi -v` and `strapi --version` options
  packages/strapi/bin/strapi.js
Labels: source: core:cli, type: bug

#8706 Bug/collection type sort asc
  packages/strapi-helper-plugin/lib/src/components/LeftMenuList/index.js
Labels: source: admin, type: bug

#8665 Add some admin french translations
  packages/strapi-admin/admin/src/translations/fr.json
  packages/strapi-plugin-content-manager/admin/src/translations/fr.json
  packages/strapi-plugin-content-type-builder/admin/src/translations/fr.json
  packages/strapi-plugin-upload/admin/src/translations/fr.json
  packages/strapi-plugin-upload/admin/src/translations/index.js
Labels: source: plugin:upload, type: translation

#8627 Improved create-strapi-app's templates
  docs/v3.x/concepts/templates.md
  packages/strapi-generate-new/lib/create-project.js
  packages/strapi-generate-new/lib/merge-template.js
  packages/strapi-generate-new/lib/utils/merge-template.js
Labels: source: core:cli, type: enhancement

#8082 [Unit testing doc] add runtime fix
  docs/v3.x/guides/unit-testing.md
Labels: source: documentation, type: enhancement

#8429 Change validateEntity to validateEntityCreation
  docs/v3.x/concepts/services.md
Labels: source: documentation, type: enhancement

#8119 Add ability to disable aggregation on GraphQL
  docs/v3.x/plugins/graphql.md
  packages/strapi-plugin-graphql/services/type-definitions.js
Labels: source: plugin:graphql, type: enhancement

#8358 adjust condition for subdomain when it is an empty string
  packages/strapi-plugin-users-permissions/admin/src/containers/Providers/utils/createProvidersArray.js
  packages/strapi-plugin-users-permissions/admin/src/containers/Providers/utils/tests/createProvidersArray.test.js
Labels: source: plugin:users-permissions, type: enhancement

#8631 Allow JSON stringify to pretty print the config dump via config
  packages/strapi/bin/strapi.js
  packages/strapi/lib/commands/configurationDump.js
Labels: source: core:cli, type: enhancement

#8738 Replace John Doe with Kai Doe
  docs/3.0.0-beta.x/content-api/parameters.md
  docs/3.0.0-beta.x/plugins/graphql.md
  docs/v3.x/content-api/parameters.md
  docs/v3.x/plugins/graphql.md
  packages/strapi-admin/admin/src/components/Users/ModalCreateBody/tests/reducer.test.js
  packages/strapi-admin/admin/src/components/Users/ModalCreateBody/utils/form.js
  packages/strapi-admin/admin/src/containers/AuthPage/tests/reducer.test.js
  packages/strapi-admin/admin/src/containers/ProfilePage/utils/form.js
  packages/strapi-admin/admin/src/containers/Users/EditPage/utils/form.js
  packages/strapi-admin/admin/src/hooks/useUsersForm/tests/reducer.test.js
  packages/strapi-admin/admin/src/translations/en.json
  packages/strapi-admin/admin/src/translations/es.json
  packages/strapi-admin/admin/src/translations/fr.json
  packages/strapi-admin/admin/src/translations/he.json
  packages/strapi-admin/admin/src/translations/id.json
  packages/strapi-admin/admin/src/translations/it.json
  packages/strapi-admin/admin/src/translations/ko.json
  packages/strapi-admin/admin/src/translations/nl.json
  packages/strapi-admin/admin/src/translations/pt-BR.json
  packages/strapi-admin/admin/src/translations/pt.json
  packages/strapi-admin/admin/src/translations/ru.json
  packages/strapi-admin/admin/src/translations/th.json
  packages/strapi-admin/admin/src/translations/tr.json
  packages/strapi-admin/admin/src/translations/vi.json
  packages/strapi-admin/admin/src/translations/zh-Hans.json
  packages/strapi-admin/admin/src/translations/zh.json
  packages/strapi-admin/controllers/__tests__/user.test.js
  packages/strapi-admin/services/__tests__/permissions-manager.test.js
  packages/strapi-admin/services/__tests__/permissions.conditions-provider.test.js
  packages/strapi-admin/services/__tests__/permissions.engine.test.js
  packages/strapi-admin/services/__tests__/user.test.js
  packages/strapi-plugin-content-manager/test/front/integration/createPage_specs.js
  packages/strapi-plugin-users-permissions/admin/src/translations/ar.json
  packages/strapi-plugin-users-permissions/admin/src/translations/de.json
  packages/strapi-plugin-users-permissions/admin/src/translations/en.json
  packages/strapi-plugin-users-permissions/admin/src/translations/es.json
  packages/strapi-plugin-users-permissions/admin/src/translations/id.json
  packages/strapi-plugin-users-permissions/admin/src/translations/it.json
  packages/strapi-plugin-users-permissions/admin/src/translations/ja.json
  packages/strapi-plugin-users-permissions/admin/src/translations/ko.json
  packages/strapi-plugin-users-permissions/admin/src/translations/ms.json
  packages/strapi-plugin-users-permissions/admin/src/translations/nl.json
  packages/strapi-plugin-users-permissions/admin/src/translations/pt-BR.json
  packages/strapi-plugin-users-permissions/admin/src/translations/pt.json
  packages/strapi-plugin-users-permissions/admin/src/translations/ru.json
  packages/strapi-plugin-users-permissions/admin/src/translations/sv.json
  packages/strapi-plugin-users-permissions/admin/src/translations/th.json
  packages/strapi-plugin-users-permissions/admin/src/translations/tr.json
  packages/strapi-plugin-users-permissions/admin/src/translations/uk.json
  packages/strapi-plugin-users-permissions/admin/src/translations/vi.json
  packages/strapi-plugin-users-permissions/admin/src/translations/zh-Hans.json
  packages/strapi-plugin-users-permissions/admin/src/translations/zh.json
Labels: source: documentation, type: enhancement

#8572 RBAC : Decorrelate create action, fix bugs, some refacto
  examples/getstarted/api/address/models/Address.settings.json
  examples/getstarted/api/category/models/Category.settings.json
  packages/strapi-admin/admin/src/components/Roles/ConditionsModal/index.js
  packages/strapi-admin/admin/src/components/Roles/Permissions/ContentTypes/ContentTypesRow/ComponentsAttributes/ComponentAttributeRow.js
  packages/strapi-admin/admin/src/components/Roles/Permissions/ContentTypes/ContentTypesRow/ComponentsAttributes/index.js
  packages/strapi-admin/admin/src/components/Roles/Permissions/ContentTypes/ContentTypesRow/ContentTypesAttributes/AttributeRow.js
  packages/strapi-admin/admin/src/components/Roles/Permissions/ContentTypes/ContentTypesRow/PermissionWrapper.js
  packages/strapi-admin/admin/src/components/Roles/Permissions/ContentTypes/ContentTypesRow/index.js
  packages/strapi-admin/admin/src/components/Roles/Permissions/ContentTypes/PermissionCheckbox.js
  packages/strapi-admin/admin/src/components/Roles/Permissions/ContentTypes/PermissionsHeader/index.js
  packages/strapi-admin/admin/src/components/Roles/Permissions/ContentTypes/index.js
  packages/strapi-admin/admin/src/components/Roles/Permissions/ContentTypes/useFillRequiredPermissions.js
  packages/strapi-admin/admin/src/components/Roles/Permissions/PluginsAndSettingsPermissions/PermissionRow/SubCategory/index.js
  packages/strapi-admin/admin/src/components/Roles/Permissions/PluginsAndSettingsPermissions/PermissionRow/index.js
  packages/strapi-admin/admin/src/components/Roles/Permissions/index.js
  packages/strapi-admin/admin/src/components/Roles/Permissions/init.js
  packages/strapi-admin/admin/src/components/Roles/Permissions/reducer.js
  packages/strapi-admin/admin/src/components/Roles/Permissions/tests/reducer.test.js
  packages/strapi-admin/admin/src/components/Roles/Permissions/utils/generateContentTypeActions.js
  packages/strapi-admin/admin/src/components/Roles/Permissions/utils/getAllAttributesActions.js
  packages/strapi-admin/admin/src/components/Roles/Permissions/utils/getAllAttributesActionsSize.js
  packages/strapi-admin/admin/src/components/Roles/Permissions/utils/getCreateActionsSizeByContentType.js
  packages/strapi-admin/admin/src/components/Roles/Permissions/utils/getNumberOfAttributes.js
  packages/strapi-admin/admin/src/components/Roles/Permissions/utils/index.js
  packages/strapi-admin/admin/src/components/Roles/Permissions/utils/isAttributeAction.js
  packages/strapi-admin/admin/src/components/Roles/Permissions/utils/isCreateAndRequired.js
  packages/strapi-admin/admin/src/components/Roles/Permissions/utils/permissonsConstantsActions.js
  packages/strapi-admin/admin/src/components/Roles/Permissions/utils/tests/generateContentTypeActions.test.js
  packages/strapi-admin/admin/src/components/Roles/Permissions/utils/tests/getAllAttributesActionsSizes.test.js
  packages/strapi-admin/admin/src/components/Roles/Permissions/utils/tests/getNumberOfAttributes.test.js
  packages/strapi-admin/admin/src/components/Roles/Permissions/utils/tests/isAttributeAction.test.js
  packages/strapi-admin/admin/src/components/Roles/Permissions/utils/tests/isCreateAndRequired.test.js
  packages/strapi-admin/admin/src/translations/en.json
  packages/strapi-admin/admin/src/utils/formatPermissionsFromApi.js
  packages/strapi-admin/admin/src/utils/formatPermissionsToApi.js
  packages/strapi-admin/admin/src/utils/getExistingActions.js
  packages/strapi-admin/admin/src/utils/tests/data.js
  packages/strapi-admin/admin/src/utils/tests/formatPermissionsFromApi.test.js
  packages/strapi-admin/admin/src/utils/tests/formatPermissionsToApi.test.js
  packages/strapi-admin/ee/admin/components/Roles/Permissions/ContentTypes/ContentTypesRow/ComponentsAttributes/ComponentAttributeRow.js
  packages/strapi-admin/ee/admin/components/Roles/Permissions/ContentTypes/ContentTypesRow/ContentTypesAttributes/AttributeRow.js
  packages/strapi-admin/ee/admin/components/Roles/Permissions/ContentTypes/ContentTypesRow/index.js
  packages/strapi-admin/ee/admin/components/Roles/Permissions/ContentTypes/PermissionsHeader/index.js
  packages/strapi-admin/ee/admin/components/Roles/Permissions/ContentTypes/useFillRequiredPermissions.js
  packages/strapi-admin/ee/admin/components/Roles/Permissions/PluginsAndSettingsPermissions/PermissionRow/SubCategory/index.js
  packages/strapi-admin/ee/admin/components/Roles/Permissions/reducer.js
  packages/strapi-admin/ee/admin/components/Roles/Permissions/tests/reducer.test.js
  packages/strapi-admin/ee/admin/containers/Roles/CreatePage/index.js
Labels: flag: don't merge, source: admin, type: bug

#8768 Fix migration when disabling dp on sqlite
  packages/strapi-connector-bookshelf/lib/build-database-schema.js
  packages/strapi-connector-bookshelf/lib/migrations/create-migration-runner.js
  packages/strapi-connector-bookshelf/lib/migrations/draft-publish-migration.js
  packages/strapi-database/test/migration-draft-publish.test.e2e.js
Labels: source: core:database, type: bug

#8803 [admin, translations] Translate documentation plugin and add German translations to index of upload plugin
  packages/strapi-plugin-documentation/admin/src/translations/de.json
  packages/strapi-plugin-upload/admin/src/translations/index.js
Labels: source: admin, type: translation

#8921 cwray-tech/update plugin descriptions
  packages/strapi-plugin-documentation/package.json
  packages/strapi-plugin-email/package.json
  packages/strapi-plugin-graphql/package.json
  packages/strapi-plugin-upload/package.json
Labels: source: core:framework, type: enhancement

#8939 Fix test migration draft & publish
  packages/strapi-database/test/migration-draft-publish.test.e2e.js
Labels: severity: low, source: core:tooling, type: bug

#8891 strapi-provider-email-mailgun: updates documentation
  packages/strapi-provider-email-mailgun/README.md
Labels: source: documentation, type: enhancement

#8937 Add telemetry on the relational field feature
  packages/strapi-plugin-content-manager/controllers/content-types.js
  packages/strapi-plugin-content-manager/services/__tests__/metrics.test.js
  packages/strapi-plugin-content-manager/services/metrics.js
  packages/strapi-utils/lib/__tests__/relations.test.js
  packages/strapi-utils/lib/relations.js
Labels: source: plugin:content-manager, type: enhancement

#8935 Fix inputs display
  packages/strapi-admin/package.json
  packages/strapi-helper-plugin/package.json
  packages/strapi-plugin-content-manager/admin/src/components/InputJSON/index.js
  packages/strapi-plugin-content-manager/admin/src/components/InputUID/index.js
  packages/strapi-plugin-content-manager/admin/src/containers/ListView/index.js
  packages/strapi-plugin-content-manager/package.json
  packages/strapi-plugin-content-type-builder/package.json
  packages/strapi-plugin-documentation/package.json
  packages/strapi-plugin-upload/package.json
  packages/strapi-plugin-users-permissions/package.json
  yarn.lock
Labels: source: plugin:content-manager, type: bug

#8974 Fix listview bug
  packages/strapi-plugin-content-manager/admin/src/components/CustomTable/Row/Cell.js
  packages/strapi-plugin-content-manager/admin/src/components/FilterPicker/index.js
  packages/strapi-plugin-content-manager/admin/src/containers/ListView/Filter.js
Labels: type: bug
