Repository strapi/strapi, pull requests merged in 2020-05, with the labels that each got.

#5991 Change search logic
  packages/strapi-connector-bookshelf/lib/buildDatabaseSchema.js
  packages/strapi-connector-bookshelf/lib/queries.js
  packages/strapi-connector-mongoose/lib/index.js
  packages/strapi-connector-mongoose/lib/queries.js
  packages/strapi-connector-mongoose/package.json
  packages/strapi-utils/lib/__tests__/stringFormatting.test.js
  packages/strapi-utils/lib/index.js
  packages/strapi-utils/lib/stringFormatting.js
  packages/strapi/__tests__/search.test.e2e.js
  yarn.lock
Labels: source: core:database, type: enhancement

#5874 Fix #5302 - Uninstall plugin: function to delete folder with files
  packages/strapi/lib/commands/uninstall.js
Labels: source: core:framework, type: bug

#6009 Prune obsolete files relations on startup
  packages/strapi-plugin-upload/config/functions/bootstrap.js
Labels: source: plugin:upload, type: bug

#5927 Chore/strapi database lifecycle
  docs/3.0.0-beta.x/concepts/models.md
  examples/getstarted/api/address/models/Address.js
  examples/getstarted/api/category/models/Category.js
  examples/getstarted/api/country/models/Country.js
  examples/getstarted/api/homepage/models/homepage.js
  examples/getstarted/api/like/models/Like.js
  examples/getstarted/api/menu/models/Menu.js
  examples/getstarted/api/menusection/models/Menusection.js
  examples/getstarted/api/restaurant/models/Restaurant.js
  examples/getstarted/api/review/models/Review.js
  packages/strapi-admin/models/Administrator.js
  packages/strapi-connector-bookshelf/lib/mount-models.js
  packages/strapi-connector-mongoose/lib/mount-models.js
  packages/strapi-database/lib/queries/__tests__/create-query.test.js
  packages/strapi-database/lib/queries/create-query.js
  packages/strapi-database/lib/utils/lifecycles.js
  packages/strapi-generate-api/templates/model.template
  packages/strapi-generate-model/templates/model.template
  packages/strapi-plugin-upload/models/File.js
  packages/strapi-plugin-users-permissions/models/Permission.js
  packages/strapi-plugin-users-permissions/models/Role.js
  packages/strapi-plugin-users-permissions/models/User.js
Labels: flag: 💥 Breaking change, source: core:database, type: bug

#6072 Only allow registeration with specific fields
  packages/strapi-plugin-users-permissions/controllers/Auth.js
Labels: source: plugin:users-permissions, type: bug

#6040 Changes the App Engine HOST variable to '0.0.0.0'
  docs/3.0.0-beta.x/deployment/google-app-engine.md
Labels: source: documentation, type: enhancement

#6039 docs: remove duplication in menu Guides/Count with GraphQL
  docs/.vuepress/config.js
Labels: source: documentation, type: enhancement

#6050 Heroku Error: self-signed certificate SSL fix
  docs/3.0.0-beta.x/deployment/heroku.md
Labels: source: documentation, type: enhancement

#6044 Preventing parse-type.test.js Date test from failure due to Time Zone differences
  packages/strapi-utils/lib/__tests__/parse-type.test.js
Labels: source: core:framework, type: enhancement

#6004 Prevent fall through in the model search method when a plugin is spec…
  packages/strapi-database/lib/database-manager.js
Labels: source: core:database, type: enhancement

#5981 Fix: Plugins docs syntax error
  docs/3.0.0-beta.x/plugins/documentation.md
Labels: source: documentation, type: enhancement

#5844 Remove Stack Overflow and Spectrum from project and use GH Discussions
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/DISCUSSION.md
  .github/ISSUE_TEMPLATE/config.yml
  CONTRIBUTING.md
  README.md
  docs/3.0.0-alpha.x/getting-started/quick-start-tutorial.md
  docs/3.0.0-alpha.x/getting-started/quick-start.md
  docs/3.0.0-beta.x/getting-started/quick-start-tutorial.md
  docs/3.0.0-beta.x/getting-started/quick-start.md
  docs/3.0.0-beta.x/getting-started/troubleshooting.md
  packages/strapi-admin/admin/src/assets/images/social_so.png
  packages/strapi-admin/admin/src/containers/HomePage/SocialLink.js
  packages/strapi-admin/admin/src/containers/HomePage/index.js
Labels: source: documentation, type: enhancement

#6078 Fix issue #5934
  packages/strapi-plugin-upload/services/__tests__/upload.test.js
  packages/strapi-plugin-upload/services/image-manipulation.js
  packages/strapi-plugin-upload/test/upload.test.e2e.js
Labels: source: plugin:upload, type: bug

#6079 Make password input optional while editing
  packages/strapi-admin/controllers/Admin.js
  packages/strapi-plugin-users-permissions/services/User.js
  packages/strapi/lib/middlewares/router/index.js
Labels: source: admin, type: bug

#5969 Improving IT translation by adding missing labels
  packages/strapi-admin/admin/src/translations/it.json
Labels: source: admin, type: enhancement

#6097 Check pluralize name in ctb
  packages/strapi-plugin-content-type-builder/controllers/validation/__tests__/content-type.test.js
  packages/strapi-plugin-content-type-builder/controllers/validation/content-type.js
Labels: source: plugin:content-type-builder, type: enhancement

#6047 Ignore private fields input on user register
  packages/strapi-plugin-users-permissions/config/schema.graphql.js
  packages/strapi-plugin-users-permissions/test/users-graphql.test.e2e.js
Labels: flag: 💥 Breaking change, source: plugin:graphql, type: bug

#5833 Fix/#4513/ability to use a sub path behind a proxy
  docs/3.0.0-alpha.x/guides/authentication.md
  docs/3.0.0-beta.x/concepts/configurations.md
  docs/3.0.0-beta.x/migration-guide/migration-guide-beta.17-to-beta.18.md
  docs/3.0.0-beta.x/migration-guide/migration-guide-beta.18-to-beta.19.md
  packages/strapi-connector-bookshelf/lib/knex.js
  packages/strapi-plugin-documentation/config/policies/index.js
  packages/strapi-plugin-documentation/controllers/Documentation.js
  packages/strapi-plugin-documentation/middlewares/documentation/index.js
  packages/strapi-plugin-documentation/public/index.html
  packages/strapi-plugin-documentation/public/login.html
  packages/strapi-plugin-graphql/hooks/graphql/index.js
  packages/strapi-plugin-users-permissions/admin/src/components/PopUpForm/index.js
  packages/strapi-plugin-users-permissions/config/functions/bootstrap.js
  packages/strapi-plugin-users-permissions/controllers/Auth.js
  packages/strapi-plugin-users-permissions/package.json
  packages/strapi-plugin-users-permissions/services/Providers.js
  packages/strapi-utils/lib/config.js
  packages/strapi-utils/lib/index.js
  packages/strapi-utils/lib/stringFormatting.js
  packages/strapi/lib/Strapi.js
  packages/strapi/lib/commands/build.js
  packages/strapi/lib/commands/uninstall.js
  packages/strapi/lib/commands/watchAdmin.js
  packages/strapi/lib/core/app-configuration/index.js
  packages/strapi/lib/core/bootstrap.js
  packages/strapi/lib/middlewares/public/index.js
  packages/strapi/lib/utils/addSlash.js
  packages/strapi/lib/utils/openBrowser.js
  yarn.lock
Labels: flag: 💥 Breaking change, source: core:framework, type: enhancement

#6086 [Docker] changed volume for Postgres
  docs/3.0.0-beta.x/installation/docker.md
Labels: source: documentation, type: enhancement

#6094 Fix typographical errors in Models concept of documentation
  docs/3.0.0-beta.x/concepts/models.md
Labels: source: documentation, type: enhancement

#5665 Fix typo
  docs/3.0.0-beta.x/concepts/policies.md
Labels: source: documentation, type: enhancement

#5730 google provider section modified
  docs/3.0.0-beta.x/plugins/users-permissions.md
Labels: source: documentation, type: enhancement

#6173 update server.url + remove server.admin.build
  docs/3.0.0-beta.x/concepts/configurations.md
Labels: source: documentation, type: enhancement

#6149 Upgrade dependency version
  packages/strapi-plugin-graphql/package.json
Labels: source: plugin:graphql, type: enhancement

#6174 Fixed link to deployment guide
  docs/3.0.0-beta.x/guides/databases.md
Labels: source: documentation, type: enhancement

#5783 fix vk providers
  packages/strapi-plugin-users-permissions/services/Providers.js
Labels: source: plugin:users-permissions, type: bug

#6171 Add Twitch auth provider
  packages/strapi-plugin-users-permissions/admin/src/components/PopUpForm/index.js
  packages/strapi-plugin-users-permissions/admin/src/translations/en.json
  packages/strapi-plugin-users-permissions/config/functions/bootstrap.js
  packages/strapi-plugin-users-permissions/services/Providers.js
Labels: source: plugin:users-permissions, type: enhancement

#6112 Configuration dump and restore cli
  docs/3.0.0-beta.x/cli/CLI.md
  packages/strapi/bin/strapi.js
  packages/strapi/lib/Strapi.js
  packages/strapi/lib/commands/configurationDump.js
  packages/strapi/lib/commands/configurationRestore.js
Labels: source: core:framework, type: feature request

#6199 User count
  packages/strapi-plugin-users-permissions/config/routes.json
  packages/strapi-plugin-users-permissions/controllers/User.js
  packages/strapi-plugin-users-permissions/services/User.js
Labels: source: plugin:users-permissions, type: enhancement

#5893 Clean up parameter and migration guide documentation and links
  README.md
  docs/3.0.0-beta.x/content-api/parameters.md
  docs/3.0.0-beta.x/migration-guide/README.md
Labels: source: documentation, type: enhancement

#6022 Update European Portuguese translations for strapi-admin
  packages/strapi-admin/admin/src/translations/pt.json
Labels: source: admin, type: enhancement

#6030 Add strapi rebuild after WYSIWYG plugin has been created and add npm/yarn commands alternatives
  docs/3.0.0-beta.x/guides/registering-a-field-in-admin.md
Labels: source: documentation, type: enhancement

#6032 Clean GraphQL plugin docs
  docs/3.0.0-beta.x/plugins/graphql.md
Labels: source: documentation, type: enhancement

#6052 Updated variables in email docs
  docs/3.0.0-beta.x/guides/send-email.md
Labels: source: documentation, type: enhancement

#6068 Update gcs file config in GAE deployment guide
  docs/3.0.0-beta.x/deployment/google-app-engine.md
Labels: source: documentation, type: enhancement

#6140 Fix broken link in Heroku deployment guide
  docs/3.0.0-beta.x/deployment/heroku.md
Labels: source: documentation, type: enhancement

#6180 Move to Github discussions for beta docs
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/DISCUSSION.md
  .github/ISSUE_TEMPLATE/config.yml
  CONTRIBUTING.md
  README.md
  docs/3.0.0-alpha.x/getting-started/quick-start-tutorial.md
  docs/3.0.0-alpha.x/getting-started/quick-start.md
  docs/3.0.0-beta.x/getting-started/quick-start-tutorial.md
  docs/3.0.0-beta.x/getting-started/quick-start.md
  docs/3.0.0-beta.x/getting-started/troubleshooting.md
  packages/strapi-admin/admin/src/assets/images/social_so.png
  packages/strapi-admin/admin/src/containers/HomePage/SocialLink.js
  packages/strapi-admin/admin/src/containers/HomePage/index.js
Labels: source: documentation, type: enhancement

#6134 Update Nginx proxy docs for new proxy changes
  docs/3.0.0-beta.x/deployment/nginx-proxy.md
Labels: source: documentation, type: enhancement

#6136 Add Caddy proxy documentation
  docs/3.0.0-beta.x/deployment/caddy-proxy.md
  docs/3.0.0-beta.x/getting-started/deployment.md
Labels: source: documentation, type: enhancement

#6150 Add HAProxy proxy documentation
  docs/3.0.0-beta.x/deployment/haproxy-proxy.md
  docs/3.0.0-beta.x/getting-started/deployment.md
Labels: source: documentation, type: enhancement

#6211 Update FAQ for Beta Docs
  docs/3.0.0-beta.x/getting-started/troubleshooting.md
Labels: source: documentation, type: enhancement

#6192 in register, response will only include jwt if email confirmation is false
  packages/strapi-plugin-users-permissions/controllers/Auth.js
Labels: source: plugin:users-permissions, type: bug

#6215 Update GCP host in beta docs
  docs/3.0.0-beta.x/deployment/google-app-engine.md
Labels: source: documentation, type: enhancement

#6210 Move email config in files
  docs/3.0.0-beta.x/migration-guide/migration-guide-beta.19-to-beta.20.md
  docs/3.0.0-beta.x/plugins/email.md
  examples/getstarted/.gitignore
  examples/getstarted/config/plugins.js
  packages/strapi-admin/controllers/Auth.js
  packages/strapi-plugin-email/config/functions/bootstrap.js
  packages/strapi-plugin-email/config/routes.json
  packages/strapi-plugin-email/config/settings.js
  packages/strapi-plugin-email/controllers/Email.js
  packages/strapi-plugin-email/documentation/1.0.0/overrides/email-Email.json
  packages/strapi-plugin-email/services/Email.js
  packages/strapi-provider-email-amazon-ses/README.md
  packages/strapi-provider-email-amazon-ses/lib/index.js
  packages/strapi-provider-email-amazon-ses/package.json
  packages/strapi-provider-email-mailgun/README.md
  packages/strapi-provider-email-mailgun/lib/index.js
  packages/strapi-provider-email-mailgun/package.json
  packages/strapi-provider-email-sendgrid/README.md
  packages/strapi-provider-email-sendgrid/lib/index.js
  packages/strapi-provider-email-sendgrid/package.json
  packages/strapi-provider-email-sendmail/README.md
  packages/strapi-provider-email-sendmail/lib/index.js
  packages/strapi-provider-email-sendmail/package.json
  packages/strapi-utils/lib/index.js
  packages/strapi-utils/lib/objectFormatting.js
  yarn.lock
Labels: flag: 💥 Breaking change, source: plugin:email, type: enhancement

#6124 Prevent user registration with confirmed status
  packages/strapi-plugin-users-permissions/controllers/Auth.js
Labels: source: plugin:users-permissions, type: bug

#6012 Fix url encoding for local upload provider
  packages/strapi-plugin-upload/package.json
  packages/strapi-plugin-upload/services/Upload.js
  packages/strapi-plugin-upload/services/__tests__/upload.test.js
  packages/strapi-utils/lib/stringFormatting.js
  yarn.lock
Labels: source: plugin:upload, type: bug

#6291 Fix ctb react-select ui
  packages/strapi-plugin-content-type-builder/admin/src/components/ComponentSelect/MultipleMenuList.js
Labels: source: plugin:content-type-builder, type: bug

#6293 Fix global policies case sensitive
  packages/strapi/lib/core/load-policies.js
Labels: source: core:framework, type: bug

#6321 Change the logo
  packages/strapi-admin/admin/src/assets/images/logo-strapi.png
  packages/strapi-admin/admin/src/assets/images/logo_strapi.png
  packages/strapi-admin/admin/src/components/LeftMenuFooter/Wrapper.js
  packages/strapi-admin/admin/src/components/PageTitle/index.js
  packages/strapi-admin/admin/src/favicon.ico
  packages/strapi-admin/admin/src/favicon.png
Labels: source: admin, type: enhancement

#6338 Clarified upload proxy error messages
  packages/strapi-plugin-upload/controllers/proxy.js
Labels: source: plugin:upload, type: enhancement

#6315 Add JWT configurations
  docs/3.0.0-beta.x/plugins/users-permissions.md
  packages/strapi-plugin-users-permissions/config/security.json
  packages/strapi-plugin-users-permissions/services/Jwt.js
Labels: source: plugin:users-permissions, type: enhancement

#6313 Fix typo
  docs/3.0.0-beta.x/migration-guide/migration-guide-beta.19-to-beta.20.md
Labels: source: documentation, type: enhancement

#6226 Add missing comma
  docs/3.0.0-beta.x/guides/send-email.md
Labels: source: documentation, type: enhancement

#5655 Fix #5653: improve UserPermissions - password mutations
  docs/3.0.0-beta.x/plugins/users-permissions.md
  packages/strapi-admin/config/routes.json
  packages/strapi-admin/controllers/Auth.js
  packages/strapi-plugin-users-permissions/config/routes.json
  packages/strapi-plugin-users-permissions/config/schema.graphql.js
  packages/strapi-plugin-users-permissions/controllers/Auth.js
Labels: flag: 💥 Breaking change, source: plugin:graphql, source: plugin:users-permissions, type: enhancement

#6340 Upload proxy - Using Header objects build-in entries function
  packages/strapi-plugin-upload/controllers/proxy.js
Labels: source: plugin:upload, type: bug

#6003 Sanitize user object in user plugin update method return value
  packages/strapi-plugin-users-permissions/controllers/User.js
Labels: source: plugin:users-permissions, type: bug

#6055 fixes #5984
  packages/strapi-helper-plugin/lib/src/utils/generateSearchFromFilters.js
  packages/strapi-helper-plugin/lib/src/utils/tests/generateSearchFromFilters.test.js
  packages/strapi-plugin-upload/admin/src/containers/HomePage/index.js
Labels: source: plugin:content-manager, source: plugin:upload, type: bug

#6257 Erroneous double quote syntax error
  docs/3.0.0-beta.x/plugins/documentation.md
Labels: source: documentation, type: enhancement

#6345 Remove help link
  packages/strapi-admin/admin/src/components/StaticLinks/index.js
Labels: source: admin

#6331 Adding private field support to UID #6204
  packages/strapi-plugin-content-type-builder/admin/src/containers/FormModal/utils/forms.js
Labels: source: plugin:content-type-builder, type: enhancement

#6354 Chore/fix front issues
  packages/strapi-helper-plugin/lib/src/svgs/Layout/index.js
  packages/strapi-plugin-content-manager/admin/src/components/SelectWrapper/index.js
  packages/strapi-plugin-content-type-builder/admin/src/containers/ListView/index.js
  packages/strapi-plugin-documentation/admin/src/containers/HomePage/index.js
Labels: source: admin, type: bug

#6353 Move header logo to the left
  packages/strapi-admin/admin/src/components/LeftMenuHeader/Wrapper.js
Labels: source: admin, type: enhancement

#6358 Fix mongo error trying to cast from empty array
  packages/strapi-connector-mongoose/lib/relations.js
Labels: source: core:database, type: bug

#6373 Fixes #1766
  packages/strapi-admin/admin/src/containers/HomePage/hooks.js
Labels: source: admin, type: bug

#6375 Fix multiple doc links to v3
  CONTRIBUTING.md
  README.md
  packages/strapi-admin/admin/src/components/EmptyList/index.js
  packages/strapi-admin/admin/src/containers/HomePage/index.js
  packages/strapi-generate-api/templates/controller.template
  packages/strapi-generate-api/templates/model.template
  packages/strapi-generate-api/templates/service.template
  packages/strapi-generate-model/templates/model.template
  packages/strapi-generate-new/lib/resources/files/config/functions/bootstrap.js
  packages/strapi-generate-new/lib/resources/files/config/functions/cron.js
  packages/strapi-plugin-documentation/config/settings.json
  packages/strapi-provider-upload-local/README.md
  packages/strapi/lib/services/metrics/index.js
Labels: source: documentation, type: enhancement

#6387 Fix language middleware
  packages/strapi/lib/middlewares/language/index.js
Labels: source: core:framework, type: bug

#6390 Typofix in GraphQL User permissions payload
  packages/strapi-plugin-users-permissions/config/schema.graphql.js
Labels: source: plugin:graphql, type: enhancement

#6404 Fix snapshots
  packages/strapi-admin/admin/src/containers/Webhooks/ListView/tests/__snapshots__/index.test.js.snap
Labels: source: admin, type: bug

#6391 openbrowser on localhost instead of 0.0.0.0
  packages/strapi-utils/lib/config.js
  packages/strapi-utils/lib/index.js
  packages/strapi/lib/Strapi.js
  packages/strapi/lib/utils/openBrowser.js
Labels: source: core:framework, type: bug

#6405 Fix/watch admin
  packages/strapi-utils/lib/config.js
  packages/strapi/lib/commands/watchAdmin.js
Labels: source: core:framework, type: bug

#6128 Updates pt-BR locale
  packages/strapi-admin/admin/src/translations/pt-BR.json
Labels: source: admin, type: enhancement

#6378 Fix #6377 ses email sending, pass required message key
  packages/strapi-provider-email-amazon-ses/lib/index.js
Labels: source: plugin:email, type: bug

#6376 Fix 3.x documentation at plugins/upload
  docs/v3.x/plugins/upload.md
Labels: source: documentation, type: enhancement

#6362 Update configurations.md
  docs/v3.x/concepts/configurations.md
Labels: source: documentation, type: enhancement

#6381 Update Security doc to reference the stable release
  SECURITY.md
Labels: source: documentation, type: enhancement

#6419 Fix cron should check for server.cron.enabled option to work
  packages/strapi/lib/middlewares/cron/defaults.json
  packages/strapi/lib/middlewares/cron/index.js
  packages/strapi/lib/middlewares/index.js
Labels: source: core:framework, type: bug

#6367 Fix links that point to old documentation
  README.md
  examples/getstarted/api/address/controllers/Address.js
  examples/getstarted/api/address/services/Address.js
  examples/getstarted/api/category/controllers/Category.js
  examples/getstarted/api/category/services/Category.js
  examples/getstarted/api/country/controllers/Country.js
  examples/getstarted/api/country/services/Country.js
  examples/getstarted/api/homepage/controllers/homepage.js
  examples/getstarted/api/homepage/services/homepage.js
  examples/getstarted/api/like/controllers/Like.js
  examples/getstarted/api/like/services/Like.js
  examples/getstarted/api/menu/controllers/Menu.js
  examples/getstarted/api/menu/services/Menu.js
  examples/getstarted/api/menusection/controllers/Menusection.js
  examples/getstarted/api/menusection/services/Menusection.js
  examples/getstarted/api/restaurant/controllers/Restaurant.js
  examples/getstarted/api/restaurant/services/Restaurant.js
  examples/getstarted/api/review/controllers/Review.js
  examples/getstarted/api/review/services/Review.js
Labels: source: documentation, type: enhancement

#6380 Fix strapi blog url
  docs/.vuepress/config.js
  docs/3.0.0-beta.x/getting-started/quick-start-tutorial.md
  docs/3.0.0-beta.x/getting-started/quick-start.md
  docs/v3.x/getting-started/quick-start-tutorial.md
  docs/v3.x/getting-started/quick-start.md
  packages/strapi-admin/admin/src/containers/HomePage/BlogPost.js
  packages/strapi-admin/admin/src/containers/HomePage/index.js
Labels: source: documentation, type: enhancement

#6350 Fix database link and example
  examples/getstarted/README.md
Labels: source: documentation, type: enhancement

#6417 Fix lifecycle hooks URL
  packages/strapi-generate-api/templates/model.template
Labels: source: core:framework, type: enhancement

#6430 Load sentry as first middleware
  docs/v3.x/guides/error-catching.md
Labels: source: documentation, type: enhancement

#6346 Fix missing validation error message on media field
  packages/strapi-plugin-upload/admin/src/components/InputMedia/ErrorMessage.js
  packages/strapi-plugin-upload/admin/src/components/InputMedia/Wrapper.js
  packages/strapi-plugin-upload/admin/src/components/InputMedia/index.js
Labels: source: plugin:upload, type: enhancement

#6396 fix some typos in configurations documentation
  docs/v3.x/concepts/configurations.md
Labels: source: documentation, type: enhancement

#6397 fix link
  docs/v3.x/migration-guide/migration-guide-beta.20-to-3.0.0.md
Labels: source: documentation, type: enhancement

#6400 Editing grammar.
  docs/v3.x/guides/is-owner.md
Labels: source: documentation, type: enhancement

#6427 Fix typos in stable migration guide
  docs/v3.x/migration-guide/migration-guide-beta.20-to-3.0.0.md
Labels: source: documentation, type: enhancement

#6422 Update RU translation for strapi-admin
  packages/strapi-admin/admin/src/translations/ru.json
Labels: source: admin, type: enhancement

#6379 Fixed dutch typos
  packages/strapi-plugin-content-type-builder/admin/src/translations/nl.json
Labels: source: plugin:content-type-builder, type: enhancement

#6436 Update digital Ocean One Click doc
  docs/v3.x/installation/digitalocean-one-click.md
Labels: source: documentation, type: enhancement
