Repository strapi/strapi, pull requests merged in 2020-02, with the labels that each got.

#5173 Add warning messages to Alpha docs
  docs/3.0.0-alpha.x/getting-started/introduction.md
  docs/3.0.0-alpha.x/getting-started/quick-start-tutorial.md
  docs/3.0.0-alpha.x/getting-started/quick-start.md
Labels: pr: 💅 Enhancement, source: Documentation

#5154 Remove empty code block from beta.18 migration guide
  docs/3.0.0-beta.x/migration-guide/migration-guide-beta.17-to-beta.18.md
Labels: pr: 💅 Enhancement, source: Documentation

#5142 Fixed misspelled word restaurant
  docs/3.0.0-beta.x/content-api/parameters.md
Labels: pr: 💅 Enhancement, source: Documentation

#5187 Update quick guide to reflect correct button names
  docs/3.0.0-beta.x/getting-started/quick-start.md
Labels: pr: 💅 Enhancement, source: Documentation

#5181 Remove queries section in local plugin docs
  docs/3.0.0-beta.x/plugin-development/backend-development.md
Labels: pr: 💅 Enhancement, source: Documentation

#5063 Updated PL translations
  packages/strapi-admin/admin/src/translations/pl.json
  packages/strapi-plugin-content-manager/admin/src/translations/pl.json
  packages/strapi-plugin-content-type-builder/admin/src/translations/pl.json
  packages/strapi-plugin-documentation/admin/src/translations/pl.json
  packages/strapi-plugin-email/admin/src/translations/pl.json
  packages/strapi-plugin-upload/admin/src/translations/pl.json
  packages/strapi-plugin-users-permissions/admin/src/translations/pl.json
Labels: pr: 💅 Enhancement, source: Admin

#5172 Updated zh-Hans translations
  packages/strapi-admin/admin/src/translations/zh-Hans.json
  packages/strapi-plugin-content-manager/admin/src/translations/zh-Hans.json
  packages/strapi-plugin-content-type-builder/admin/src/translations/zh-Hans.json
  packages/strapi-plugin-documentation/admin/src/translations/zh-Hans.json
  packages/strapi-plugin-email/admin/src/translations/zh-Hans.json
  packages/strapi-plugin-upload/admin/src/translations/zh-Hans.json
  packages/strapi-plugin-users-permissions/admin/src/translations/zh-Hans.json
Labels: pr: 💅 Enhancement, source: Admin

#5191 Match provider when logging in, to make sure the right user is found
  packages/strapi-plugin-users-permissions/controllers/Auth.js
Labels: pr: 🐛 Bug fix, source: Plugin

#5079 Create realted_col for self referencing many ways
  packages/strapi-connector-bookshelf/lib/buildDatabaseSchema.js
  packages/strapi-connector-bookshelf/lib/mount-models.js
Labels: pr: 🐛 Bug fix, source: Framework

#5217 Expose mongoose connections
  packages/strapi-connector-mongoose/lib/index.js
Labels: pr: 💅 Enhancement, source: Framework

#5208 Fix typos in third party client doc
  docs/3.0.0-beta.x/guides/client.md
Labels: pr: 💅 Enhancement, source: Documentation

#5021 Add plugin development doc
  docs/3.0.0-beta.x/plugin-development/frontend-development.md
Labels: pr: 💅 Enhancement, source: Documentation

#5205 Grammar + corrections of the three first sections
  docs/3.0.0-beta.x/concepts/configurations.md
  docs/3.0.0-beta.x/concepts/controllers.md
  docs/3.0.0-beta.x/concepts/customization.md
  docs/3.0.0-beta.x/concepts/file-structure.md
  docs/3.0.0-beta.x/concepts/hooks.md
  docs/3.0.0-beta.x/concepts/logging.md
  docs/3.0.0-beta.x/concepts/middlewares.md
  docs/3.0.0-beta.x/concepts/models.md
  docs/3.0.0-beta.x/concepts/parameters.md
  docs/3.0.0-beta.x/concepts/plugins.md
  docs/3.0.0-beta.x/concepts/policies.md
  docs/3.0.0-beta.x/concepts/public-assets.md
  docs/3.0.0-beta.x/concepts/routing.md
  docs/3.0.0-beta.x/concepts/services.md
  docs/3.0.0-beta.x/concepts/webhooks.md
  docs/3.0.0-beta.x/content-api/api-endpoints.md
  docs/3.0.0-beta.x/content-api/parameters.md
  docs/3.0.0-beta.x/getting-started/install-requirements.md
  docs/3.0.0-beta.x/getting-started/quick-start-tutorial.md
  docs/3.0.0-beta.x/getting-started/quick-start.md
  yarn.lock
Labels: pr: 💅 Enhancement, source: Documentation

#5235 admin watcher improvement
  packages/strapi-admin/index.js
Labels: pr: 🐛 Bug fix, source: admin

#5251 Update RU translations
  packages/strapi-admin/admin/src/translations/ru.json
Labels: pr: 💅 Enhancement, source: admin

#5276 Delete labels from the PR body
  .github/PULL_REQUEST_TEMPLATE.md
Labels: source: documentation, type: enhancement

#5252 Fix hardcoded styles
  packages/strapi-admin/admin/src/components/LeftMenuHeader/Wrapper.js
  packages/strapi-admin/admin/src/components/LeftMenuLinkContainer/Wrapper.js
Labels: source: admin, type: enhancement

#5273 Add guide for isOwner policy
  docs/.vuepress/config.js
  docs/3.0.0-beta.x/guides/is-owner.md
Labels: source: documentation, type: enhancement

#5308 Added information about body and files to request docs
  docs/3.0.0-beta.x/concepts/requests-responses.md
Labels: source: documentation, type: enhancement

#5242 fix(plugin-upload): size limit comparison issue
  packages/strapi-plugin-upload/controllers/Upload.js
  packages/strapi-plugin-upload/services/Upload.js
Labels: source: plugin:upload

#5320 Update docs about Extending a Model Service
  docs/3.0.0-beta.x/concepts/services.md
Labels: source: documentation, type: enhancement

#5294 edited some minor typos
  docs/3.0.0-beta.x/cli/CLI.md
Labels: source: documentation, type: enhancement

#5341 Fix polymorphic relations in the content manager
  packages/strapi-plugin-content-manager/admin/src/components/SelectWrapper/index.js
Labels: source: plugin:content-manager, type: bug

#5345 Add validations for duplicate enums
  packages/strapi-plugin-content-manager/admin/src/components/InputUID/Options/index.js
  packages/strapi-plugin-content-type-builder/admin/src/containers/FormModal/utils/forms.js
  packages/strapi-plugin-content-type-builder/admin/src/translations/en.json
  packages/strapi-plugin-content-type-builder/controllers/validation/common.js
  packages/strapi-plugin-content-type-builder/controllers/validation/types.js
Labels: source: plugin:content-type-builder, type: bug

#5346 Update div wrapper for SelectWrapper
  packages/strapi-plugin-content-manager/admin/src/components/Inputs/index.js
Labels: source: admin, type: bug

#5340 Fixes #5053
  packages/strapi-plugin-content-manager/admin/src/components/Inputs/index.js
Labels: source: plugin:content-manager, type: enhancement
