Repository strapi/strapi, pull requests merged in 2020-11, with the labels that each got.

#8534 Improve spanish locale
  packages/strapi-admin/admin/src/translations/es.json
  packages/strapi-plugin-content-manager/admin/src/translations/es.json
  packages/strapi-plugin-content-type-builder/admin/src/translations/es.json
  packages/strapi-plugin-documentation/admin/src/translations/es.json
  packages/strapi-plugin-upload/admin/src/translations/es.json
  packages/strapi-plugin-upload/admin/src/translations/index.js
  packages/strapi-plugin-users-permissions/admin/src/translations/es.json
Labels: type: translation

#8404 Update IT translations
  packages/strapi-admin/admin/src/translations/it.json
Labels: type: translation

#8461 Upgrade graphql-tools package to use GraphQL v15
  packages/strapi-plugin-graphql/package.json
Labels: source: plugin:graphql, type: bug

#8373 Added timezone for cron jobs
  docs/v3.x/concepts/configurations.md
  docs/v3.x/guides/scheduled-publication.md
  packages/strapi/lib/middlewares/cron/index.js
Labels: hacktoberfest-accepted

#8546 typo fix in the redirect url
  docs/v3.x/admin-panel/deploy.md
Labels: source: documentation, type: enhancement

#8526 add notification to update
  docs/v3.x/concepts/configurations.md
  examples/getstarted/.gitignore
  packages/strapi-utils/lib/__tests__/env-helper.test.js
  packages/strapi-utils/lib/env-helper.js
  packages/strapi-utils/lib/index.js
  packages/strapi/lib/Strapi.js
  packages/strapi/lib/core/app-configuration/config-loader.js
  packages/strapi/lib/utils/update-notifier/index.js
  packages/strapi/package.json
  yarn.lock
Labels: source: core:framework, type: enhancement

#8459 Maintain strapi-provider-email-nodemailer
  packages/strapi-provider-email-nodemailer/LICENSE
  packages/strapi-provider-email-nodemailer/README.md
  packages/strapi-provider-email-nodemailer/lib/index.js
  packages/strapi-provider-email-nodemailer/package.json
  yarn.lock
Labels: flag: don't merge

#8366 fix: #8342 ignore dynamic zone component if its not in data
  packages/strapi-connector-mongoose/lib/mount-models.js
Labels: source: core:database, type: bug

#8410 Allow deleting file that is already deleted in Cloudinary
  packages/strapi-provider-upload-cloudinary/lib/index.js
Labels: source: plugin:upload, type: enhancement

#8613 Documentation: update notifications + "Application" section in admin panel
  docs/v3.x/guides/update-version.md
Labels: source: documentation

#8587 Update Heroku guide to set NODE_ENV to production
  docs/v3.x/deployment/heroku.md
Labels: severity: high, source: documentation

#8615 Fix write access error of the update-notifier
  packages/strapi/lib/utils/update-notifier/index.js
Labels: source: core:framework, type: bug

#8658 Sanitize /upload/search/:q route
  packages/strapi-plugin-upload/controllers/Upload.js
Labels: source: plugin:upload, type: security

#8661 Make the beta docs more clear, depreciated notice
  docs/.vuepress/theme/components/Navbar.vue
Labels: source: documentation, type: enhancement

#8679 Fixed click event on non-repeatable empty component
  packages/strapi-plugin-content-manager/admin/src/components/ComponentInitializer/index.js
Labels: source: plugin:content-manager, type: bug

#7987 Added Categories selector for dynamic zone
  packages/strapi-plugin-content-manager/admin/src/components/DynamicComponentCard/Wrapper.js
  packages/strapi-plugin-content-manager/admin/src/components/DynamicZone/Banner.js
  packages/strapi-plugin-content-manager/admin/src/components/DynamicZone/BannerWrapper.js
  packages/strapi-plugin-content-manager/admin/src/components/DynamicZone/CategoryItem.js
  packages/strapi-plugin-content-manager/admin/src/components/DynamicZone/ComponentsList.js
  packages/strapi-plugin-content-manager/admin/src/components/DynamicZone/ComponentsPicker.js
  packages/strapi-plugin-content-manager/admin/src/components/DynamicZone/index.js
Labels: source: plugin:content-manager

#8686 Make upload parser middleware example more clear
  docs/v3.x/plugins/upload.md
Labels: source: documentation, type: enhancement

#8711 fixed admin-tutorial broken link in heroku-deployment
  docs/v3.x/deployment/heroku.md
Labels: source: documentation

#8724 Update docs FAQ with component filtering
  docs/v3.x/getting-started/troubleshooting.md
Labels: source: documentation

#8625 Translations Update: Adds & Improves German Translations
  CONTRIBUTING.md
  packages/strapi-plugin-content-manager/admin/src/translations/de.json
  packages/strapi-plugin-content-type-builder/admin/src/translations/de.json
  packages/strapi-plugin-upload/admin/src/translations/de.json
Labels: type: translation

#8707 Update gitignore in example and in generate-new
  examples/getstarted/.gitignore
  packages/strapi-generate-new/lib/resources/dot-files/gitignore
Labels: source: core:cli, type: bug

#8388 fix(docs): Remove unreachable code
  docs/v3.x/guides/jwt-validation.md
Labels: source: documentation, type: enhancement

#8531 Restaurant spelled right
  docs/3.0.0-beta.x/guides/count-graphql.md
  docs/v3.x/guides/count-graphql.md
Labels: source: documentation, type: enhancement

#8723 Add support for columnType in Mongoose
  packages/strapi-connector-mongoose/lib/utils/index.js
Labels: source: core:database, type: enhancement

#8384 Add indonesian translations
  packages/strapi-generate-plugin/files/admin/src/translations/id.json
  packages/strapi-generate-plugin/files/admin/src/translations/index.js
  packages/strapi-plugin-content-manager/admin/src/translations/id.json
  packages/strapi-plugin-content-manager/admin/src/translations/index.js
  packages/strapi-plugin-content-type-builder/admin/src/translations/id.json
  packages/strapi-plugin-content-type-builder/admin/src/translations/index.js
  packages/strapi-plugin-documentation/admin/src/translations/id.json
  packages/strapi-plugin-documentation/admin/src/translations/index.js
  packages/strapi-plugin-email/admin/src/translations/id.json
  packages/strapi-plugin-email/admin/src/translations/index.js
Labels: source: admin, type: translation
