Repository strapi/strapi, pull requests merged in 2020-08, with the labels that each got.

#7280 Upload path can be absolute
  packages/strapi-plugin-upload/controllers/upload/admin.js
  packages/strapi-plugin-upload/middlewares/upload/index.js
  packages/strapi-provider-upload-local/lib/index.js
Labels: source: plugin:upload, type: bug

#7263 Gender Equality
  packages/strapi-admin/admin/src/containers/Users/EditPage/index.js
  packages/strapi-admin/admin/src/translations/en.json
Labels: source: admin, type: enhancement

#7303 Add conf proxy koa variable
  docs/v3.x/concepts/configurations.md
  packages/strapi/lib/Strapi.js
  packages/strapi/lib/core/app-configuration/index.js
Labels: source: core:framework, type: bug

#7144 Add events for the rbac feature.
  packages/strapi-admin/admin/src/containers/Admin/index.js
  packages/strapi-admin/admin/src/containers/Roles/EditPage/index.js
  packages/strapi-admin/admin/src/containers/Roles/ListPage/index.js
  packages/strapi-admin/ee/admin/containers/Roles/CreatePage/index.js
  packages/strapi-admin/webpack.config.js
Labels: source: admin, type: enhancement

#7299 Add events for user creation
  packages/strapi-admin/services/__tests__/metrics.test.js
  packages/strapi-admin/services/__tests__/role.test.js
  packages/strapi-admin/services/__tests__/user.test.js
  packages/strapi-admin/services/metrics.js
  packages/strapi-admin/services/role.js
  packages/strapi-admin/services/user.js
  packages/strapi/lib/services/metrics/__tests__/index.test.js
  packages/strapi/lib/services/metrics/sender.js
Labels: source: admin, type: enhancement

#7300 Remove session options from docs that no longer work
  docs/v3.x/concepts/middlewares.md
Labels: source: documentation, type: enhancement

#7132 Fix/login providers
  docs/v3.x/plugins/users-permissions.md
  packages/strapi-plugin-users-permissions/admin/src/components/PopUpForm/index.js
  packages/strapi-plugin-users-permissions/admin/src/translations/ar.json
  packages/strapi-plugin-users-permissions/admin/src/translations/cs.json
  packages/strapi-plugin-users-permissions/admin/src/translations/de.json
  packages/strapi-plugin-users-permissions/admin/src/translations/en.json
  packages/strapi-plugin-users-permissions/admin/src/translations/es.json
  packages/strapi-plugin-users-permissions/admin/src/translations/fr.json
  packages/strapi-plugin-users-permissions/admin/src/translations/it.json
  packages/strapi-plugin-users-permissions/admin/src/translations/ja.json
  packages/strapi-plugin-users-permissions/admin/src/translations/ko.json
  packages/strapi-plugin-users-permissions/admin/src/translations/ms.json
  packages/strapi-plugin-users-permissions/admin/src/translations/nl.json
  packages/strapi-plugin-users-permissions/admin/src/translations/pl.json
  packages/strapi-plugin-users-permissions/admin/src/translations/pt-BR.json
  packages/strapi-plugin-users-permissions/admin/src/translations/pt.json
  packages/strapi-plugin-users-permissions/admin/src/translations/ru.json
  packages/strapi-plugin-users-permissions/admin/src/translations/sk.json
  packages/strapi-plugin-users-permissions/admin/src/translations/tr.json
  packages/strapi-plugin-users-permissions/admin/src/translations/uk.json
  packages/strapi-plugin-users-permissions/admin/src/translations/vi.json
  packages/strapi-plugin-users-permissions/admin/src/translations/zh-Hans.json
  packages/strapi-plugin-users-permissions/admin/src/translations/zh.json
  packages/strapi-plugin-users-permissions/controllers/Auth.js
  packages/strapi-plugin-users-permissions/controllers/UsersPermissions.js
  packages/strapi-plugin-users-permissions/package.json
  packages/strapi-plugin-users-permissions/services/Providers.js
  yarn.lock
Labels: source: documentation, source: plugin:users-permissions, type: enhancement

#7350 Fix sanitizeEntity's includeFields usage
  packages/strapi-utils/lib/sanitize-entity.js
Labels: source: core:framework, type: bug

#7341 Email plugin docs fix typo
  docs/v3.x/plugins/email.md
Labels: source: documentation, type: enhancement

#7342 Fix custom admin guide typo
  docs/v3.x/guides/custom-admin.md
Labels: source: documentation, type: enhancement

#7363 fix(graphql): filter out orphaned relationships
  packages/strapi-plugin-graphql/services/build-aggregation.js
Labels: source: plugin:graphql, type: enhancement

#7356 Fix docs for loading ORM plugins
  docs/v3.x/concepts/configurations.md
Labels: source: documentation, type: enhancement

#7344 Change CORS documentation on origin
  docs/v3.x/concepts/middlewares.md
Labels: source: documentation, type: enhancement

#7372 fixed strapi/strapi#7334 add the data-loader for admin users to the graphql plugin
  packages/strapi-plugin-graphql/services/data-loaders.js
  packages/strapi-plugin-graphql/test/graphqlCrud.test.e2e.js
Labels: source: plugin:graphql, type: bug

#7373 Fix strapi-provider-upload-local readme
  packages/strapi-provider-upload-local/README.md
Labels: source: documentation, type: enhancement

#7368 FIX: Broken links to email configurations & middlewares
  docs/v3.x/concepts/configurations.md
Labels: source: documentation, type: enhancement

#7394 Fix favicon link in docs
  docs/.vuepress/config.js
Labels: source: documentation, type: enhancement

#7378 Fix typo in upload plugin documentation
  docs/3.0.0-beta.x/plugins/upload.md
Labels: source: documentation, type: enhancement

#7400 Fix virtual mongoose remove _v char
  packages/strapi-connector-mongoose/lib/mount-models.js
Labels: source: core:database, type: bug

#7418 Docs update on migration guide for username constraint
  docs/v3.x/migration-guide/migration-guide-3.0.x-to-3.1.x.md
Labels: source: documentation, type: enhancement

#7425 Fix custom mongoose query .toObject() is undefined
  docs/v3.x/concepts/queries.md
Labels: source: documentation, type: enhancement

#7416 Fixes #7414
  packages/strapi-plugin-content-manager/admin/src/containers/EditViewDataManagerProvider/index.js
Labels: source: plugin:content-manager, type: bug

#7388 Show error.message || error on failed command
  packages/strapi/bin/strapi.js
Labels: source: core:cli, type: enhancement

#7370 Fix WYSIWYG bugs
  packages/strapi-plugin-content-manager/admin/src/components/Wysiwyg/constants.js
  packages/strapi-plugin-content-manager/admin/src/components/Wysiwyg/helpers.js
  packages/strapi-plugin-content-manager/admin/src/components/Wysiwyg/index.js
Labels: source: plugin:content-manager, type: bug

#7337 Fix/6641
  packages/strapi-helper-plugin/lib/src/components/HeaderSearch/index.js
  packages/strapi-plugin-upload/admin/src/containers/HomePage/HomePageContent/HomePageSettings.js
Labels: source: plugin:upload, type: bug

#7375 Added pt-BR localization to strapi-plugin-upload
  packages/strapi-plugin-upload/admin/src/translations/index.js
  packages/strapi-plugin-upload/admin/src/translations/pt-BR.json
Labels: source: plugin:upload, type: enhancement

#7291 Fixes link to AWS Free landing page
  docs/v3.x/deployment/amazon-aws.md
Labels: source: documentation, type: enhancement

#7274 Fixing typo in translations/en.json.
  packages/strapi-admin/admin/src/translations/en.json
Labels: source: admin, type: enhancement

#6922 Improve empty state grammar for Assets
  packages/strapi-plugin-upload/admin/src/translations/en.json
Labels: source: plugin:upload, type: enhancement

#7312 Fixes #7301
  packages/strapi-plugin-content-type-builder/admin/src/containers/ListView/index.js
Labels: source: plugin:content-type-builder, type: bug

#7109 Chore/ml delete assets
  packages/strapi-plugin-upload/admin/src/containers/HomePage/HomePageContent/HomePageSettings.js
  packages/strapi-plugin-upload/admin/src/containers/HomePage/HomePageContent/index.js
  packages/strapi-plugin-upload/admin/src/containers/HomePage/index.js
  packages/strapi-plugin-upload/admin/src/containers/HomePage/reducer.js
  packages/strapi-plugin-upload/admin/src/containers/ModalStepper/index.js
Labels: source: plugin:upload, type: enhancement

#7383 Add missing and improve existing German translations
  packages/strapi-admin/admin/src/translations/de.json
Labels: source: admin, type: enhancement

#7413 Updating email documentation adding a tip during initial setup to avo…
  docs/v3.x/plugins/email.md
Labels: source: documentation, type: enhancement

#6858 Formatting enhancements and Fixes
  docs/3.0.0-beta.x/deployment/digitalocean.md
  docs/3.0.0-beta.x/deployment/heroku.md
  docs/3.0.0-beta.x/plugin-development/frontend-development.md
  docs/v3.x/deployment/digitalocean.md
  docs/v3.x/deployment/heroku.md
  docs/v3.x/plugin-development/frontend-development.md
Labels: source: documentation, type: enhancement

#6769 fixes #6725
  packages/strapi/lib/core/load-plugins.js
Labels: source: core:framework, type: bug

#7161 Fix #7141 - Wrong conversion of to a boolean value
  packages/strapi-admin/admin/src/components/Webhooks/Inputs/index.js
  packages/strapi-plugin-content-manager/admin/src/components/InputJSONWithErrors/index.js
  packages/strapi-plugin-content-manager/admin/src/components/InputUID/index.js
  packages/strapi-plugin-content-manager/admin/src/components/WysiwygWithErrors/index.js
Labels: source: admin, type: bug

#7408 Update FAQ with latest RBAC information
  docs/v3.x/getting-started/troubleshooting.md
Labels: source: documentation, type: enhancement

#7430 Increase parser arrayLimit to 100
  docs/v3.x/concepts/middlewares.md
  packages/strapi/lib/middlewares/parser/defaults.json
  packages/strapi/lib/middlewares/parser/index.js
Labels: source: core:framework, type: enhancement

#7470 Remove tips in login provider tab causing templating issues
  docs/v3.x/plugins/users-permissions.md
Labels: source: documentation, type: enhancement

#7471 Setup docs branch to update directly the documentation branch
  docs/.vuepress/config.js
Labels: source: documentation, type: enhancement

#7441 Add how to change login page's logo
  docs/v3.x/admin-panel/customization.md
Labels: source: documentation, type: enhancement

#7385 Update basic GraphQL Plugin information
  packages/strapi-plugin-graphql/README.md
  packages/strapi-plugin-graphql/package.json
Labels: source: plugin:graphql, type: enhancement

#7476 Boom middleware needs to be loaded before sentry middleware
  docs/v3.x/guides/error-catching.md
Labels: source: documentation, type: enhancement

#7497 Add utils::sanitize-entity tests
  packages/strapi-utils/lib/__tests__/sanitize-entity.test.js
  packages/strapi-utils/lib/sanitize-entity.js
  packages/strapi/lib/core-api/controller.js
Labels: source: core:framework

#7524 Add warning to unit testing guide for windows/SQLite
  docs/v3.x/guides/unit-testing.md
Labels: source: documentation, type: enhancement

#7590 Prevent from uninstalling the upload plugin in the admin panel
  packages/strapi-plugin-upload/package.json
Labels: source: plugin:upload, type: bug

#7597 Fix front-end small issues
  packages/strapi-admin/admin/src/containers/HomePage/index.js
  packages/strapi-plugin-content-type-builder/admin/src/components/CreatableSelect/index.js
Labels: source: admin, source: plugin:content-type-builder, type: bug

#7589 CM bug fixes
  packages/strapi-helper-plugin/package.json
  packages/strapi-plugin-content-manager/admin/src/components/SelectWrapper/index.js
  yarn.lock
Labels: source: plugin:content-manager, type: bug

#7527 Fix decimal on content manager's inputs
  packages/strapi-plugin-content-manager/admin/src/components/Inputs/index.js
Labels: source: plugin:content-manager, type: bug

#7606 Bump Buffet.js version
  packages/strapi-admin/package.json
  packages/strapi-helper-plugin/package.json
  yarn.lock
Labels: dependencies

#7644 GraphQL Typos fixed to improve documentation
  docs/3.0.0-beta.x/guides/count-graphql.md
  docs/v3.x/guides/count-graphql.md
Labels: source: documentation

#7629 add webhooks for draftAndPublish + sanitize all webhooks info
  docs/v3.x/concepts/webhooks.md
  packages/strapi-admin/controllers/Webhooks.js
  packages/strapi-admin/test/admin-role.test.e2e.js
  packages/strapi-plugin-content-manager/services/ContentManager.js
  packages/strapi-plugin-content-manager/services/__tests__/content-manager.test.js
  packages/strapi-plugin-upload/controllers/upload/admin.js
  packages/strapi-plugin-upload/services/Upload.js
  packages/strapi-utils/lib/index.js
  packages/strapi-utils/lib/webhook.js
  packages/strapi/lib/services/__tests__/entity-service.test.js
  packages/strapi/lib/services/entity-service.js
Labels: flag: 💥 Breaking change
