Repository strapi/strapi, pull requests merged in 2020-06, with the labels that each got.

#6327 🚑 Forgot/Reset password fix for MongoDB - only update mandatory fields
  packages/strapi-plugin-users-permissions/controllers/Auth.js
Labels: source: plugin:users-permissions, type: bug

#6451 Fix typo in migration guide to stable
  docs/v3.x/migration-guide/migration-guide-beta.20-to-3.0.0.md
Labels: source: documentation, type: enhancement

#6429 Typo fixes throughout the stable docs
  README.md
  docs/v3.x/concepts/configurations.md
  docs/v3.x/concepts/controllers.md
  docs/v3.x/concepts/customization.md
  docs/v3.x/concepts/models.md
  docs/v3.x/concepts/queries.md
  docs/v3.x/content-api/parameters.md
  docs/v3.x/deployment/caddy-proxy.md
  docs/v3.x/deployment/haproxy-proxy.md
  docs/v3.x/getting-started/quick-start-tutorial.md
  docs/v3.x/getting-started/troubleshooting.md
  docs/v3.x/guides/auth-request.md
  docs/v3.x/guides/client.md
  docs/v3.x/guides/custom-admin.md
  docs/v3.x/guides/custom-data-response.md
  docs/v3.x/guides/is-owner.md
  docs/v3.x/guides/scheduled-publication.md
  docs/v3.x/guides/update-version.md
  docs/v3.x/installation/digitalocean-one-click.md
  docs/v3.x/installation/docker.md
  docs/v3.x/installation/platformsh.md
  docs/v3.x/plugin-development/frontend-development.md
  docs/v3.x/plugin-development/frontend-settings-api.md
  docs/v3.x/plugin-development/quick-start.md
  docs/v3.x/plugins/email.md
  docs/v3.x/plugins/graphql.md
  docs/v3.x/plugins/upload.md
  docs/v3.x/plugins/users-permissions.md
Labels: source: documentation, type: enhancement

#6489 FAQ section of docs update to add notes applied in stable and fix regression
  docs/v3.x/getting-started/troubleshooting.md
Labels: source: documentation, type: enhancement

#6498 Fixed the spelling of 'Troubleshooting'
  docs/3.0.0-beta.x/plugins/email.md
  docs/v3.x/plugins/email.md
Labels: source: documentation, type: enhancement

#6507 Fix link CLI installation
  docs/v3.x/getting-started/quick-start-tutorial.md
Labels: source: documentation, type: enhancement

#5614 Added uid slugify options
  docs/v3.x/concepts/models.md
  packages/strapi-plugin-content-manager/services/__tests__/uid.test.js
  packages/strapi-plugin-content-manager/services/uid.js
  packages/strapi-plugin-content-type-builder/controllers/validation/types.js
Labels: source: plugin:content-manager, type: enhancement

#6275 Update documentation of the section plugin Google Cloud Storage
  docs/3.0.0-beta.x/deployment/google-app-engine.md
  docs/v3.x/deployment/google-app-engine.md
Labels: source: documentation, type: enhancement

#6361 Add guide on unit testing
  docs/.vuepress/config.js
  docs/v3.x/guides/unit-testing.md
Labels: source: documentation, type: enhancement

#6426 Fix links in deployment page
  docs/3.0.0-beta.x/getting-started/deployment.md
Labels: source: documentation, type: enhancement

#6521 Update slug guide match the v3 life cycle documentation
  docs/v3.x/guides/slug.md
Labels: source: documentation, type: enhancement

#6557 Remove cypress because it is not used
  .eslintrc.js
  cypress/fixtures/api/category.json
  cypress/fixtures/api/product.json
  cypress/fixtures/api/tag.json
  cypress/fixtures/seeds/category.json
  cypress/fixtures/seeds/product.json
  cypress/fixtures/seeds/tag.json
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  package.json
  packages/strapi/lib/commands/develop.js
  test/cypress.js
  yarn.lock
Labels: source: core:framework, type: bug

#6463 Fixing messages when uninstalling plugins
  packages/strapi-admin/admin/src/containers/InstalledPluginsPage/index.js
  packages/strapi-admin/admin/src/translations/en.json
  packages/strapi-admin/admin/src/translations/pt-BR.json
Labels: source: admin, type: enhancement

#6563 Fix bootstrap use cases
  docs/3.0.0-beta.x/concepts/configurations.md
  docs/v3.x/concepts/configurations.md
Labels: source: documentation, type: enhancement

#6574 Fix singularName resolver for GraphQL findOne action
  packages/strapi-plugin-graphql/services/type-definitions.js
Labels: source: plugin:graphql, type: bug

#6599 better error handling in email
  docs/v3.x/deployment/amazon-aws.md
  docs/v3.x/plugins/email.md
  packages/strapi-plugin-email/controllers/Email.js
  packages/strapi-provider-email-amazon-ses/lib/index.js
  packages/strapi-provider-email-mailgun/lib/index.js
  packages/strapi-provider-email-sendgrid/lib/index.js
  packages/strapi-provider-email-sendmail/lib/index.js
Labels: source: plugin:email, type: bug

#6602 Update Contrib guide defining documentation pull requests
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
Labels: source: documentation, type: enhancement

#6469 Remove options pool for non sqlite3 clients
  packages/strapi-connector-bookshelf/lib/knex.js
Labels: source: core:database, type: bug

#6394 Add Malay(ms.json) Translation
  packages/strapi-admin/admin/src/containers/LocaleToggle/index.js
  packages/strapi-admin/admin/src/containers/LocaleToggle/tests/index.test.js
  packages/strapi-admin/admin/src/translations/index.js
  packages/strapi-admin/admin/src/translations/ms.json
  packages/strapi-generate-plugin/files/admin/src/translations/index.js
  packages/strapi-generate-plugin/files/admin/src/translations/ms.json
  packages/strapi-plugin-content-manager/admin/src/translations/index.js
  packages/strapi-plugin-content-manager/admin/src/translations/ms.json
  packages/strapi-plugin-content-type-builder/admin/src/translations/index.js
  packages/strapi-plugin-content-type-builder/admin/src/translations/ms.json
  packages/strapi-plugin-documentation/admin/src/translations/index.js
  packages/strapi-plugin-documentation/admin/src/translations/ms.json
  packages/strapi-plugin-email/admin/src/translations/index.js
  packages/strapi-plugin-email/admin/src/translations/ms.json
  packages/strapi-plugin-upload/admin/src/translations/index.js
  packages/strapi-plugin-upload/admin/src/translations/ms.json
  packages/strapi-plugin-users-permissions/admin/src/translations/index.js
  packages/strapi-plugin-users-permissions/admin/src/translations/ms.json
Labels: source: admin, source: plugin:content-manager, source: plugin:content-type-builder, source: plugin:documentation, source: plugin:email, source: plugin:graphql, source: plugin:upload, source: plugin:users-permissions, type: enhancement

#6536 added Japanese translations
  packages/strapi-admin/admin/src/translations/ja.json
Labels: source: admin, type: enhancement

#6656 docs: Fix a few typos in the 3rd party client guide
  docs/v3.x/guides/client.md
Labels: source: documentation, type: enhancement

#6657 Typo error
  docs/v3.x/guides/custom-data-response.md
Labels: source: documentation, type: enhancement

#6629 Fix some user permission issue
  packages/strapi-plugin-users-permissions/config/functions/bootstrap.js
  packages/strapi-plugin-users-permissions/config/policies/rateLimit.js
  packages/strapi-plugin-users-permissions/controllers/Auth.js
  packages/strapi-plugin-users-permissions/controllers/UsersPermissions.js
  packages/strapi-plugin-users-permissions/controllers/validation/__tests__/email-template.test.js
  packages/strapi-plugin-users-permissions/controllers/validation/email-template.js
Labels: source: plugin:users-permissions, type: enhancement

#6601 Modified admin.path to admin.url
  docs/v3.x/admin-panel/customization.md
Labels: source: documentation, type: enhancement

#6572 Update slug system to new lifecycle hooks
  docs/v3.x/guides/slug.md
Labels: source: documentation, type: enhancement

#6546 Remove platform check
  packages/strapi-plugin-users-permissions/controllers/Auth.js
Labels: source: plugin:users-permissions, type: bug

#6439 Update translation support on 'users-permissions' , 'upload' and 'content-manager' plugin
  packages/strapi-plugin-content-manager/admin/src/components/DynamicZone/index.js
  packages/strapi-plugin-content-manager/admin/src/translations/en.json
  packages/strapi-plugin-upload/admin/src/containers/InputModalStepper/InputModalStepper.js
  packages/strapi-plugin-upload/admin/src/containers/ModalStepper/index.js
  packages/strapi-plugin-upload/admin/src/translations/en.json
  packages/strapi-plugin-users-permissions/admin/src/components/ListRow/index.js
  packages/strapi-plugin-users-permissions/admin/src/translations/en.json
Labels: source: admin, type: enhancement

#6620 Add reserved names for attributes (Enum and Relations)
  packages/strapi-plugin-content-type-builder/admin/src/containers/FormModal/utils/forms.js
Labels: source: plugin:content-type-builder, type: bug

#6494 Load image from file to fix the caddy logo
  docs/v3.x/assets/deployment/caddy-monotone.svg
  docs/v3.x/getting-started/deployment.md
Labels: source: documentation, type: enhancement

#6633 Clean up the stable migration guide
  docs/v3.x/migration-guide/migration-guide-beta.20-to-3.0.0.md
Labels: source: documentation, type: enhancement

#6679 Fixed misspelled lifecycle hook in documentation
  docs/v3.x/concepts/models.md
Labels: source: documentation, type: enhancement

#6662 Should be port 5432
  docs/v3.x/deployment/digitalocean.md
Labels: source: documentation, type: enhancement

#6652 Very slight improvement of the webhook definition
  docs/v3.x/concepts/webhooks.md
Labels: source: documentation, type: enhancement

#6635 Fixed Typo on v3.x
  docs/3.0.0-beta.x/concepts/services.md
  docs/v3.x/concepts/services.md
Labels: source: documentation, type: enhancement

#6621 Fixed misspelled word
  docs/v3.x/concepts/models.md
Labels: source: documentation, type: enhancement

#6539 Fix typo in model relations docs
  docs/3.0.0-beta.x/concepts/models.md
Labels: source: documentation, type: enhancement

#6636 Remove outdated docs for stable admin customization
  docs/v3.x/admin-panel/customization.md
Labels: source: documentation, type: enhancement

#6691 Fix the engine info in the package.json
  CONTRIBUTING.md
  README.md
  examples/getstarted/package.json
  package.json
  packages/create-strapi-app/package.json
  packages/strapi-admin/package.json
  packages/strapi-connector-bookshelf/package.json
  packages/strapi-connector-mongoose/package.json
  packages/strapi-database/package.json
  packages/strapi-generate-api/package.json
  packages/strapi-generate-controller/package.json
  packages/strapi-generate-model/package.json
  packages/strapi-generate-new/package.json
  packages/strapi-generate-plugin/package.json
  packages/strapi-generate-policy/package.json
  packages/strapi-generate-service/package.json
  packages/strapi-generate/package.json
  packages/strapi-helper-plugin/package.json
  packages/strapi-hook-ejs/package.json
  packages/strapi-hook-redis/package.json
  packages/strapi-middleware-views/package.json
  packages/strapi-plugin-content-manager/package.json
  packages/strapi-plugin-content-type-builder/package.json
  packages/strapi-plugin-documentation/package.json
  packages/strapi-plugin-email/package.json
  packages/strapi-plugin-graphql/package.json
  packages/strapi-plugin-upload/package.json
  packages/strapi-plugin-users-permissions/package.json
  packages/strapi-provider-email-amazon-ses/package.json
  packages/strapi-provider-email-mailgun/package.json
  packages/strapi-provider-email-sendgrid/package.json
  packages/strapi-provider-email-sendmail/package.json
  packages/strapi-provider-upload-aws-s3/package.json
  packages/strapi-provider-upload-cloudinary/package.json
  packages/strapi-provider-upload-local/package.json
  packages/strapi-provider-upload-rackspace/package.json
  packages/strapi-utils/package.json
  packages/strapi/package.json
Labels: source: core:framework, type: enhancement

#6696 Fix init reset password permission
  packages/strapi-plugin-users-permissions/services/UsersPermissions.js
Labels: source: plugin:users-permissions, type: bug

#6524 Add info to custom resolvers and add formatError to GraphQL service
  packages/strapi-plugin-graphql/hooks/graphql/index.js
  packages/strapi-plugin-graphql/services/resolvers-builder.js
Labels: source: plugin:graphql, type: enhancement

#6694 Security middlewares csp option added
  docs/v3.x/concepts/middlewares.md
Labels: source: documentation, type: enhancement

#6663 Fixed input checkbox behavior
  packages/strapi-plugin-users-permissions/admin/src/components/Controller/index.js
  packages/strapi-plugin-users-permissions/admin/src/components/InputCheckboxPlugin/Components.js
  packages/strapi-plugin-users-permissions/admin/src/components/InputCheckboxPlugin/index.js
  packages/strapi-plugin-users-permissions/admin/src/components/Plugin/index.js
Labels: source: plugin:users-permissions, type: bug

#6709 Update upload providers README to reflect stable changes
  packages/strapi-provider-upload-aws-s3/README.md
  packages/strapi-provider-upload-cloudinary/README.md
  packages/strapi-provider-upload-rackspace/README.md
Labels: source: documentation, type: enhancement

#6626 createPluginsJs after copyCustomAdmin
  packages/strapi-admin/index.js
Labels: source: admin, type: enhancement

#6167 Russian translation for Media Library
  packages/strapi-admin/admin/src/translations/en.json
  packages/strapi-admin/admin/src/translations/ru.json
  packages/strapi-plugin-upload/admin/src/translations/index.js
  packages/strapi-plugin-upload/admin/src/translations/ru.json
Labels: source: admin, type: enhancement

#6732 Only pick required fields to register for newsletter updates
  packages/strapi-admin/admin/src/containers/AuthPage/index.js
Labels: source: admin, type: bug

#6738 Fixes #6733
  packages/strapi-plugin-users-permissions/admin/src/components/Controller/index.js
Labels: source: plugin:users-permissions, type: bug

#6779 Fixes #6775
  packages/strapi-admin/package.json
  packages/strapi-helper-plugin/package.json
  packages/strapi-plugin-content-manager/package.json
  packages/strapi-plugin-content-type-builder/package.json
  packages/strapi-plugin-documentation/package.json
  packages/strapi-plugin-upload/package.json
  packages/strapi-plugin-users-permissions/package.json
Labels: source: admin, type: bug

#6781 Fix links wrong documentation version
  docs/v3.x/migration-guide/migration-guide-alpha.26-to-beta.md
  docs/v3.x/migration-guide/migration-guide-beta.15-to-beta.16.md
  docs/v3.x/migration-guide/migration-guide-beta.19-to-beta.20.md
Labels: source: documentation, type: enhancement

#6764 fix missing images on index.html
  packages/strapi/lib/middlewares/public/assets/images/group_people_1.png
  packages/strapi/lib/middlewares/public/assets/images/group_people_2.png
  packages/strapi/lib/middlewares/public/assets/images/group_people_3.png
  packages/strapi/lib/middlewares/public/assets/images/logo_login.png
  packages/strapi/lib/middlewares/public/index.html
  packages/strapi/lib/middlewares/public/index.js
  packages/strapi/lib/middlewares/public/serve-static.js
Labels: source: core:framework, type: bug

#6753 scoped packages doc
  docs/v3.x/plugins/email.md
  docs/v3.x/plugins/upload.md
Labels: source: documentation, type: enhancement

#6525 Fix cloudinary upload error message
  packages/strapi-provider-upload-cloudinary/lib/index.js
Labels: source: plugin:upload, type: enhancement

#6786 [typofix] Client ID > Client Secret
  docs/3.0.0-beta.x/plugins/users-permissions.md
  docs/v3.x/plugins/users-permissions.md
Labels: source: documentation, type: enhancement

#6797 Support STRAPI_UUID_PREFIX env var
  packages/strapi-generate-new/lib/index.js
Labels: source: core:framework, type: enhancement

#6724 Fix docs links 404
  docs/3.0.0-beta.x/concepts/services.md
  docs/3.0.0-beta.x/deployment/amazon-aws.md
  docs/3.0.0-beta.x/deployment/digitalocean.md
  docs/3.0.0-beta.x/getting-started/deployment.md
  docs/3.0.0-beta.x/getting-started/installation.md
  docs/3.0.0-beta.x/getting-started/quick-start.md
  docs/3.0.0-beta.x/guides/draft.md
  docs/3.0.0-beta.x/guides/send-email.md
  docs/3.0.0-beta.x/migration-guide/migration-guide-alpha.15-to-alpha.16.md
  docs/3.0.0-beta.x/plugins/graphql.md
  docs/v3.x/concepts/services.md
  docs/v3.x/deployment/amazon-aws.md
  docs/v3.x/deployment/digitalocean.md
  docs/v3.x/getting-started/deployment.md
  docs/v3.x/getting-started/installation.md
  docs/v3.x/getting-started/quick-start.md
  docs/v3.x/guides/draft.md
  docs/v3.x/guides/send-email.md
  docs/v3.x/guides/unit-testing.md
  docs/v3.x/migration-guide/migration-guide-alpha.15-to-alpha.16.md
  docs/v3.x/plugins/email.md
  docs/v3.x/plugins/graphql.md
Labels: source: documentation, type: enhancement

#5971 Fixes for Media Library upload
  packages/strapi-plugin-upload/package.json
  packages/strapi-plugin-upload/services/Upload.js
  packages/strapi-plugin-upload/services/__tests__/upload.test.js
  packages/strapi-plugin-upload/services/image-manipulation.js
  packages/strapi-plugin-upload/test/graphqlUpload.test.e2e.js
  packages/strapi-plugin-upload/test/upload.test.e2e.js
  test/helpers/request.js
  yarn.lock
Labels: source: plugin:upload, type: enhancement

#6802 Fix 404 link in the DO deployment guide
  docs/v3.x/deployment/digitalocean.md
Labels: source: documentation, type: enhancement
