Repository strapi/strapi, pull requests merged in 2021-02, with the labels that each got.

#9263 Fix input UID label
  packages/strapi-plugin-content-manager/admin/src/components/InputUID/index.js
Labels: source: plugin:content-manager, type: bug

#8490 Fix undefined filter value
  packages/strapi-utils/lib/build-query.js
Labels: source: core:framework, type: enhancement

#9249 Adds missing import for italian translation of upload plugin
  packages/strapi-plugin-upload/admin/src/translations/index.js
Labels: source: plugin:upload, type: translation

#9293 Improve front end development
  packages/strapi-admin/index.js
Labels: source: admin, type: enhancement

#8477 Update target.js: Change assignment of "ok" in "isValidTarget" function
  packages/strapi-generate/lib/target.js
Labels: source: core:cli, type: enhancement

#9223 Fix WYSIWYG Reverse text
  packages/strapi-plugin-content-manager/admin/src/components/Wysiwyg/index.js
Labels: source: plugin:content-manager, type: bug

#9306 Fix idsToOmit
  packages/strapi-plugin-content-manager/admin/src/components/SelectWrapper/index.js
Labels: source: plugin:content-manager, type: bug

#8457 Bug: Erroneous error if there is a database configuration for a custom session middleware storage provider.
  packages/strapi/lib/middlewares/session/__tests__/session.test.js
  packages/strapi/lib/middlewares/session/index.js
Labels: source: core:framework, type: bug

#9310 Fix sanitize removing polymorphic relations
  packages/strapi-utils/lib/sanitize-entity.js
Labels: source: core:framework, type: bug

#9286 Fix some many many perf issues in graphQL
  packages/strapi-plugin-graphql/services/type-definitions.js
Labels: source: plugin:graphql, type: bug

#9348 Fix crash when database (SQL) options are not defined
  packages/strapi-connector-bookshelf/lib/knex.js
Labels: source: core:database, type: bug

#9226 CTB form extensions
  packages/strapi-admin/admin/src/app.js
  packages/strapi-admin/admin/src/utils/Plugin.js
  packages/strapi-admin/admin/src/utils/Strapi.js
  packages/strapi-plugin-content-type-builder/admin/src/components/CheckboxWithDescription/Wrapper.js
  packages/strapi-plugin-content-type-builder/admin/src/components/CheckboxWithDescription/index.js
  packages/strapi-plugin-content-type-builder/admin/src/components/CustomCheckbox/StyledCustomCheckbox.js
  packages/strapi-plugin-content-type-builder/admin/src/components/CustomCheckbox/index.js
  packages/strapi-plugin-content-type-builder/admin/src/containers/DataManagerProvider/index.js
  packages/strapi-plugin-content-type-builder/admin/src/containers/FormModal/attributes/advancedForm.js
  packages/strapi-plugin-content-type-builder/admin/src/containers/FormModal/forms/index.js
  packages/strapi-plugin-content-type-builder/admin/src/containers/FormModal/forms/tests/index.test.js
  packages/strapi-plugin-content-type-builder/admin/src/containers/FormModal/index.js
  packages/strapi-plugin-content-type-builder/admin/src/containers/FormModal/reducer.js
  packages/strapi-plugin-content-type-builder/admin/src/index.js
  packages/strapi-plugin-content-type-builder/admin/src/utils/formAPI.js
  packages/strapi-plugin-content-type-builder/admin/src/utils/tests/formAPI.test.js
  packages/strapi-plugin-i18n/admin/src/components/CheckboxConfirmation/Wrapper.js
  packages/strapi-plugin-i18n/admin/src/components/CheckboxConfirmation/index.js
  packages/strapi-plugin-i18n/admin/src/index.js
  packages/strapi-plugin-i18n/admin/src/middlewares/extendCTBAttributeInitialDataMiddleware.js
  packages/strapi-plugin-i18n/admin/src/middlewares/extendCTBInitialDataMiddleware.js
  packages/strapi-plugin-i18n/admin/src/middlewares/index.js
  packages/strapi-plugin-i18n/admin/src/middlewares/tests/extendCTBAttrributeInitialDataMiddleware.test.js
  packages/strapi-plugin-i18n/admin/src/middlewares/tests/extendCTBInitialDataMiddleware.test.js
  packages/strapi-plugin-i18n/admin/src/translations/en.json
  packages/strapi-plugin-i18n/admin/src/utils/localizedFields.js
  packages/strapi-plugin-i18n/admin/src/utils/mutateCTBContentTypeSchema.js
  packages/strapi-plugin-i18n/admin/src/utils/tests/mutateCTBContentTypeSchema.test.js
Labels: flag: don't merge

#9330 Do not use npm v7 on new projects
  packages/strapi-generate-new/lib/resources/json/package.json.js
Labels: source: core:framework, type: bug

#9341 UI - Make policies components sticky
  packages/strapi-admin/admin/src/containers/Admin/Wrapper.js
  packages/strapi-plugin-users-permissions/admin/src/components/Policies/Components.js
  packages/strapi-plugin-users-permissions/admin/src/components/Policies/index.js
Labels: source: plugin:users-permissions, type: enhancement

#9367 Fix mongoose autopopulate recursively looping to infinity when cycles…
  packages/strapi-connector-mongoose/lib/mount-models.js
Labels: source: core:database, type: bug

#9380 Update README.md
  README.md
Labels: source: documentation, type: enhancement

#9387 Translation Update (german)
  packages/strapi-admin/admin/src/translations/de.json
  packages/strapi-plugin-content-type-builder/admin/src/translations/de.json
  packages/strapi-plugin-documentation/admin/src/translations/de.json
Labels: source: admin, type: translation

#9381 plugin-documentation: added enum for associations
  packages/strapi-plugin-documentation/services/Documentation.js
Labels: source: plugin:documentation, type: bug

#9379 plugin-documentation: added missed manyWay relation
  packages/strapi-plugin-documentation/services/Documentation.js
Labels: source: plugin:documentation, type: bug

#8773 Enable develop --polling flag to watch file changes in network directories
  packages/strapi/bin/strapi.js
  packages/strapi/lib/commands/develop.js
Labels: source: core:cli, type: enhancement

#9191 strapi-plugin-upload accepts localServer configuration
  packages/strapi-plugin-upload/middlewares/upload/index.js
Labels: source: plugin:upload, type: enhancement

#9339 Fix/mongoose ca
  packages/strapi-connector-mongoose/lib/index.js
Labels: source: core:database, type: enhancement

#9417 Fix pool config
  packages/strapi-connector-bookshelf/lib/knex.js
Labels: source: core:database, type: bug

#8890 Add Sentry plugin
  packages/strapi-generate-new/package.json
  packages/strapi-plugin-sentry/.editorconfig
  packages/strapi-plugin-sentry/.gitattributes
  packages/strapi-plugin-sentry/.gitignore
  packages/strapi-plugin-sentry/.npmignore
  packages/strapi-plugin-sentry/LICENSE
  packages/strapi-plugin-sentry/README.md
  packages/strapi-plugin-sentry/admin/src/assets/images/logo.svg
  packages/strapi-plugin-sentry/admin/src/index.js
  packages/strapi-plugin-sentry/admin/src/pluginId.js
  packages/strapi-plugin-sentry/admin/src/translations/ar.json
  packages/strapi-plugin-sentry/admin/src/translations/cs.json
  packages/strapi-plugin-sentry/admin/src/translations/de.json
  packages/strapi-plugin-sentry/admin/src/translations/en.json
  packages/strapi-plugin-sentry/admin/src/translations/es.json
  packages/strapi-plugin-sentry/admin/src/translations/fr.json
  packages/strapi-plugin-sentry/admin/src/translations/id.json
  packages/strapi-plugin-sentry/admin/src/translations/index.js
  packages/strapi-plugin-sentry/admin/src/translations/it.json
  packages/strapi-plugin-sentry/admin/src/translations/ko.json
  packages/strapi-plugin-sentry/admin/src/translations/ms.json
  packages/strapi-plugin-sentry/admin/src/translations/nl.json
  packages/strapi-plugin-sentry/admin/src/translations/pl.json
  packages/strapi-plugin-sentry/admin/src/translations/pt-BR.json
  packages/strapi-plugin-sentry/admin/src/translations/pt.json
  packages/strapi-plugin-sentry/admin/src/translations/ru.json
  packages/strapi-plugin-sentry/admin/src/translations/sk.json
  packages/strapi-plugin-sentry/admin/src/translations/th.json
  packages/strapi-plugin-sentry/admin/src/translations/tr.json
  packages/strapi-plugin-sentry/admin/src/translations/uk.json
  packages/strapi-plugin-sentry/admin/src/translations/vi.json
  packages/strapi-plugin-sentry/admin/src/translations/zh-Hans.json
  packages/strapi-plugin-sentry/admin/src/translations/zh.json
  packages/strapi-plugin-sentry/config/functions/bootstrap.js
  packages/strapi-plugin-sentry/config/routes.json
  packages/strapi-plugin-sentry/config/settings.json
  packages/strapi-plugin-sentry/controllers/sentry.js
  packages/strapi-plugin-sentry/middlewares/sentry/defaults.json
  packages/strapi-plugin-sentry/middlewares/sentry/index.js
  packages/strapi-plugin-sentry/package.json
  packages/strapi-plugin-sentry/services/__tests__/sentry.test.js
  packages/strapi-plugin-sentry/services/sentry.js
  yarn.lock
Labels: source: plugin:sentry, type: feature request

#9316 added a way to have a less expensive search
  packages/strapi-connector-bookshelf/lib/queries.js
  packages/strapi-connector-mongoose/lib/buildQuery.js
Labels: source: plugin:content-type-builder, type: enhancement

#9422 fix #8914 allow multiple images to be inserted into wysiwyg
  packages/strapi-plugin-content-manager/admin/src/components/Wysiwyg/MediaLib.js
  packages/strapi-plugin-content-manager/admin/src/components/Wysiwyg/index.js
Labels: source: plugin:content-manager, type: bug

#9441 Fix sanitize polymorphic entities that can be undefined or ids only
  packages/strapi-utils/lib/sanitize-entity.js
Labels: source: core:framework, type: bug

#9388 Tests: Explicit sorting where we test offset and limit
  packages/strapi/tests/deepFiltering.test.e2e.js
  packages/strapi/tests/filtering.test.e2e.js
  packages/strapi/tests/search.test.e2e.js
Labels: source: core:tooling, type: enhancement

#9449 Fix repository url in strapi-admin/package.json
  packages/strapi-admin/package.json
Labels: source: documentation, type: enhancement

#9407 Add demo link on top of the README to be more visible
  README.md
Labels: type: enhancement

#9477 Update of webpack configuration: fix #9442
  packages/strapi-admin/webpack.config.js
Labels: source: admin, type: bug

#9464 Stop populating component when populating relation to avoid infinitie…
  packages/strapi-connector-mongoose/lib/mount-models.js
Labels: source: core:database, type: bug

#9493 Fix watch-admin in EE mode
  packages/strapi/lib/commands/watchAdmin.js
Labels: source: core:framework, type: bug

#9511 Fix knex, pg, mysql versions
  examples/getstarted/package.json
  packages/strapi-connector-bookshelf/package.json
  packages/strapi-generate-new/lib/utils/db-client-dependencies.js
Labels: source: core:database, type: bug
